app.version=@project.version@
build.revision=@project.version@
build.time=@maven.build.timestamp@
desktop.compatibility.baseline=@desktop.compatibility.baseline@
android.compatibility.baseline=@android.compatibility.baseline@
android.latest.version=@android.latest.version@
ios.compatibility.baseline=@ios.compatibility.baseline@
ios.latest.version=@ios.latest.version@
