CREATE TABLE IF NOT EXISTS sales_charge (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_id        INTEGER NOT NULL REFERENCES sales_header(id) ON DELETE CASCADE,
    sequence_no     INTEGER NOT NULL,
    charge_code     TEXT NOT NULL,
    charge_name     TEXT NOT NULL,
    amount          NUMERIC(19,2) NOT NULL CHECK (amount > 0),
    taxable         BOOLEAN NOT NULL DEFAULT FALSE,
    gst_percent     NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (gst_percent >= 0 AND gst_percent <= 100),
    CONSTRAINT uq_sales_charge_sequence UNIQUE (sales_id, sequence_no)
);

CREATE INDEX IF NOT EXISTS idx_sales_charge_sales_id ON sales_charge(sales_id);

INSERT INTO sales_charge(sales_id, sequence_no, charge_code, charge_name, amount, taxable, gst_percent)
SELECT h.id, 1,
       COALESCE(NULLIF(BTRIM(h.charge_type), ''), 'Charges'),
       COALESCE(NULLIF(BTRIM(h.charge_type), ''), 'Charges'),
       ROUND(h.charge_amount::numeric, 2), FALSE, 0
FROM sales_header h
WHERE COALESCE(h.charge_amount, 0) > 0
  AND NOT EXISTS (SELECT 1 FROM sales_charge c WHERE c.sales_id = h.id);
