package org.example.server.reconciliation;

import org.example.server.persistence.entity.*;
import org.example.server.persistence.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;

@Service
public class BankReconciliationService {
 private static final Set<String> RESOLVED=Set.of("MATCHED","EXPENSE","IGNORED");
 private final BankStatementImportRepository imports; private final BankStatementTransactionRepository txs; private final BankReconciliationAllocationRepository allocations; private final BankReconciliationAuditRepository audits; private final PaymentRecordRepository payments; private final SalesHeaderRepository sales; private final PurchaseHeaderRepository purchases; private final FinanceRegisterRepository finance;
 public BankReconciliationService(BankStatementImportRepository imports,BankStatementTransactionRepository txs,BankReconciliationAllocationRepository allocations,BankReconciliationAuditRepository audits,PaymentRecordRepository payments,SalesHeaderRepository sales,PurchaseHeaderRepository purchases,FinanceRegisterRepository finance){this.imports=imports;this.txs=txs;this.allocations=allocations;this.audits=audits;this.payments=payments;this.sales=sales;this.purchases=purchases;this.finance=finance;}

 @Transactional
 public BankReconciliationDtos.ImportResult importStatement(BankReconciliationDtos.ImportRequest r){
  if(r==null||blank(r.bankAccount())||blank(r.sourceFingerprint()))throw new IllegalArgumentException("Bank account and source fingerprint are required.");
  var prior=imports.findBySourceFingerprint(r.sourceFingerprint()); if(prior.isPresent())throw new IllegalStateException("This exact bank statement file has already been imported.");
  BankStatementImportEntity b=new BankStatementImportEntity(); b.setBankName(blank(r.bankName())?"Bank":r.bankName().trim());b.setBankAccount(r.bankAccount().trim());b.setAccountHolder(r.accountHolder());b.setStatementFrom(r.statementFrom());b.setStatementTo(r.statementTo());b.setCurrency(blank(r.currency())?"INR":r.currency());b.setOpeningBalance(r.openingBalance());b.setClosingBalance(r.closingBalance());b.setSourceFingerprint(r.sourceFingerprint());b.setSourceFileName(r.sourceFileName());b.setSourceCsv(r.sourceCsv());b.setImportedBy(r.importedBy());b.setTransactionCount(0);b.setTotalDebit(0d);b.setTotalCredit(0d);b.setReconciledCount(0);b.setReconciliationPercent(0d);b=imports.save(b);
  int added=0,dupes=0; double debit=0,credit=0;
  if(r.rows()!=null)for(var row:r.rows()){
   if(blank(row.transactionFingerprint())||txs.existsByTransactionFingerprint(row.transactionFingerprint())){dupes++;continue;}
   BankStatementTransactionEntity t=new BankStatementTransactionEntity();t.setImportBatch(b);t.setSourceRowNumber(row.sourceRowNumber());t.setTransactionTimestamp(row.transactionTimestamp());t.setTransactionDate(row.transactionDate());t.setValueDate(row.valueDate());t.setOriginalDescription(row.description());t.setOriginalReference(row.reference());t.setDebitAmount(row.debit());t.setCreditAmount(row.credit());t.setBalance(row.balance());t.setTransactionFingerprint(row.transactionFingerprint());txs.save(t);applySuggestion(t);added++;debit+=row.debit();credit+=row.credit();audit(t,"IMPORTED","Imported from "+r.sourceFileName(),null,t.getStatus(),r.importedBy());
  }
  if(added==0){imports.delete(b);throw new IllegalStateException("All transactions in this statement were already imported.");}
  b.setTransactionCount(added);b.setTotalDebit(debit);b.setTotalCredit(credit);imports.save(b);refreshBatch(b.getId());return new BankReconciliationDtos.ImportResult(batch(b),added,dupes);
 }

 public List<BankReconciliationDtos.BatchDto> batches(){return imports.findAllByOrderByImportedAtDesc().stream().map(this::batch).toList();}
 public BankReconciliationDtos.SourceDto source(Long importId){var b=imports.findById(importId).orElseThrow(()->new IllegalArgumentException("Statement batch not found."));return new BankReconciliationDtos.SourceDto(b.getSourceFileName(),b.getSourceFingerprint(),b.getSourceCsv());}
 public List<BankReconciliationDtos.TransactionDto> transactions(Long importId){return txs.findByImportBatchIdOrderByTransactionTimestampAscIdAsc(importId).stream().map(this::transaction).toList();}
 public BankReconciliationDtos.Metrics metrics(Long importId){var list=txs.findByImportBatchIdOrderByTransactionTimestampAscIdAsc(importId);int unmatched=0,suggested=0,matched=0,expenses=0,ignored=0,review=0,resolved=0;double cr=0,dr=0;for(var t:list){cr+=n(t.getCreditAmount());dr+=n(t.getDebitAmount());switch(up(t.getStatus())){case"SUGGESTED"->suggested++;case"MATCHED"->{matched++;resolved++;}case"EXPENSE"->{expenses++;resolved++;}case"IGNORED"->{ignored++;resolved++;}case"REVIEW"->review++;default->unmatched++;}}double pct=list.isEmpty()?0:resolved*100d/list.size();String status=list.isEmpty()?"IMPORTED":resolved==list.size()?"FULLY RECONCILED":resolved==0?"IMPORTED":"PARTIALLY RECONCILED";return new BankReconciliationDtos.Metrics(list.size(),unmatched,suggested,matched,expenses,ignored,review,cr,dr,resolved,pct,status);}

 @Transactional public List<BankReconciliationDtos.CandidateDto> suggest(Long id){var t=reqTxForUpdate(id);applySuggestion(t);txs.save(t);refreshBatch(t.getImportBatch().getId());return candidates(id);}
 public List<BankReconciliationDtos.CandidateDto> candidates(Long id){var t=reqTx(id);List<BankReconciliationDtos.CandidateDto> out=new ArrayList<>();if(n(t.getCreditAmount())>0){for(var s:sales.findAllByOrderByInvoiceDateDescIdDesc()){double outstanding=Math.max(0,n(s.getTotalAmount())-n(s.getPaidAmount()));if(outstanding>.009&&!cancelled(s.getDocumentStatus()))out.add(candidate(t,"SALE",s.getId(),s.getInvoiceNo(),s.getCustomer()==null?"":s.getCustomer().getName(),s.getInvoiceDate(),n(s.getTotalAmount()),n(s.getPaidAmount()),outstanding));}}else{for(var p:purchases.findAllByOrderByInvoiceDateDescIdDesc()){double outstanding=Math.max(0,n(p.getTotalAmount())-n(p.getPaidAmount()));if(outstanding>.009&&!cancelled(p.getDocumentStatus()))out.add(candidate(t,"PURCHASE",p.getId(),p.getInvoiceNo(),p.getSupplier()==null?"":p.getSupplier().getName(),p.getInvoiceDate(),n(p.getTotalAmount()),n(p.getPaidAmount()),outstanding));}}out.sort(Comparator.comparingDouble(BankReconciliationDtos.CandidateDto::confidence).reversed().thenComparingDouble(x->Math.abs(x.outstanding()-bankAmount(t))));return out.stream().limit(30).toList();}

 @Transactional public BankReconciliationDtos.OperationResult match(Long id,BankReconciliationDtos.MatchRequest r){
  var t=reqTxForUpdate(id);ensureProcessable(t);if(r==null||r.allocations()==null||r.allocations().isEmpty())throw new IllegalArgumentException("Select at least one Sales/Purchase transaction.");double bank=bankAmount(t),sum=r.allocations().stream().mapToDouble(BankReconciliationDtos.AllocationRequest::amount).sum();if(!Double.isFinite(sum)||Math.abs(sum-bank)>.01)throw new IllegalArgumentException("Allocated amount must equal the bank transaction amount ("+fmt(bank)+").");String expected=n(t.getCreditAmount())>0?"SALE":"PURCHASE";for(var a:r.allocations())if(!expected.equals(up(a.targetType())))throw new IllegalArgumentException("Bank direction can only match "+expected+" transactions.");
  FinanceRegisterEntity f=new FinanceRegisterEntity();f.setVoucherNo("BST-"+id);f.setVoucherType(expected.equals("SALE")?"BANK DEPOSIT":"BANK WITHDRAWAL");f.setVoucherDate(t.getTransactionDate());f.setCategory(expected.equals("SALE")?"Deposit":"Withdrawal");f.setReferenceNo(t.getOriginalReference());f.setAmount(bank);f.setPaymentMode("Bank Statement");f.setNotes("Matched from imported bank statement: "+safe(t.getOriginalDescription()));f.setAccountName(t.getImportBatch().getBankName()+" - "+t.getImportBatch().getBankAccount());f.setReconciled(1);f.setCreatedAt(LocalDateTime.now().toString());f=finance.save(f);
  for(var a:r.allocations()){
   double amount=a.amount();if(!Double.isFinite(amount)||amount<=0)throw new IllegalArgumentException("Allocation amount must be a finite number greater than zero.");Integer partyId=null;String docNo;
   if(expected.equals("SALE")){var s=sales.findByIdForUpdate(a.targetId()).orElseThrow(()->new IllegalArgumentException("Sales invoice not found."));double outstanding=Math.max(0,n(s.getTotalAmount())-n(s.getPaidAmount()));if(amount>outstanding+.01)throw new IllegalArgumentException("Allocation exceeds outstanding balance for "+s.getInvoiceNo());double paid=n(s.getPaidAmount())+amount;s.setPaidAmount(paid);s.setPaymentStatus(paid+0.01>=n(s.getTotalAmount())?"PAID":"PARTIAL");sales.save(s);partyId=s.getCustomer()==null?null:s.getCustomer().getId();docNo=s.getInvoiceNo();
   }else{var p=purchases.findByIdForUpdate(a.targetId()).orElseThrow(()->new IllegalArgumentException("Purchase invoice not found."));double outstanding=Math.max(0,n(p.getTotalAmount())-n(p.getPaidAmount()));if(amount>outstanding+.01)throw new IllegalArgumentException("Allocation exceeds outstanding balance for "+p.getInvoiceNo());double paid=n(p.getPaidAmount())+amount;p.setPaidAmount(paid);p.setPaymentStatus(paid+0.01>=n(p.getTotalAmount())?"PAID":"PARTIAL");purchases.save(p);partyId=p.getSupplier()==null?null:p.getSupplier().getId();docNo=p.getInvoiceNo();}
   if(r.allocations().size()==1)f.setPartyId(partyId);
   PaymentRecordEntity pr=new PaymentRecordEntity();pr.setDocumentType(expected);pr.setDocumentId(a.targetId());pr.setPaymentDate(t.getTransactionDate());pr.setAmount(amount);pr.setPaymentMode("Bank Statement");pr.setReferenceNo(t.getOriginalReference());pr.setNotes("Reconciled from bank statement transaction #"+t.getId());pr.setCreatedBy(org.example.server.security.CurrentUser.require().username());pr.setReceivedFrom(expected.equals("SALE")?"Bank Statement":null);pr.setPaymentType("BANK_RECONCILIATION");pr=payments.save(pr);
   BankReconciliationAllocationEntity al=new BankReconciliationAllocationEntity();al.setStatementTransactionId(t.getId());al.setTargetType(expected);al.setTargetId(a.targetId());al.setAllocatedAmount(amount);al.setPaymentRecordId(pr.getId());al.setFinanceEntryId(f.getId());al.setCreatedBy(org.example.server.security.CurrentUser.require().username());allocations.save(al);audit(t,"MATCHED","Allocated "+fmt(amount)+" to "+docNo,t.getStatus(),"MATCHED",r.user());
  }
  finance.save(f);String old=t.getStatus();t.setStatus("MATCHED");t.setSuggestedConfidence(null);txs.save(t);if(!"MATCHED".equals(old))audit(t,"STATUS_CHANGED","Match confirmed",old,"MATCHED",r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Bank transaction matched successfully.","MATCHED",f.getId());
 }

 @Transactional public BankReconciliationDtos.OperationResult expense(Long id,BankReconciliationDtos.ExpenseRequest r){var t=reqTx(id);ensureProcessable(t);if(n(t.getDebitAmount())<=0)throw new IllegalArgumentException("Only debit transactions can be moved to Expense Entry.");FinanceRegisterEntity f=new FinanceRegisterEntity();f.setVoucherNo("BSE-"+id);f.setVoucherType("EXPENSE");f.setVoucherDate(t.getTransactionDate());f.setCategory(blank(r.category())?"Other":r.category());f.setReferenceNo(t.getOriginalReference());f.setAmount(t.getDebitAmount());f.setPaymentMode(blank(r.paymentMode())?"Bank":r.paymentMode());f.setNotes(blank(r.notes())?t.getOriginalDescription():r.notes());f.setAccountName(r.accountName());f.setBillPath(r.billPath());f.setReconciled(1);f.setCreatedAt(LocalDateTime.now().toString());f=finance.save(f);String old=t.getStatus();t.setStatus("EXPENSE");txs.save(t);BankReconciliationAllocationEntity al=new BankReconciliationAllocationEntity();al.setStatementTransactionId(t.getId());al.setTargetType("EXPENSE");al.setTargetId(f.getId());al.setAllocatedAmount(t.getDebitAmount());al.setFinanceEntryId(f.getId());al.setCreatedBy(org.example.server.security.CurrentUser.require().username());allocations.save(al);audit(t,"EXPENSE_CREATED","Expense voucher "+f.getVoucherNo()+" created",old,"EXPENSE",r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Expense created from bank statement.","EXPENSE",f.getId());}
 @Transactional public BankReconciliationDtos.OperationResult updateNote(Long id,BankReconciliationDtos.NoteRequest r){var t=reqTx(id);t.setNotes(r==null?null:r.note());txs.save(t);audit(t,"NOTE_UPDATED",r==null?"":r.note(),t.getStatus(),t.getStatus(),r==null?null:r.user());return new BankReconciliationDtos.OperationResult(true,"Transaction note updated.",t.getStatus(),null);}
 @Transactional public BankReconciliationDtos.OperationResult ignore(Long id,BankReconciliationDtos.IgnoreRequest r){var t=reqTx(id);ensureProcessable(t);String old=t.getStatus();t.setStatus("IGNORED");t.setNotes(r==null?null:r.note());txs.save(t);audit(t,"IGNORED",r==null?"Marked intentionally ignored":r.note(),old,"IGNORED",r==null?null:r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Transaction marked as ignored.","IGNORED",null);}
 @Transactional public BankReconciliationDtos.OperationResult review(Long id,BankReconciliationDtos.NoteRequest r){var t=reqTx(id);ensureProcessable(t);String old=t.getStatus();t.setStatus("REVIEW");t.setNotes(r==null?"Reviewed by user":r.note());txs.save(t);audit(t,"MARKED_REVIEW","Transaction marked for review",old,"REVIEW",r==null?null:r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Transaction marked for review.","REVIEW",null);}

 @Transactional public BankReconciliationDtos.OperationResult reverse(Long id,String user){var t=reqTx(id);var active=allocations.findByStatementTransactionIdAndReversedAtIsNull(id);if(active.isEmpty()&&"IGNORED".equals(up(t.getStatus()))){String old=t.getStatus();t.setStatus("UNMATCHED");txs.save(t);audit(t,"REOPENED","Ignored transaction returned to reconciliation",old,"UNMATCHED",user);refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Transaction returned to UNMATCHED.","UNMATCHED",null);}if(active.isEmpty())throw new IllegalStateException("No active reconciliation exists for this transaction.");Set<Integer> financeIds=new HashSet<>();for(var a:active){if(a.getPaymentRecordId()!=null){if("SALE".equals(up(a.getTargetType()))){sales.findByIdForUpdate(a.getTargetId()).ifPresent(s->{double paid=Math.max(0,n(s.getPaidAmount())-n(a.getAllocatedAmount()));s.setPaidAmount(paid);s.setPaymentStatus(paid<=.009?"PENDING":paid+.01>=n(s.getTotalAmount())?"PAID":"PARTIAL");sales.save(s);});}else if("PURCHASE".equals(up(a.getTargetType()))){purchases.findByIdForUpdate(a.getTargetId()).ifPresent(p->{double paid=Math.max(0,n(p.getPaidAmount())-n(a.getAllocatedAmount()));p.setPaidAmount(paid);p.setPaymentStatus(paid<=.009?"PENDING":paid+.01>=n(p.getTotalAmount())?"PAID":"PARTIAL");purchases.save(p);});}payments.deleteById(a.getPaymentRecordId());}if(a.getFinanceEntryId()!=null)financeIds.add(a.getFinanceEntryId());a.setReversedAt(LocalDateTime.now().toString());allocations.save(a);}for(Integer fid:financeIds)if(finance.existsById(fid))finance.deleteById(fid);String old=t.getStatus();t.setStatus("UNMATCHED");t.setSuggestedMatchId(null);t.setSuggestedMatchType(null);t.setSuggestedConfidence(null);txs.save(t);audit(t,"REVERSED","Reconciliation reversed",old,"UNMATCHED",user);refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Reconciliation reversed.","UNMATCHED",null);}
 public List<BankReconciliationDtos.AuditDto> audit(Long id){return audits.findByStatementTransactionIdOrderByIdDesc(id).stream().map(a->new BankReconciliationDtos.AuditDto(a.getId(),a.getEventType(),a.getEventDetail(),a.getPreviousStatus(),a.getNewStatus(),a.getPerformedBy(),a.getCreatedAt())).toList();}

 private void applySuggestion(BankStatementTransactionEntity t){String desc=up(t.getOriginalDescription());String holder=compact(t.getImportBatch().getAccountHolder());if(desc.contains("REV-")||desc.startsWith("REV")){t.setStatus("REVIEW");t.setNotes("Possible bank reversal; review before posting.");return;}if(!holder.isBlank()&&compact(desc).contains(holder)){t.setStatus("REVIEW");t.setNotes("Possible transfer involving the statement account holder; verify before posting.");return;}if(desc.contains("CHRG")||desc.contains("CHARGE")){t.setStatus("REVIEW");t.setNotes("Likely bank charge; review and use Move to Expense if appropriate.");return;}var cs=candidatesFor(t);if(!cs.isEmpty()&&cs.get(0).confidence()>=75){var c=cs.get(0);t.setStatus("SUGGESTED");t.setSuggestedMatchType(c.type());t.setSuggestedMatchId(c.id());t.setSuggestedConfidence(c.confidence());}else t.setStatus("UNMATCHED");txs.save(t);}
 private List<BankReconciliationDtos.CandidateDto> candidatesFor(BankStatementTransactionEntity t){List<BankReconciliationDtos.CandidateDto> out=new ArrayList<>();if(n(t.getCreditAmount())>0){for(var s:sales.findAllByOrderByInvoiceDateDescIdDesc()){double o=Math.max(0,n(s.getTotalAmount())-n(s.getPaidAmount()));if(o>.009&&!cancelled(s.getDocumentStatus()))out.add(candidate(t,"SALE",s.getId(),s.getInvoiceNo(),s.getCustomer()==null?"":s.getCustomer().getName(),s.getInvoiceDate(),n(s.getTotalAmount()),n(s.getPaidAmount()),o));}}else{for(var p:purchases.findAllByOrderByInvoiceDateDescIdDesc()){double o=Math.max(0,n(p.getTotalAmount())-n(p.getPaidAmount()));if(o>.009&&!cancelled(p.getDocumentStatus()))out.add(candidate(t,"PURCHASE",p.getId(),p.getInvoiceNo(),p.getSupplier()==null?"":p.getSupplier().getName(),p.getInvoiceDate(),n(p.getTotalAmount()),n(p.getPaidAmount()),o));}}out.sort(Comparator.comparingDouble(BankReconciliationDtos.CandidateDto::confidence).reversed());return out;}
 private BankReconciliationDtos.CandidateDto candidate(BankStatementTransactionEntity t,String type,Integer id,String no,String party,String docDate,double total,double paid,double outstanding){double score=0,amount=bankAmount(t);if(Math.abs(outstanding-amount)<=.01)score+=50;String hay=up(safe(t.getOriginalDescription())+" "+safe(t.getOriginalReference()));if(!blank(no)&&compact(hay).contains(compact(no)))score+=20;String normHay=hay.replaceAll("[^A-Z0-9 ]"," ");if(!blank(party)){String[] tokens=up(party).replaceAll("[^A-Z0-9 ]"," ").split("\\s+");long useful=Arrays.stream(tokens).filter(x->x.length()>=4&&normHay.contains(x)).count();if(useful>0)score+=25;}LocalDate td=date(t.getTransactionDate()),dd=date(docDate);if(td!=null&&dd!=null&&Math.abs(ChronoUnit.DAYS.between(dd,td))<=7)score+=5;return new BankReconciliationDtos.CandidateDto(type,id,no,party,docDate,total,paid,outstanding,Math.min(100,score));}
 private void refreshBatch(Long id){var b=imports.findById(id).orElseThrow();var m=metrics(id);b.setReconciledCount(m.reconciled());b.setReconciliationPercent(m.reconciledPercent());b.setStatus(m.batchStatus());imports.save(b);}
 private BankReconciliationDtos.BatchDto batch(BankStatementImportEntity b){return new BankReconciliationDtos.BatchDto(b.getId(),b.getBankName(),b.getBankAccount(),b.getAccountHolder(),b.getStatementFrom(),b.getStatementTo(),b.getCurrency(),nv(b.getTransactionCount()),n(b.getTotalDebit()),n(b.getTotalCredit()),nv(b.getReconciledCount()),n(b.getReconciliationPercent()),b.getStatus(),b.getSourceFileName(),b.getImportedAt());}
 private BankReconciliationDtos.TransactionDto transaction(BankStatementTransactionEntity t){
  String link=""; Integer financeId=null,targetId=null; String targetType=null,docNo=null;
  var a=allocations.findByStatementTransactionIdAndReversedAtIsNull(t.getId());
  if(!a.isEmpty()){
   var first=a.get(0); financeId=first.getFinanceEntryId(); targetType=up(first.getTargetType()); targetId=first.getTargetId();
   if("EXPENSE".equals(targetType)){link="View Expense"; docNo="Expense #"+targetId;}
   else if(a.size()>1){link=a.size()+" linked invoices"; docNo=link;}
   else if("SALE".equals(targetType)){docNo=sales.findById(targetId).map(SalesHeaderEntity::getInvoiceNo).orElse("Sale #"+targetId);link=docNo;}
   else if("PURCHASE".equals(targetType)){docNo=purchases.findById(targetId).map(PurchaseHeaderEntity::getInvoiceNo).orElse("Purchase #"+targetId);link=docNo;}
  }else if(t.getSuggestedMatchId()!=null){targetType=up(t.getSuggestedMatchType());targetId=t.getSuggestedMatchId();
   if("SALE".equals(targetType))docNo=sales.findById(targetId).map(SalesHeaderEntity::getInvoiceNo).orElse("Sale #"+targetId);
   else if("PURCHASE".equals(targetType))docNo=purchases.findById(targetId).map(PurchaseHeaderEntity::getInvoiceNo).orElse("Purchase #"+targetId);
   link="Suggested: "+(docNo==null?targetType+" #"+targetId:docNo);
  }
  return new BankReconciliationDtos.TransactionDto(t.getId(),t.getImportBatch().getId(),t.getSourceRowNumber(),t.getTransactionTimestamp(),t.getTransactionDate(),t.getValueDate(),t.getOriginalDescription(),t.getOriginalReference(),n(t.getDebitAmount()),n(t.getCreditAmount()),n(t.getBalance()),t.getStatus(),t.getSuggestedMatchType(),t.getSuggestedMatchId(),t.getSuggestedConfidence(),link,financeId,targetType,targetId,docNo);
 }
 private void audit(BankStatementTransactionEntity t,String event,String detail,String old,String next,String user){BankReconciliationAuditEntity a=new BankReconciliationAuditEntity();a.setStatementTransactionId(t.getId());a.setEventType(event);a.setEventDetail(detail);a.setPreviousStatus(old);a.setNewStatus(next);a.setPerformedBy(org.example.server.security.CurrentUser.require().username());audits.save(a);}
 private BankStatementTransactionEntity reqTx(Long id){return txs.findById(id).orElseThrow(()->new IllegalArgumentException("Bank statement transaction not found."));} private BankStatementTransactionEntity reqTxForUpdate(Long id){return txs.findByIdForUpdate(id).orElseThrow(()->new IllegalArgumentException("Bank statement transaction not found."));} private void ensureProcessable(BankStatementTransactionEntity t){if(RESOLVED.contains(up(t.getStatus())))throw new IllegalStateException("This bank transaction is already resolved. Use Unmatch / Reverse first.");}
 private static double bankAmount(BankStatementTransactionEntity t){return n(t.getCreditAmount())>0?n(t.getCreditAmount()):n(t.getDebitAmount());} private static boolean cancelled(String s){String x=up(s);return x.equals("CANCELLED")||x.equals("DELETED");} private static int nv(Integer v){return v==null?0:v;} private static double n(Number v){return v==null?0:v.doubleValue();} private static String up(String s){return s==null?"":s.trim().toUpperCase(Locale.ROOT);} private static boolean blank(String s){return s==null||s.isBlank();} private static String safe(String s){return s==null?"":s;} private static String compact(String s){return up(s).replaceAll("[^A-Z0-9]","");} private static String fmt(double v){return String.format(Locale.ENGLISH,"%,.2f",v);} private static LocalDate date(String s){try{return s==null?null:LocalDate.parse(s.length()>=10?s.substring(0,10):s);}catch(Exception e){return null;}}
}
