package org.example.api.admin;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.*;import org.example.config.ConfigManager;import java.io.*;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.time.Duration;import java.util.*;
public final class AdminApiClient {
 private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build(); private final ObjectMapper json=new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES,false); private final String base;
 public AdminApiClient(){String b=ConfigManager.getDataApiBaseUrl();while(b.endsWith("/"))b=b.substring(0,b.length()-1);base=b;}
 public List<UserDto> users(){return get("/api/admin/users",new TypeReference<List<UserDto>>(){});} public UserDto user(int id){return get("/api/admin/users/"+id,UserDto.class);} public UserDto saveUser(UserSaveRequest d){return d.id()==null?post("/api/admin/users",d,UserDto.class):put("/api/admin/users/"+d.id(),d,UserDto.class);} public void deleteUser(int id){delete("/api/admin/users/"+id);} public void resetPassword(int id,String p){post("/api/admin/users/"+id+"/password",new PasswordRequest(p),Ok.class);} public void setLocked(int id,boolean b){post("/api/admin/users/"+id+"/lock",new LockRequest(b),Ok.class);}
 public List<RoleDto> roles(){return get("/api/admin/roles",new TypeReference<List<RoleDto>>(){});} public RoleDto saveRole(RoleSaveRequest d){return d.id()==null?post("/api/admin/roles",d,RoleDto.class):put("/api/admin/roles/"+d.id(),d,RoleDto.class);} public void deleteRole(int id){delete("/api/admin/roles/"+id);}
 public List<PermissionDto> permissions(String role){return get("/api/admin/permissions?role="+enc(role),new TypeReference<List<PermissionDto>>(){});} public void savePermissions(String role,List<PermissionSave> p){put("/api/admin/permissions",new PermissionSaveRequest(role,p),Ok.class);} public void audit(int userId,String action,String detail){post("/api/admin/audit",new AuditRequest(userId,action,detail),Ok.class);}
 private <T>T get(String p,Class<T>c){return req("GET",p,null,c,null);}private <T>T get(String p,TypeReference<T>t){return req("GET",p,null,null,t);}private <T>T post(String p,Object b,Class<T>c){return req("POST",p,b,c,null);}private <T>T put(String p,Object b,Class<T>c){return req("PUT",p,b,c,null);}private void delete(String p){req("DELETE",p,null,Ok.class,null);} private String enc(String v){return URLEncoder.encode(v==null?"":v,StandardCharsets.UTF_8);}
 private <T>T req(String m,String p,Object body,Class<T>c,TypeReference<T>t){try{HttpRequest.Builder b=HttpRequest.newBuilder(URI.create(base+p)).timeout(Duration.ofSeconds(20)).header("Accept","application/json");org.example.api.ApiSession.authorize(b);if(body!=null)b.header("Content-Type","application/json").method(m,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));else b.method(m,HttpRequest.BodyPublishers.noBody());var r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()<200||r.statusCode()>=300)throw new IllegalStateException("Admin API error ("+r.statusCode()+"): "+r.body());return t!=null?json.readValue(r.body(),t):json.readValue(r.body(),c);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException(e);}catch(IOException e){throw new IllegalStateException("Cannot reach admin API at "+base,e);}}
 public record UserDto(int id,String username,String fullName,String email,String role,String department,String accessLevel,String branch,boolean active,boolean locked,boolean mfaEnabled,String lastLogin){} public record UserSaveRequest(Integer id,String username,String password,String fullName,String email,String role,String department,String accessLevel,String branch,boolean active,boolean locked,boolean mfaEnabled){} public record RoleDto(int id,String name,String description,boolean active,long userCount){} public record RoleSaveRequest(Integer id,String name,String description,boolean active){} public record PermissionDto(long id,String module,String action,String description,boolean allowed){} public record PermissionSave(long id,boolean allowed){} public record PermissionSaveRequest(String role,List<PermissionSave> permissions){} public record PasswordRequest(String password){} public record LockRequest(boolean locked){} public record AuditRequest(int userId,String action,String detail){} public record Ok(boolean success,String message){}
}
