package org.example.server.returns;
import org.example.server.persistence.JpaNativeRepository;import org.example.server.security.CurrentUser;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class ReturnService{
 private final JpaNativeRepository jdbc;public ReturnService(JpaNativeRepository jdbc){this.jdbc=jdbc;}
 @Transactional(readOnly=true) public List<ReturnDtos.Summary> summaries(String type){return jdbc.query("SELECT r.return_no,MAX(r.return_date),MAX(COALESCE(r.invoice_no,'')),MAX(COALESCE(p.name,'')),SUM(r.amount),SUM(COALESCE(r.refund_amount,0)),MAX(COALESCE(r.reason,'')),CASE WHEN MAX(r.status)='CANCELLED' THEN 'CANCELLED' WHEN SUM(COALESCE(r.refund_amount,0))>=SUM(r.amount) AND SUM(r.amount)>0 THEN 'COMPLETED' WHEN SUM(COALESCE(r.refund_amount,0))>0 THEN 'PARTIAL' ELSE MAX(COALESCE(r.status,'PENDING')) END,CASE WHEN SUM(COALESCE(r.refund_amount,0))>=SUM(r.amount) AND SUM(r.amount)>0 THEN 'REFUNDED' WHEN SUM(COALESCE(r.refund_amount,0))>0 THEN 'PARTIAL' ELSE 'PENDING' END,MAX(COALESCE(p.email,'')) FROM return_register r LEFT JOIN party_master p ON p.id=r.party_id WHERE r.return_type=? GROUP BY r.return_no ORDER BY MAX(CAST(r.return_date AS DATE)) DESC,MAX(r.id) DESC",(r,i)->new ReturnDtos.Summary(r.getString(1),String.valueOf(r.getObject(2)),r.getString(3),r.getString(4),r.getDouble(5),r.getDouble(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10)),type);}
 @Transactional(readOnly=true) public Map<String,Double> returned(String type,String invoice){Map<String,Double> out=new HashMap<>();jdbc.query("SELECT item_code,COALESCE(SUM(quantity),0) FROM return_register WHERE return_type=? AND invoice_no=? AND COALESCE(status,'PENDING')<>'CANCELLED' GROUP BY item_code",r->{out.put(r.getString(1),r.getDouble(2));},type,invoice);return out;}
 @Transactional public ReturnDtos.Created create(ReturnDtos.CreateRequest d){if(d==null||d.lines()==null||d.lines().isEmpty())throw new IllegalArgumentException("Select at least one item to return.");String type=d.type()==null?"":d.type().trim().toUpperCase(Locale.ROOT);if(!Set.of("SALES RETURN","PURCHASE RETURN").contains(type))throw new IllegalArgumentException("Return type must be SALES RETURN or PURCHASE RETURN.");if(d.invoiceNo()==null||d.invoiceNo().isBlank())throw new IllegalArgumentException("Invoice number is required.");String prefix="SALES RETURN".equals(type)?"SAL-RET-":"PUR-RET-",no=prefix+System.currentTimeMillis();boolean sales="SALES RETURN".equals(type);for(var l:d.lines()){if(l.code()==null||l.code().isBlank())throw new IllegalArgumentException("Return item code is required.");if(!Double.isFinite(l.quantity())||l.quantity()<=0)throw new IllegalArgumentException("Return quantity must be a finite number greater than zero.");if(!Double.isFinite(l.amount())||l.amount()<0)throw new IllegalArgumentException("Return amount must be a finite non-negative number.");double invoiced=invoicedQuantity(sales,d.invoiceNo(),l.code()),already=returnedQuantity(type,d.invoiceNo(),l.code());if(invoiced<=0)throw new IllegalArgumentException("Item "+l.code()+" is not present on invoice "+d.invoiceNo()+".");if(l.quantity()>invoiced-already+.0001)throw new IllegalArgumentException("Return quantity exceeds the remaining invoiced quantity for "+l.code()+".");if(!sales){Integer changed=jdbc.update("UPDATE item_master SET opening_stock=COALESCE(opening_stock,0)-? WHERE item_code=? AND COALESCE(opening_stock,0)>=?",l.quantity(),l.code(),l.quantity());if(changed==0)throw new IllegalStateException("Available stock changed while creating the return. Refresh and try again.");}else if(jdbc.update("UPDATE item_master SET opening_stock=COALESCE(opening_stock,0)+? WHERE item_code=?",l.quantity(),l.code())!=1)throw new IllegalArgumentException("Item not found: "+l.code());jdbc.update("INSERT INTO return_register(return_no,return_type,return_date,invoice_no,party_id,item_code,quantity,amount,reason,status,refund_amount,refund_status) VALUES(?,?,?,?,?,?,?,?,?,'PENDING',0,'PENDING')",no,type,d.returnDate(),d.invoiceNo(),d.partyId(),l.code(),l.quantity(),l.amount(),l.reason());}return new ReturnDtos.Created(no);}
 @Transactional(readOnly=true) public ReturnDtos.Details details(String no){List<ReturnDtos.Line> lines=jdbc.query("SELECT COALESCE(im.description,r.item_code),r.item_code,r.quantity,COALESCE(im.unit,'Nos'),COALESCE(sl.rate,pl.rate,0),COALESCE(sl.gst_percent,pl.gst_percent,0),r.amount,COALESCE(r.reason,'') FROM return_register r LEFT JOIN item_master im ON im.item_code=r.item_code LEFT JOIN sales_header sh ON sh.invoice_no=r.invoice_no AND r.return_type='SALES RETURN' LEFT JOIN sales_line sl ON sl.sales_id=sh.id AND sl.item_code=r.item_code LEFT JOIN purchase_header ph ON ph.invoice_no=r.invoice_no AND r.return_type='PURCHASE RETURN' LEFT JOIN purchase_line pl ON pl.purchase_id=ph.id AND pl.item_code=r.item_code WHERE r.return_no=? ORDER BY r.id",(r,i)->new ReturnDtos.Line(r.getString(1),r.getString(2),r.getDouble(3),r.getString(4),r.getDouble(5),r.getDouble(6),r.getDouble(7),r.getString(8)),no);if(lines.isEmpty())throw new IllegalArgumentException("Return not found: "+no);Map<String,Object> h=jdbc.queryForMap("SELECT MAX(r.return_no) no,MAX(r.return_date) date,MAX(COALESCE(r.invoice_no,'')) invoice,MAX(COALESCE(pm.name,'')) party,MAX(r.return_type) type,MAX(COALESCE(ph.payment_terms,'')) terms,MAX(COALESCE(ph.currency,'INR - Indian Rupee')) currency,MAX(COALESCE(r.created_at::text,'')) created,MAX(COALESCE(r.updated_at::text,'')) updated,MAX(COALESCE(r.attachment_path,'')) attachment,MAX(COALESCE(r.notes,'')) notes,SUM(r.amount) total,SUM(COALESCE(r.refund_amount,0)) refund,MAX(COALESCE(r.status,'PENDING')) raw_status FROM return_register r LEFT JOIN party_master pm ON pm.id=r.party_id LEFT JOIN purchase_header ph ON ph.invoice_no=r.invoice_no WHERE r.return_no=?",no);double total=n(h.get("total")),refund=n(h.get("refund"));String raw=Objects.toString(h.get("raw_status"),"PENDING"),refundStatus=refund<=.0001?"PENDING":refund+.0001>=total?"REFUNDED":"PARTIAL",status="CANCELLED".equalsIgnoreCase(raw)?"CANCELLED":"REFUNDED".equals(refundStatus)?"COMPLETED":"PARTIAL".equals(refundStatus)?"PARTIAL":raw;return new ReturnDtos.Details(no,Objects.toString(h.get("date"),""),Objects.toString(h.get("invoice"),""),Objects.toString(h.get("party"),""),Objects.toString(h.get("type"),""),Objects.toString(h.get("terms"),""),Objects.toString(h.get("currency"),"INR - Indian Rupee"),Objects.toString(h.get("created"),""),Objects.toString(h.get("updated"),""),Objects.toString(h.get("attachment"),""),Objects.toString(h.get("notes"),""),total,refund,status,refundStatus,lines);}
 @Transactional public void update(String no,String field,String value){if(!Set.of("reason","notes","attachment_path","status").contains(field))throw new IllegalArgumentException("Unsupported return field");jdbc.update("UPDATE return_register SET "+field+"=?,updated_at=CURRENT_TIMESTAMP WHERE return_no=?",value,no);}
 @Transactional public void refund(String no,double amount){double total=total(no);if(!Double.isFinite(amount)||amount<=0||amount>total+.0001)throw new IllegalArgumentException("Refund amount must be finite, greater than zero and no more than the return total.");String rs=amount+.0001>=total?"REFUNDED":"PARTIAL",status="REFUNDED".equals(rs)?"COMPLETED":"PARTIAL";jdbc.update("UPDATE return_register SET refund_amount=0,refund_status=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE return_no=?",rs,status,no);jdbc.update("UPDATE return_register SET refund_amount=? WHERE id=(SELECT MIN(id) FROM return_register WHERE return_no=?)",amount,no);}
 @Transactional public void delete(String no,boolean ignoredSalesFlag){requireAccess(no);assertUnrefunded(no);reverse(no,isSalesReturn(no));jdbc.update("DELETE FROM return_register WHERE return_no=?",no);}
 @Transactional public void cancel(String no,boolean ignoredSalesFlag){requireAccess(no);assertUnrefunded(no);Long c=jdbc.queryForObject("SELECT COUNT(*) FROM return_register WHERE return_no=? AND status='CANCELLED'",Long.class,no);if(c!=null&&c>0)throw new IllegalStateException("This return is already cancelled.");reverse(no,isSalesReturn(no));jdbc.update("UPDATE return_register SET status='CANCELLED',updated_at=CURRENT_TIMESTAMP WHERE return_no=?",no);}
 private void assertUnrefunded(String no){Map<String,Object>m=jdbc.queryForMap("SELECT COALESCE(SUM(refund_amount),0) refund,MAX(COALESCE(refund_status,'PENDING')) state,COUNT(*) cnt FROM return_register WHERE return_no=?",no);if(((Number)m.get("cnt")).longValue()==0)throw new IllegalStateException("Return "+no+" was not found.");if(n(m.get("refund"))>.0001||!"PENDING".equalsIgnoreCase(Objects.toString(m.get("state"),"PENDING")))throw new IllegalStateException("A refunded or partially refunded return cannot be deleted or cancelled because it would corrupt accounting history.");}
 private double total(String no){Double d=jdbc.queryForObject("SELECT COALESCE(SUM(amount),0) FROM return_register WHERE return_no=?",Double.class,no);if(d==null||d<=0)throw new IllegalStateException("Return "+no+" was not found.");return d;}
 private void reverse(String no,boolean sales){for(Map<String,Object> r:jdbc.queryForList("SELECT item_code,quantity FROM return_register WHERE return_no=?",no)){double q=n(r.get("quantity"));String code=Objects.toString(r.get("item_code"),"");if(sales){if(jdbc.update("UPDATE item_master SET opening_stock=COALESCE(opening_stock,0)-? WHERE item_code=? AND COALESCE(opening_stock,0)>=?",q,code,q)!=1)throw new IllegalStateException("Stock for "+code+" is no longer sufficient to reverse this return.");}else if(jdbc.update("UPDATE item_master SET opening_stock=COALESCE(opening_stock,0)+? WHERE item_code=?",q,code)!=1)throw new IllegalStateException("Item not found: "+code);}}
 private double invoicedQuantity(boolean sales,String invoice,String code){String sql=sales?"SELECT COALESCE(SUM(l.quantity),0) FROM sales_line l JOIN sales_header h ON h.id=l.sales_id WHERE h.invoice_no=? AND l.item_code=?":"SELECT COALESCE(SUM(l.quantity),0) FROM purchase_line l JOIN purchase_header h ON h.id=l.purchase_id WHERE h.invoice_no=? AND l.item_code=?";Double value=jdbc.queryForObject(sql,Double.class,invoice,code);return value==null?0:value;}
 private double returnedQuantity(String type,String invoice,String code){Double value=jdbc.queryForObject("SELECT COALESCE(SUM(quantity),0) FROM return_register WHERE return_type=? AND invoice_no=? AND item_code=? AND COALESCE(status,'PENDING')<>'CANCELLED'",Double.class,type,invoice,code);return value==null?0:value;}
 public void requireTypeAccess(String type){if(CurrentUser.isSales()&&!"SALES RETURN".equalsIgnoreCase(type==null?"":type.trim()))throw new SecurityException("Purchase returns require Manager or Admin access");}
 public void requireAccess(String no){if(CurrentUser.isSales()&&!isSalesReturn(no))throw new SecurityException("Purchase returns require Manager or Admin access");}
 private boolean isSalesReturn(String no){String type=jdbc.queryForObject("SELECT MAX(return_type) FROM return_register WHERE return_no=?",String.class,no);if(type==null||type.isBlank())throw new IllegalArgumentException("Return not found: "+no);return "SALES RETURN".equalsIgnoreCase(type);}
 private double n(Object x){return x instanceof Number v?v.doubleValue():0;}
}
