package org.example.api.bank;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.example.config.ConfigManager;

import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.time.Duration;import java.util.*;

public final class BankStatementApiClient {
 private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(6)).build();
 private final ObjectMapper json=new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES,false);
 private final String base;
 public BankStatementApiClient(){String b=ConfigManager.getDataApiBaseUrl();while(b.endsWith("/"))b=b.substring(0,b.length()-1);base=b;}
 public ImportResult importStatement(ImportRequest r){return post("/api/bank-statements/imports",r,ImportResult.class);} public List<BatchDto>batches(){return get("/api/bank-statements/imports",new TypeReference<List<BatchDto>>(){});} public SourceDto source(long id){return get("/api/bank-statements/imports/"+id+"/source",SourceDto.class);} public List<TransactionDto>transactions(long id){return get("/api/bank-statements/imports/"+id+"/transactions",new TypeReference<List<TransactionDto>>(){});} public Metrics metrics(long id){return get("/api/bank-statements/imports/"+id+"/metrics",Metrics.class);} public List<CandidateDto>suggest(long id){return post("/api/bank-statements/transactions/"+id+"/suggest",null,new TypeReference<List<CandidateDto>>(){});} public List<CandidateDto>candidates(long id){return get("/api/bank-statements/transactions/"+id+"/candidates",new TypeReference<List<CandidateDto>>(){});} public OperationResult match(long id,MatchRequest r){return post("/api/bank-statements/transactions/"+id+"/match",r,OperationResult.class);} public OperationResult expense(long id,ExpenseRequest r){return post("/api/bank-statements/transactions/"+id+"/expense",r,OperationResult.class);} public OperationResult updateNote(long id,NoteRequest r){return post("/api/bank-statements/transactions/"+id+"/note",r,OperationResult.class);} public OperationResult ignore(long id,IgnoreRequest r){return post("/api/bank-statements/transactions/"+id+"/ignore",r,OperationResult.class);} public OperationResult review(long id,NoteRequest r){return post("/api/bank-statements/transactions/"+id+"/review",r,OperationResult.class);} public OperationResult reverse(long id,String user){return post("/api/bank-statements/transactions/"+id+"/reverse?user="+enc(user),null,OperationResult.class);} public List<AuditDto>audit(long id){return get("/api/bank-statements/transactions/"+id+"/audit",new TypeReference<List<AuditDto>>(){});}
 private <T>T get(String p,Class<T>c){return req("GET",p,null,c,null);} private <T>T get(String p,TypeReference<T>t){return req("GET",p,null,null,t);} private <T>T post(String p,Object b,Class<T>c){return req("POST",p,b,c,null);} private <T>T post(String p,Object b,TypeReference<T>t){return req("POST",p,b,null,t);}
 private <T>T req(String method,String path,Object body,Class<T>c,TypeReference<T>t){try{HttpRequest.Builder b=HttpRequest.newBuilder(URI.create(base+path)).timeout(Duration.ofSeconds(30)).header("Accept","application/json");org.example.api.ApiSession.authorize(b);if(body!=null)b.header("Content-Type","application/json");String payload=body==null?"":json.writeValueAsString(body);b.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(payload,StandardCharsets.UTF_8));HttpResponse<String>r=http.send(b.build(),HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if(r.statusCode()/100!=2)throw new IllegalStateException("Bank Statement API error ("+r.statusCode()+"): "+r.body());if(c!=null)return json.readValue(r.body(),c);return json.readValue(r.body(),t);}catch(Exception e){if(e instanceof RuntimeException re)throw re;throw new IllegalStateException("Cannot reach Bank Statement API at "+base+": "+e.getMessage(),e);}}
 private static String enc(String s){return URLEncoder.encode(s==null?"":s,StandardCharsets.UTF_8);}
 public record ImportRow(Integer sourceRowNumber,String transactionTimestamp,String transactionDate,String valueDate,String description,String reference,double debit,double credit,double balance,String transactionFingerprint){}
 public record ImportRequest(String bankName,String bankAccount,String accountHolder,String statementFrom,String statementTo,String currency,Double openingBalance,Double closingBalance,String sourceFingerprint,String sourceFileName,String sourceCsv,String importedBy,List<ImportRow> rows){}
 public record ImportResult(BatchDto batch,int importedRows,int duplicateRows){}
 public record BatchDto(Long id,String bankName,String bankAccount,String accountHolder,String statementFrom,String statementTo,String currency,int transactionCount,double totalDebit,double totalCredit,int reconciledCount,double reconciliationPercent,String status,String sourceFileName,String importedAt){@Override public String toString(){return bankName+" • "+statementFrom+" to "+statementTo+" • "+transactionCount+" rows";}}
 public record SourceDto(String fileName,String fingerprint,String csvContent){} public record TransactionDto(Long id,Long importId,Integer sourceRowNumber,String transactionTimestamp,String transactionDate,String valueDate,String description,String reference,double debit,double credit,double balance,String status,String suggestedMatchType,Integer suggestedMatchId,Double suggestedConfidence,String matchLink,Integer financeEntryId,String linkedTargetType,Integer linkedTargetId,String linkedDocumentNo){}
 public record CandidateDto(String type,Integer id,String documentNo,String partyName,String documentDate,double totalAmount,double paidAmount,double outstanding,double confidence){@Override public String toString(){return type+" • "+documentNo+" • "+partyName+" • Outstanding "+String.format(Locale.ENGLISH,"%,.2f",outstanding)+" • "+String.format(Locale.ENGLISH,"%.0f%%",confidence);}}
 public record AllocationRequest(String targetType,Integer targetId,double amount){} public record MatchRequest(String user,List<AllocationRequest> allocations){} public record ExpenseRequest(String category,String accountName,String paymentMode,String notes,String billPath,String user){} public record IgnoreRequest(String note,String user){} public record NoteRequest(String note,String user){} public record OperationResult(boolean success,String message,String status,Integer financeEntryId){} public record AuditDto(Long id,String eventType,String detail,String previousStatus,String newStatus,String performedBy,String createdAt){} public record Metrics(int total,int unmatched,int suggested,int matched,int expenses,int ignored,int review,double totalCredits,double totalDebits,int reconciled,double reconciledPercent,String batchStatus){}
}
