#!/usr/bin/env python3
from release_version import VERSION
from pathlib import Path
import hashlib
import re
import sys
ROOT = Path(__file__).resolve().parents[1]

def text(rel):
    return (ROOT / rel).read_text(encoding='utf-8', errors='replace')

def req(cond, msg):
    if not cond:
        print(f'FAIL: {msg}', file=sys.stderr)
        raise SystemExit(1)
ops = text('server/src/main/java/org/example/server/operations/BusinessOperationsService.java')
security = text('server/src/main/java/org/example/server/security/SecurityConfig.java')
support = text('server/src/main/java/org/example/server/support/SupportService.java')
email = text('server/src/main/java/org/example/server/authority/BusinessEmailController.java')
pdf = text('server/src/main/java/org/example/server/authority/PdfStudioTemplateController.java')
insights_c = text('server/src/main/java/org/example/server/insights/InsightsController.java')
insights_s = text('server/src/main/java/org/example/server/insights/InsightsService.java')
cash_position = text('server/src/main/java/org/example/server/insights/CashPositionService.java')
master = text('server/src/main/java/org/example/server/master/MasterDataService.java')
admin = text('server/src/main/java/org/example/server/admin/AdminService.java')
quote = text('server/src/main/java/org/example/server/quotation/QuotationService.java')
recon = text('server/src/main/java/org/example/server/reconciliation/BankReconciliationService.java')
importer = text('desktop/src/main/java/org/example/service/ImportService.java')
sales_ui = text('desktop/src/main/java/org/example/controller/SalesController.java')
ref_rules = text('shared/src/main/java/org/example/shared/ReferenceFormatRules.java')
migration = text('server/src/main/resources/db/migration/V9_0_9__corrective_integrity_hardening.sql')
migration_runner = text('server/src/main/java/org/example/server/runtime/SecurityFinancialMigrationRunner.java')
purchase_header = text('server/src/main/java/org/example/server/persistence/entity/PurchaseHeaderEntity.java')
purchase_line = text('server/src/main/java/org/example/server/persistence/entity/PurchaseLineEntity.java')
purchase_recon = text('server/src/main/java/org/example/server/recon/PurchaseReconService.java')
runtime_bootstrap = text('desktop/src/main/java/org/example/api/runtime/RuntimeBootstrapper.java')
helpers = ['saleQuantityTotals', 'saleChargeSummaries', 'saleSummaryDto', 'saleDto', 'recordedPurchasePayments', 'purchaseQuantityTotals', 'purchaseChargeSummaries', 'purchaseSummaryDto', 'purchaseDto']
for name in helpers:
    req(re.search('\\bprivate\\s+[^;{}]+\\b' + re.escape(name) + '\\s*\\(', ops) is not None, f'BusinessOperationsService helper must be implemented: {name}')
req('"/api/bank-statements/**", "/api/reconciliation/**"' in security and '"BANK_EXPENSE.RECONCILE"' in security, 'bank-statement reconciliation routes must require BANK_EXPENSE.RECONCILE')
req('HttpMethod.POST, "/api/authority/email"' in security and '"COMMUNICATION.CREATE"' in security, 'business email POST route must require COMMUNICATION.CREATE')
req('CurrentUser.requirePermission("COMMUNICATION.CREATE"' in email, 'business email controller must enforce COMMUNICATION.CREATE')
req('HttpMethod.PUT, "/api/pdf-studio/templates/**"' in security and 'HttpMethod.DELETE, "/api/pdf-studio/templates/**"' in security and (security.count('hasAnyAuthority("ROLE_ADMIN", "DOCUMENT_STUDIO.EDIT", "DOCUMENT_STUDIO.MANAGE_TEMPLATES")') >= 2), 'PDF Studio PUT/DELETE routes must allow the same EDIT/MANAGE_TEMPLATES authorities used by the desktop editor')
req('private static void requireTemplateEdit()' in pdf and 'CurrentUser.hasPermission("DOCUMENT_STUDIO.EDIT")' in pdf and 'CurrentUser.hasPermission("DOCUMENT_STUDIO.MANAGE_TEMPLATES")' in pdf, 'PDF Studio controller must enforce the same EDIT/MANAGE_TEMPLATES permission contract as route security')
for permission in ['REMINDERS.VIEW', 'REMINDERS.CREATE', 'REMINDERS.EDIT', 'REMINDERS.DELETE', 'COMMUNICATION.VIEW', 'COMMUNICATION.CREATE', 'COMMUNICATION.EDIT', 'COMMUNICATION.DELETE']:
    req(permission in insights_c or permission in insights_s or permission in support, f'missing communication/reminder permission enforcement: {permission}')
req('REMINDERS.SNOOZE' in insights_s and 'REMINDERS.COMPLETE' in insights_s, 'reminder status transitions must enforce SNOOZE/COMPLETE permissions')
req('CurrentUser.requirePermission("SALES.CREATE","DuplicateSale")' in support.replace(' ', ''), 'Support duplicate Sale must require SALES.CREATE')
req('operations.duplicateSale(id)' in support, 'Support duplicate Sale must delegate to the canonical business operation')
for field in ['supplierNameSnapshot', 'supplierEmailSnapshot', 'supplierPhoneSnapshot', 'supplierGstinSnapshot', 'supplierAddressSnapshot']:
    req(field.lower() in purchase_header.lower(), f'purchase header snapshot missing: {field}')
for field in ['itemDescriptionSnapshot', 'hsnSnapshot', 'unitSnapshot', 'itemRemarksSnapshot', 'unitCostSnapshot']:
    req(field.lower() in purchase_line.lower(), f'purchase line snapshot missing: {field}')
for col in ['supplier_name_snapshot', 'supplier_email_snapshot', 'supplier_phone_snapshot', 'supplier_gstin_snapshot', 'supplier_address_snapshot', 'item_description_snapshot', 'hsn_snapshot', 'unit_snapshot', 'item_remarks_snapshot', 'unit_cost_snapshot']:
    req(col in migration, f'v9.0.9 migration missing purchase snapshot column/backfill: {col}')
req('snapshotPurchaseParty(h)' in ops and 'setItemDescriptionSnapshot' in ops and ('setUnitCostSnapshot' in ops), 'purchase save/update path must populate snapshots')
req('HttpMethod.GET, "/api/master/items/**"' in security and '"INVENTORY.VIEW"' in security, 'Item Master GET route must require INVENTORY.VIEW')
req(master.count('CurrentUser.requirePermission("INVENTORY.VIEW"') >= 2, 'Item list and search service methods must require INVENTORY.VIEW')
req('CREATE OR REPLACE FUNCTION dse_safe_date' in migration, 'safe legacy-date parser migration missing')
req('V9_0_9__corrective_integrity_hardening' in migration_runner and 'dollarQuote' in migration_runner, 'runtime migration runner must register V9_0_9 and support dollar-quoted SQL blocks')
req(ops.count('dse_safe_date(') >= 4, 'stock/operation date queries must use dse_safe_date')
req('dse_safe_date(' in quote and 'dse_safe_date(' in support, 'quotation/report queries must use dse_safe_date')
req('markWhatsappSent' in support and 'int updated=jdbc.update' in support and ('if(updated!=1)throw' in support.replace(' ', '')), 'WhatsApp status update must propagate DB errors and reject zero-row updates')
whatsapp_line = next((line for line in support.splitlines() if 'markWhatsappSent' in line), '')
req('catch' not in whatsapp_line, 'WhatsApp status update must not swallow database exceptions')
req('doc.getReferenceNo()' in importer and 'doc.getInvoiceNo()' in importer and (importer.count('addDocumentIdentity(existingDocument') >= 4), 'Purchase import must compare external reference and internal invoice identities')
req('if (sales) ImportDocumentPolicy.requireReference(referenceFormats, "REF_SALES", invoice' in importer, 'Sales import invoice format validation must remain enforced through extracted ImportDocumentPolicy')
req('requireReference(referenceFormats, sales ? "REF_SALES" : "REF_PURCHASE", invoice' not in importer, 'Purchase external reference must not be validated as internal REF_PURCHASE')
req('requireValidFormat' in ref_rules and 'Pattern.compile("X{2,}")' in ref_rules and ('if (!matcher.find())' in ref_rules) and ('if (matcher.find())' in ref_rules), 'ReferenceFormatRules must require exactly one sequence group')
req('ReferenceFormatRules.requireValidFormat(d.lookupValue())' in master, 'Master Data must reject invalid reference formats before persistence')
req('prepareDuplicate()' in sales_ui and 'txtOrderNo.clear()' in sales_ui, 'desktop duplicate Sale must clear customer Order/PO number')
dup = re.search('OperationDtos\\.SaleDto\\s+duplicateSale\\s*\\(int id\\)\\s*\\{(.*?)\\n \\}\\n @Transactional public void deleteSale', ops, re.S)
req(dup is not None and 'd.transportNote(),null,d.gstin()' in dup.group(1).replace(' ', ''), 'server duplicate Sale must not carry the original unique Order/PO number')
req(dup is not None and 'saleDto(source,true)' in dup.group(1) and ('saveSale(request)' in dup.group(1)) and ('d.discountAmount()' in dup.group(1)) and ('d.charges()' in dup.group(1)) and ('d.lines()' in dup.group(1)), 'server duplicate Sale must rebuild through canonical saveSale from complete source DTO')
req(ops.count('findByFinanceEntryIdAndReversedAtIsNull') >= 2 and 'Reconciled finance entries must be reversed from Bank Statement before editing.' in ops and ('Reconciled finance entries must be reversed from Bank Statement before deletion.' in ops), 'Finance edit/delete must block active bank allocations')
req('e.setReconciled(reconciled)' in ops, 'Finance update must preserve server-owned reconciled state')
req('FOREIGN KEY(finance_entry_id) REFERENCES finance_register(id) ON DELETE RESTRICT' in migration, 'bank allocation must have Finance Register FK integrity')
req('a.setFinanceEntryId(null)' in recon, 'reconciliation reversal must detach allocation before deleting finance entry')
req('ensureActiveAdministratorRemains' in admin and admin.count('ensureActiveAdministratorRemains') >= 3, 'user admin must enforce last-active-admin protection across destructive authority changes')
req('assignedRole' in admin and ('own role' in admin.lower() or 'your own role' in admin.lower()), 'administrator must not be able to change their own role')
req('Set.of("CUSTOMER", "SUPPLIER")' in master and master.count('Party type must be CUSTOMER or SUPPLIER') >= 2, 'party type must be restricted to CUSTOMER/SUPPLIER')
req('Party name is required' in master, 'party name must be mandatory')
req('previousName' in master and 'findByLookupTypeOrderByDisplayOrderAscLookupValueAsc(previousName)' in master and ('value.setLookupType(nextName)' in master), 'Master category upsert rename must migrate existing lookup values')
req('private List<QuotationDtos.LineDto> loadLines' in quote, 'Quotation service must provide internal line loader for authorized actions')
convert = re.search('convert\\s*\\([^)]*\\).*?\\n\\s*\\}', quote, re.S)
duplicate = re.search('duplicate\\s*\\([^)]*\\).*?\\n\\s*\\}', quote, re.S)
req('loadLines(' in quote and quote.count('loadLines(') >= 3, 'Quotation action paths must use internal loadLines')
req('BANK DEPOSIT' in cash_position and 'BANK WITHDRAWAL' in cash_position and ('deposits' in cash_position) and ('withdrawals' in cash_position) and ('cashPosition::cashPosition' in insights_s), 'Dashboard cash position must include manual bank deposit/withdrawal finance entries through canonical CashPositionService')
req('row.otherAdjustment()' not in purchase_recon and 'round2(0d)' in purchase_recon, 'Purchase Recon import signature must use the defined zero Other Adjustment rather than a nonexistent ImportRow accessor')
req('isExpectedDevelopmentServerJar(cached)' in runtime_bootstrap and 'Implementation-Version' in runtime_bootstrap and ('BuildInfo.version().equals(version)' in runtime_bootstrap or 'org.example.update.BuildInfo.version().equals(version)' in runtime_bootstrap), 'IntelliJ server cache must reject cached JARs from a different DSE ERP version')
sales_controller = text('desktop/src/main/java/org/example/controller/SalesController.java')
purchase_controller = text('desktop/src/main/java/org/example/controller/PurchaseController.java')
bank_expense_controller = text('desktop/src/main/java/org/example/controller/BankExpenseController.java')
api_runtime = text('desktop/src/main/java/org/example/api/ApiRuntime.java')
ops_client = text('desktop/src/main/java/org/example/api/operations/OperationsApiClient.java')
bank_client = text('desktop/src/main/java/org/example/api/bank/BankStatementApiClient.java')
master_client = text('desktop/src/main/java/org/example/api/master/MasterApiClient.java')
modern_dialog = text('desktop/src/main/java/org/example/util/ModernDialog.java')
permission_matrix = text('desktop/src/main/java/org/example/controller/PermissionMatrixController.java')
dashboard_controller = text('desktop/src/main/java/org/example/controller/DashboardController.java')
pdf_controller = text('desktop/src/main/java/org/example/documentstudio/controller/PdfStudioController.java')
pdf_fxml = text('desktop/src/main/resources/fxml/pages/PdfDesigner.fxml')
finance_repair = text('server/src/main/resources/db/migration/V9_0_11__finance_runtime_repair.sql')
req('if (taxType.isBlank()) taxType = "GST";' in sales_controller, 'Sales create screen must tolerate the blank GST ComboBox bootstrap window')
req('safeValue(cmbGstType.getValue(),"GST")' in purchase_controller, 'Purchase create screen must tolerate the blank GST ComboBox bootstrap window')
for required in ['account_name', 'bill_path', 'reconciled', 'row_version', 'finance_entry_id', 'rounding_adjustment', 'reversed_at', 'CREATE OR REPLACE FUNCTION dse_safe_date']:
    req(required in finance_repair, f'v9.0.12 Finance repair migration missing runtime prerequisite: {required}')
req('V9_0_11__finance_runtime_repair' in migration_runner, 'runtime migration runner must execute the v9.0.12 Finance repair before READY')
for required in ['finance_register", "account_name', 'finance_register", "bill_path', 'finance_register", "reconciled', 'bank_reconciliation_allocation", "finance_entry_id', 'bank_reconciliation_allocation", "rounding_adjustment']:
    req(required in migration_runner, f'runtime schema verification missing: {required}')
req('userMessage(String area, int status, String body)' in api_runtime and 'logHttpFailure' in api_runtime, 'API runtime must separate user-facing HTTP messages from technical logging')
for name, client in [('operations', ops_client), ('bank statement', bank_client), ('master', master_client)]:
    req('ApiRuntime.userMessage' in client and 'ApiRuntime.logHttpFailure' in client, f'{name} API client must use centralized user-facing error translation')
req('userFacingError' in modern_dialog and 'empty string' in modern_dialog.lower(), 'modern dialogs must translate raw/empty technical exception messages')
req('userMessage(e)' in bank_expense_controller and 'parseEntryDate' in bank_expense_controller, 'Bank/Expense screen must sanitize save errors and tolerate legacy dates')
req('erp.icon.skip' in permission_matrix and 'setContentDisplay(ContentDisplay.TEXT_ONLY)' in permission_matrix and (' + " of " + ' in permission_matrix), 'Permission Matrix Special column must remain readable text instead of icon-only decoration')
req('new ScrollPane(content)' in dashboard_controller and 'Screen.getScreensForRectangle' in dashboard_controller and ('setPrefViewportHeight(520)' in dashboard_controller), 'Keyboard Shortcuts dialog must be scrollable and constrained to the active screen')
req('Auto Map Fields' in pdf_fxml and 'Mapping Checklist' in pdf_fxml and 'ERP Field Search' in pdf_fxml and 'Template Readiness' in pdf_fxml and (pdf_fxml.count('<FlowPane') >= 2), 'PDF Studio must expose searchable readiness-driven mapping and wrap toolbar actions rather than ellipsize them')
req('loadPreviewData(sample, false)' in pdf_controller and 'analyzeMapping(false)' in pdf_controller, 'opening a PDF Studio template must not auto-materialize mappings')
req('new Label("IMAGE")' not in pdf_controller and 'new Label(region.kind())' not in pdf_controller, 'detected PDF image/vector hit regions must not draw permanent type labels over the source PDF')
req('showErpFields()' in pdf_controller, 'PDF Studio inspector must provide a direct path to the ERP Fields palette')
root_pom = text('pom.xml')
server_pom = text('server/pom.xml')
desktop_pom = text('desktop/pom.xml')
shared_pom = text('shared/pom.xml')
runtime = text('shared/src/main/java/org/example/shared/RuntimeContract.java')
props = text('server/src/main/resources/application.properties')
app_version = text('desktop/src/main/resources/app-version.properties')
update = text('desktop/src/main/java/org/example/update/UpdateService.java')
runtime_manifest = text('runtime/runtime-manifest.properties') if (ROOT / 'runtime/runtime-manifest.properties').exists() else ''
run_bat = text('Run DSE ERP.bat')
build_bat = text('Build Production Windows.bat')
postgres_bat = text('scripts/start-postgresql.cmd')
safe_rollback = text('desktop/src/main/resources/fxml/pages/SafeRollback.fxml')
protected = {'desktop/src/main/java/org/example/documentstudio/service/DocumentOutputService.java': '0bb413a5666585af1c67beac15e54bb45112eb8cbc3ffcb36dccf70ea0c837f0', 'desktop/src/main/java/org/example/service/InvoicePdfService.java': 'ddc9bd1120388058ae60742f343553c6c0de2634e885360deef8e31298033fa8', 'desktop/src/main/java/org/example/invoice/service/SalesTaxInvoiceService.java': '27eb0498f015a410b60aa86f71c8bced4e0ff0e45f8a7e0207b7be9a7ce74082'}
for rel, expected in protected.items():
    actual = hashlib.sha256((ROOT / rel).read_bytes()).hexdigest()
    req(actual == expected, f'locked production PDF/Sales generation file changed: {rel}')
print(f'CORRECTIVE_RUNTIME_UI_CONTRACT_OK version={VERSION}')
