package org.example.server.operations;

import org.example.server.persistence.entity.*;
import org.example.server.persistence.repository.*;
import org.springframework.stereotype.Service;
import org.example.server.persistence.JpaNativeRepository;
import org.example.server.security.CurrentUser;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.*;

@Service
public class BusinessOperationsService {
 private final SalesHeaderRepository sales; private final SalesLineRepository salesLines; private final PurchaseHeaderRepository purchases; private final PurchaseLineRepository purchaseLines; private final PartyRepository parties; private final ItemRepository items; private final LookupRepository lookups; private final MasterCategoryRepository categories; private final FinanceRegisterRepository finance; private final BankReconciliationAllocationRepository reconciliationAllocations; private final JpaNativeRepository jdbc;
 public BusinessOperationsService(SalesHeaderRepository s,SalesLineRepository sl,PurchaseHeaderRepository p,PurchaseLineRepository pl,PartyRepository pa,ItemRepository i,LookupRepository l,MasterCategoryRepository c,FinanceRegisterRepository f,BankReconciliationAllocationRepository ra,JpaNativeRepository jdbc){sales=s;salesLines=sl;purchases=p;purchaseLines=pl;parties=pa;items=i;lookups=l;categories=c;finance=f;reconciliationAllocations=ra;this.jdbc=jdbc;}

 @Transactional(readOnly=true) public List<OperationDtos.SaleDto> sales(){return sales.findAllByOrderByInvoiceDateDescIdDesc().stream().map(h->saleDto(h,false)).toList();}
 @Transactional(readOnly=true) public OperationDtos.SaleDto sale(String invoice){return saleDto(sales.findByInvoiceNo(invoice).orElseThrow(()->new IllegalArgumentException("Sale not found: "+invoice)),true);}
 @Transactional(readOnly=true) public boolean saleExists(String invoiceNo){return sales.findByInvoiceNo(invoiceNo).isPresent();}

 @Transactional public OperationDtos.SaleDto saveSale(OperationDtos.SaleDto d){SalesHeaderEntity h=new SalesHeaderEntity(); copySale(d,h); if(blank(h.getInvoiceNo())||sales.existsByInvoiceNo(h.getInvoiceNo()))h.setInvoiceNo(nextSalesInvoice()); if(blank(h.getOrderNo())||sales.existsByOrderNo(h.getOrderNo()))h.setOrderNo(nextOrderNo()); h.setCreatedAt(LocalDateTime.now().toString()); h.setEmailSent(0); h.setDocumentStatus(blank(h.getDocumentStatus())?"PENDING":h.getDocumentStatus()); h=sales.save(h); replaceSaleLines(h.getId(),d.lines(),false); return saleDto(h,true);}
 @Transactional public OperationDtos.SaleDto updateSale(OperationDtos.SaleDto d){SalesHeaderEntity h=sales.findByInvoiceNo(d.invoiceNo()).orElseThrow(()->new IllegalArgumentException("Sale not found: "+d.invoiceNo())); restoreSaleStock(h.getId()); copySale(d,h); replaceSaleLines(h.getId(),d.lines(),false); return saleDto(h,true);}
 @Transactional public void deleteSale(String invoice){SalesHeaderEntity h=sales.findByInvoiceNo(invoice).orElseThrow(()->new IllegalArgumentException("Sale not found: "+invoice)); if(!"DELETED".equalsIgnoreCase(h.getDocumentStatus()))restoreSaleStock(h.getId()); h.setDocumentStatus("DELETED");}
 @Transactional public void cancelSale(String invoice){SalesHeaderEntity h=sales.findByInvoiceNo(invoice).orElseThrow(()->new IllegalArgumentException("Sale not found: "+invoice)); if(!"CANCELLED".equalsIgnoreCase(h.getDocumentStatus())&&!"DELETED".equalsIgnoreCase(h.getDocumentStatus()))restoreSaleStock(h.getId()); h.setDocumentStatus("CANCELLED");}
 @Transactional public void markSaleEmail(int id){SalesHeaderEntity h=sales.findById(id).orElseThrow();h.setEmailSent(1);}
 @Transactional(readOnly=true) public String nextSalesInvoice(){return formattedNext("SALES_INVOICE_FORMAT","IN/DD-MM-YYYY/XXXX",sales.findAll().stream().map(SalesHeaderEntity::getInvoiceNo).filter(Objects::nonNull).toList());}
 @Transactional(readOnly=true) public String nextOrderNo(){return formattedNext("PO_DATE_FORMAT","PO/DD-MM-YYYY/XXXX",sales.findAll().stream().map(SalesHeaderEntity::getOrderNo).filter(Objects::nonNull).toList());}

 @Transactional(readOnly=true) public List<OperationDtos.PurchaseDto> purchases(){Map<Integer,Double> paid=recordedPurchasePayments();return purchases.findAllByOrderByInvoiceDateDescIdDesc().stream().map(h->purchaseDto(h,false,effectivePurchasePaid(h,paid.getOrDefault(h.getId(),0d)))).toList();}
 @Transactional(readOnly=true) public OperationDtos.PurchaseDto purchase(String invoice){PurchaseHeaderEntity h=purchases.findByInvoiceNo(invoice).orElseThrow(()->new IllegalArgumentException("Purchase not found: "+invoice));Double recorded=jdbc.queryForObject("SELECT COALESCE(SUM(amount),0) FROM payment_record WHERE UPPER(document_type)='PURCHASE' AND document_id=?",Double.class,h.getId());return purchaseDto(h,true,effectivePurchasePaid(h,n(recorded)));}
 @Transactional(readOnly=true) public boolean purchaseExists(String invoiceNo){return purchases.findByInvoiceNo(invoiceNo).isPresent();}

 @Transactional public OperationDtos.PurchaseDto savePurchase(OperationDtos.PurchaseDto d){PurchaseHeaderEntity h=new PurchaseHeaderEntity();copyPurchase(d,h);if(blank(h.getInvoiceNo())||purchases.existsByInvoiceNo(h.getInvoiceNo()))h.setInvoiceNo(nextPurchaseInvoice());h.setCreatedAt(LocalDateTime.now().toString());h=purchases.save(h);replacePurchaseLines(h.getId(),d.lines(),false);return purchaseDto(h,true);}
 @Transactional public OperationDtos.PurchaseDto updatePurchase(OperationDtos.PurchaseDto d){PurchaseHeaderEntity h=purchases.findByInvoiceNo(d.invoiceNo()).orElseThrow(()->new IllegalArgumentException("Purchase not found: "+d.invoiceNo()));restorePurchaseStock(h.getId());copyPurchase(d,h);replacePurchaseLines(h.getId(),d.lines(),false);return purchaseDto(h,true);}
 @Transactional public void deletePurchase(String invoice){PurchaseHeaderEntity h=purchases.findByInvoiceNo(invoice).orElseThrow(()->new IllegalArgumentException("Purchase not found: "+invoice));String ps=up(h.getPaymentStatus()); if(n(h.getPaidAmount())>.0001||Set.of("PAID","SETTLED","PARTIAL").contains(ps))throw new IllegalStateException("Paid, partially paid, or settled purchase documents cannot be deleted. Use the return/reversal workflow."); restorePurchaseStock(h.getId()); purchaseLines.deleteByPurchaseId(h.getId());purchases.delete(h);}
 @Transactional public void markPurchaseEmail(int id){PurchaseHeaderEntity h=purchases.findById(id).orElseThrow();h.setEmailSent(1);}
 @Transactional(readOnly=true) public String nextPurchaseInvoice(){int max=0;Pattern p=Pattern.compile("(?i)^PUR-(\\d+)$");for(var h:purchases.findAll()){Matcher m=p.matcher(Optional.ofNullable(h.getInvoiceNo()).orElse(""));if(m.matches())max=Math.max(max,Integer.parseInt(m.group(1)));}return "PUR-"+String.format(Locale.ROOT,"%05d",max+1);}

 @Transactional(readOnly=true) public List<OperationDtos.FinanceDto> finance(){return finance.findAllByOrderByVoucherDateDescIdDesc().stream().map(this::financeDto).toList();}
 @Transactional public OperationDtos.FinanceDto saveFinance(OperationDtos.FinanceDto d){FinanceRegisterEntity e=new FinanceRegisterEntity();copyFinance(d,e);if(blank(e.getVoucherNo()))e.setVoucherNo(nextVoucher());e.setCreatedAt(LocalDateTime.now().toString());return financeDto(finance.save(e));}
 @Transactional public OperationDtos.FinanceDto updateFinance(OperationDtos.FinanceDto d){FinanceRegisterEntity e=finance.findById(req(d.id())).orElseThrow(()->new IllegalArgumentException("Finance entry not found"));copyFinance(d,e);return financeDto(e);}
 @Transactional public void deleteFinance(int id){finance.deleteById(id);}
 @Transactional(readOnly=true) public String nextVoucher(){int next=finance.findTopByOrderByIdDesc().map(x->x.getId()+1).orElse(1);return "VCH-"+LocalDate.now().getYear()+"-"+String.format(Locale.ROOT,"%05d",next);}

 @Transactional(readOnly=true) public List<OperationDtos.StockHistoryDto> stockHistory(String itemCode){
   String sql="""
     SELECT CAST(adjustment_date AS DATE) AS movement_day, adjustment_type AS movement_type, quantity, reason, reference_no, created_by
     FROM stock_adjustment WHERE item_code=?
     UNION ALL
     SELECT CAST(h.invoice_date AS DATE), 'SALE', -l.quantity, 'Sales invoice', h.invoice_no, COALESCE(h.salesperson,'System')
     FROM sales_line l JOIN sales_header h ON h.id=l.sales_id WHERE l.item_code=?
     UNION ALL
     SELECT CAST(h.invoice_date AS DATE), 'PURCHASE', l.quantity, 'Purchase invoice', h.invoice_no, 'System'
     FROM purchase_line l JOIN purchase_header h ON h.id=l.purchase_id WHERE l.item_code=?
     UNION ALL
     SELECT CAST(return_date AS DATE), return_type, CASE WHEN return_type='SALE RETURN' THEN quantity ELSE -quantity END, COALESCE(reason,'Return'), return_no, 'System'
     FROM return_register WHERE item_code=?
     ORDER BY movement_day DESC
     """;
   return jdbc.query(sql,(r,i)->new OperationDtos.StockHistoryDto(String.valueOf(r.getObject(1)),r.getString(2),r.getDouble(3),r.getString(4),r.getString(5),r.getString(6)),itemCode,itemCode,itemCode,itemCode);
 }
 @Transactional public void adjustStock(OperationDtos.StockAdjustmentRequest d){
   if(d==null||blank(d.itemCode()))throw new IllegalArgumentException("Item code is required");
   ItemEntity item=items.findByItemCode(d.itemCode()).orElseThrow(()->new IllegalArgumentException("Item not found: "+d.itemCode()));
   double current=n(item.getOpeningStock()); double quantity=d.quantity(); if(quantity<0)throw new IllegalArgumentException("Quantity cannot be negative");
   String type=up(d.type()); double delta=switch(type){case "ADD"->quantity;case "REMOVE"->-quantity;case "SET"->quantity-current;default->throw new IllegalArgumentException("Invalid adjustment type");};
   if(current+delta<-.0001)throw new IllegalArgumentException("Adjustment would make stock negative");
   item.setOpeningStock(Math.max(0,current+delta));
   jdbc.update("INSERT INTO stock_adjustment(item_code,adjustment_date,adjustment_type,quantity,reason,reference_no,created_by) VALUES(?,CURRENT_DATE,?,?,?,?,?)",d.itemCode(),type,delta,d.reason(),d.referenceNo(),CurrentUser.require().username());
 }
 @Transactional(readOnly=true) public OperationDtos.FinanceMetrics financeMetrics(){double cr=0,db=0,em=0,ey=0,pendAmt=0;long bc=0,dc=0,wc=0,ec=0,pend=0;Map<String,Double> cat=new HashMap<>();YearMonth ym=YearMonth.now();int y=LocalDate.now().getYear();for(var e:finance.findAll()){String t=up(e.getVoucherType());LocalDate d=date(e.getVoucherDate());double a=n(e.getAmount());if(t.equals("BANK DEPOSIT")){cr+=a;dc++;if(d!=null&&YearMonth.from(d).equals(ym))bc++;}else if(t.equals("BANK WITHDRAWAL")){db+=a;wc++;if(d!=null&&YearMonth.from(d).equals(ym))bc++;}else if(t.equals("EXPENSE")){if(d!=null&&YearMonth.from(d).equals(ym)){em+=a;ec++;}if(d!=null&&d.getYear()==y)ey+=a;String c=blank(e.getCategory())?"Other":e.getCategory();cat.merge(c,a,Double::sum);if(n(e.getReconciled())==0){pend++;pendAmt+=a;}}}var top=cat.entrySet().stream().max(Map.Entry.comparingByValue()).orElse(null);return new OperationDtos.FinanceMetrics(cr-db,cr,db,bc,dc,wc,em,ey,ec,top==null?"No expenses":top.getKey(),top==null?0:top.getValue(),pend,pendAmt);}

 private void replaceSaleLines(int id,List<OperationDtos.LineDto> ls,boolean skipStock){salesLines.deleteBySalesId(id);if(ls==null)return;for(var d:ls){if(!skipStock)changeStock(d.itemCode(),-d.quantity(),true);SalesLineEntity l=new SalesLineEntity();l.setSalesId(id);l.setItemCode(d.itemCode());l.setQuantity(d.quantity());l.setRate(d.rate());l.setDiscountPercent(d.discountPercent());l.setDiscountAmount(d.discountAmount());l.setGstPercent(d.gstPercent());l.setLineTotal(d.totalAmount());salesLines.save(l);}}
 private void restoreSaleStock(int id){for(var l:salesLines.findBySalesIdOrderByIdAsc(id))changeStock(l.getItemCode(),n(l.getQuantity()),false);}
 private void replacePurchaseLines(int id,List<OperationDtos.LineDto> ls,boolean skipStock){purchaseLines.deleteByPurchaseId(id);if(ls==null)return;for(var d:ls){if(!skipStock)changeStock(d.itemCode(),d.quantity(),false);PurchaseLineEntity l=new PurchaseLineEntity();l.setPurchaseId(id);l.setItemCode(d.itemCode());l.setQuantity(d.quantity());l.setRate(d.rate());l.setDiscountPercent(d.discountPercent());l.setDiscountAmount(d.discountAmount());l.setGstPercent(d.gstPercent());l.setLineTotal(d.totalAmount());purchaseLines.save(l);}}
 private void restorePurchaseStock(int id){for(var l:purchaseLines.findByPurchaseIdOrderByIdAsc(id))changeStock(l.getItemCode(),-n(l.getQuantity()),true);}
 private void changeStock(String code,double delta,boolean enforce){if(code==null||code.isBlank())throw new IllegalArgumentException("Item code is required");if(!Double.isFinite(delta))throw new IllegalArgumentException("Stock quantity must be finite");ItemEntity i=items.findByItemCodeForUpdate(code).orElseThrow(()->new IllegalArgumentException("Item not found: "+code));double now=n(i.getOpeningStock());double next=now+delta;if(enforce&&next<-.0001)throw new IllegalStateException("Insufficient stock for item "+code);i.setOpeningStock(Math.max(0,next));}

private OperationDtos.SaleDto saleDto(SalesHeaderEntity h,boolean detail){var p=h.getCustomer();List<OperationDtos.LineDto> ls=detail?salesLines.findBySalesIdOrderByIdAsc(h.getId()).stream().map(this::line).toList():List.of();double qty=detail?ls.stream().mapToDouble(OperationDtos.LineDto::quantity).sum():salesLines.findBySalesIdOrderByIdAsc(h.getId()).stream().mapToDouble(x->n(x.getQuantity())).sum();return new OperationDtos.SaleDto(h.getId(),h.getInvoiceNo(),dateOnly(h.getInvoiceDate()),party(p),n(h.getSubtotal()),n(h.getDiscountAmount()),n(h.getGstAmount()),n(h.getTotalAmount()),h.getRemarks(),h.getCreatedAt(),n(h.getEmailSent())!=0,dateOnly(h.getDueDate()),n(h.getPaidAmount()),h.getPaymentStatus(),n(h.getWhatsappSent())!=0,h.getInvoiceType(),h.getSalesperson(),h.getSource(),h.getNotes(),h.getDeliveryAddress(),h.getPaymentTerms(),h.getTransporter(),h.getReferenceNo(),dateOnly(h.getPoDate()),h.getBillingAddress(),h.getGstType(),h.getDoorDelivery(),h.getVehicleNumber(),h.getContactPerson(),h.getTransportNote(),h.getOrderNo(),h.getGstin(),h.getBillingGstin(),h.getDeliveryGstin(),h.getTransporterGstin(),h.getChargeType(),n(h.getChargeAmount()),h.getContactPersonMobile(),h.getDocumentStatus(),qty,ls);}
 private OperationDtos.PurchaseDto purchaseDto(PurchaseHeaderEntity h,boolean detail){return purchaseDto(h,detail,effectivePurchasePaid(h,0d));}
 private OperationDtos.PurchaseDto purchaseDto(PurchaseHeaderEntity h,boolean detail,double paid){var p=h.getSupplier();List<OperationDtos.LineDto> ls=detail?purchaseLines.findByPurchaseIdOrderByIdAsc(h.getId()).stream().map(this::line).toList():List.of();double qty=detail?ls.stream().mapToDouble(OperationDtos.LineDto::quantity).sum():purchaseLines.findByPurchaseIdOrderByIdAsc(h.getId()).stream().mapToDouble(x->n(x.getQuantity())).sum();double total=n(h.getTotalAmount()),effective=Math.min(total,Math.max(0,paid));String ps=up(h.getPaymentStatus());String status=total>0&&effective+0.0001>=total?"PAID":effective>0.0001?"PARTIAL":(blank(ps)?"PENDING":ps);return new OperationDtos.PurchaseDto(h.getId(),h.getInvoiceNo(),dateOnly(h.getInvoiceDate()),party(p),n(h.getSubtotal()),n(h.getGstAmount()),total,h.getRemarks(),h.getCreatedAt(),n(h.getEmailSent())!=0,dateOnly(h.getDueDate()),effective,status,h.getDocumentStatus(),h.getWarehouse(),h.getPaymentTerms(),h.getCurrency(),h.getReferenceNo(),h.getGstTreatment(),h.getTransporter(),h.getLrAwbNo(),h.getDiscountType(),n(h.getDiscountAmount()),h.getAttachmentPath(),h.getCreatedBy(),dateOnly(h.getDeliveryDate()),qty,ls);}
 private Map<Integer,Double> recordedPurchasePayments(){Map<Integer,Double> out=new HashMap<>();jdbc.query("SELECT document_id,COALESCE(SUM(amount),0) FROM payment_record WHERE UPPER(document_type)='PURCHASE' GROUP BY document_id",r->out.put(r.getInt(1),r.getDouble(2)));return out;}
 private double effectivePurchasePaid(PurchaseHeaderEntity h,double recorded){double total=n(h.getTotalAmount()),paid=Math.max(n(h.getPaidAmount()),recorded);String ps=up(h.getPaymentStatus());if(total>0&&Set.of("PAID","SETTLED").contains(ps))paid=Math.max(paid,total);return total>0?Math.min(total,paid):Math.max(0,paid);}
 private OperationDtos.LineDto line(SalesLineEntity l){String desc=items.findByItemCode(l.getItemCode()).map(ItemEntity::getDescription).orElse(null);return new OperationDtos.LineDto(l.getItemCode(),desc,n(l.getQuantity()),n(l.getRate()),n(l.getDiscountPercent()),n(l.getDiscountAmount()),n(l.getGstPercent()),n(l.getLineTotal()));} private OperationDtos.LineDto line(PurchaseLineEntity l){String desc=items.findByItemCode(l.getItemCode()).map(ItemEntity::getDescription).orElse(null);return new OperationDtos.LineDto(l.getItemCode(),desc,n(l.getQuantity()),n(l.getRate()),n(l.getDiscountPercent()),n(l.getDiscountAmount()),n(l.getGstPercent()),n(l.getLineTotal()));}
 private OperationDtos.PartyDto party(PartyEntity p){return p==null?null:new OperationDtos.PartyDto(p.getId(),p.getPartyCode(),p.getName(),p.getEmail(),p.getPhone(),p.getGstin(),p.getAddress());}
private void copySale(OperationDtos.SaleDto d,SalesHeaderEntity h){h.setInvoiceNo(d.invoiceNo());h.setInvoiceDate(d.invoiceDate());h.setCustomer(parties.findById(req(d.customer()==null?null:d.customer().id())).orElseThrow(()->new IllegalArgumentException("Customer not found")));h.setSubtotal(d.subtotal());h.setDiscountAmount(d.discountAmount());h.setGstAmount(d.gstAmount());h.setTotalAmount(d.totalAmount());h.setRemarks(d.remarks());h.setDueDate(d.dueDate());h.setPaidAmount(d.paidAmount());h.setPaymentStatus(d.paymentStatus());h.setWhatsappSent(d.whatsappSent()?1:0);h.setInvoiceType(d.invoiceType());h.setSalesperson(d.salesperson());h.setSource(d.source());h.setNotes(d.notes());h.setDeliveryAddress(d.deliveryAddress());h.setPaymentTerms(d.paymentTerms());h.setTransporter(d.transporter());h.setReferenceNo(d.referenceNo());h.setPoDate(d.poDate());h.setBillingAddress(d.billingAddress());h.setGstType(d.gstType());h.setDoorDelivery(d.doorDelivery());h.setVehicleNumber(d.vehicleNumber());h.setContactPerson(d.contactPerson());h.setTransportNote(d.transportNote());h.setOrderNo(d.orderNo());h.setGstin(d.gstin());h.setBillingGstin(d.billingGstin());h.setDeliveryGstin(d.deliveryGstin());h.setTransporterGstin(d.transporterGstin());h.setChargeType(d.chargeType());h.setChargeAmount(d.chargeAmount());h.setContactPersonMobile(d.contactPersonMobile());h.setDocumentStatus(d.documentStatus());}
 private void copyPurchase(OperationDtos.PurchaseDto d,PurchaseHeaderEntity h){h.setInvoiceNo(d.invoiceNo());h.setInvoiceDate(d.invoiceDate());h.setSupplier(parties.findById(req(d.supplier()==null?null:d.supplier().id())).orElseThrow(()->new IllegalArgumentException("Supplier not found")));h.setSubtotal(d.subtotal());h.setGstAmount(d.gstAmount());h.setTotalAmount(d.totalAmount());h.setRemarks(d.remarks());h.setDueDate(d.dueDate());h.setPaidAmount(d.paidAmount());h.setPaymentStatus(d.paymentStatus());h.setDocumentStatus(d.documentStatus());h.setEmailSent(d.emailSent()?1:0);h.setWarehouse(d.warehouse());h.setPaymentTerms(d.paymentTerms());h.setCurrency(d.currency());h.setReferenceNo(d.referenceNo());h.setGstTreatment(d.gstTreatment());h.setTransporter(d.transporter());h.setLrAwbNo(d.lrAwbNo());h.setDiscountType(d.discountType());h.setDiscountAmount(d.discountAmount());h.setAttachmentPath(d.attachmentPath());if(h.getId()==null)h.setCreatedBy(CurrentUser.require().username());h.setDeliveryDate(d.deliveryDate());}
 private void copyFinance(OperationDtos.FinanceDto d,FinanceRegisterEntity e){if(d.voucherNo()!=null)e.setVoucherNo(d.voucherNo());e.setVoucherType(d.voucherType());e.setVoucherDate(d.voucherDate());e.setPartyId(d.partyId());e.setCategory(d.category());e.setReferenceNo(d.referenceNo());e.setAmount(d.amount());e.setPaymentMode(d.paymentMode());e.setNotes(d.notes());e.setAccountName(d.accountName());if(d.billPath()!=null)e.setBillPath(d.billPath());e.setReconciled(d.reconciled()?1:0);}
 private OperationDtos.FinanceDto financeDto(FinanceRegisterEntity e){Long statementId=null;String targetType=null;Integer targetId=null;String documentNo=null;var active=reconciliationAllocations.findByFinanceEntryIdAndReversedAtIsNull(e.getId());if(!active.isEmpty()){var a=active.get(0);statementId=a.getStatementTransactionId();if(active.size()>1){targetType="MULTIPLE";documentNo="Multiple ("+active.size()+")";}else{targetType=up(a.getTargetType());targetId=a.getTargetId();if("SALE".equals(targetType)&&targetId!=null)documentNo=sales.findById(targetId).map(SalesHeaderEntity::getInvoiceNo).orElse(null);else if("PURCHASE".equals(targetType)&&targetId!=null)documentNo=purchases.findById(targetId).map(PurchaseHeaderEntity::getInvoiceNo).orElse(null);else if("EXPENSE".equals(targetType))documentNo=e.getVoucherNo();}}return new OperationDtos.FinanceDto(e.getId(),e.getVoucherNo(),e.getVoucherType(),dateOnly(e.getVoucherDate()),e.getPartyId(),e.getCategory(),e.getReferenceNo(),n(e.getAmount()),e.getPaymentMode(),e.getNotes(),e.getAccountName(),e.getBillPath(),n(e.getReconciled())!=0,statementId,targetType,targetId,documentNo);}
 private String formattedNext(String code,String fallback,List<String> existing){String fmt=fallback;var c=categories.findByCategoryCode(code).orElse(null);if(c!=null){var vals=lookups.findByLookupTypeAndActiveTrueOrderByDisplayOrderAscLookupValueAsc(c.getCategoryName());if(!vals.isEmpty()&&!blank(vals.get(0).getLookupValue()))fmt=vals.get(0).getLookupValue().trim();}LocalDate t=LocalDate.now();String dated=fmt.replace("DD-MM-YYYY",t.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"))).replace("DD/MM/YYYY",t.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))).replace("YYYY-MM-DD",t.toString());Matcher m=Pattern.compile("X{2,}").matcher(dated);if(!m.find()){dated+="/XXXX";m=Pattern.compile("X{2,}").matcher(dated);m.find();}int w=m.end()-m.start();String pre=dated.substring(0,m.start()),suf=dated.substring(m.end());int max=0;for(String x:existing){if(x.startsWith(pre)&&x.endsWith(suf)){try{max=Math.max(max,Integer.parseInt(x.substring(pre.length(),x.length()-suf.length())));}catch(Exception ignored){}}}return pre+String.format(Locale.ROOT,"%0"+w+"d",max+1)+suf;}
 private static int req(Integer v){if(v==null||v<=0)throw new IllegalArgumentException("Required id missing");return v;} private static double n(Number v){return v==null?0:v.doubleValue();} private static String up(String v){return v==null?"":v.trim().toUpperCase(Locale.ROOT);} private static boolean blank(String v){return v==null||v.isBlank();}
 private static String dateOnly(String v){if(v==null)return null;return v.length()>=10?v.substring(0,10):v;} private static LocalDate date(String v){try{return LocalDate.parse(dateOnly(v));}catch(Exception e){return null;}}
}
