package org.example.controller;

import org.example.api.support.SupportApiClient;
import org.example.util.OwnedAlert;
import org.example.util.OwnedTextInputDialog;
import java.util.List;
import org.example.util.IconFactory;
import org.example.util.TableSelectionSupport;
import org.example.util.SemanticTableCells;
import org.example.util.UiActionIcons;
import org.example.util.ScreenRefreshPolicy;
import org.example.navigation.ScreenLifecycle;
import org.example.util.FxDebouncer;
import org.example.util.UiTaskExecutor;
import org.example.util.PerformanceMonitor;
import org.example.util.InvoicePaymentDetailsDialog;
import javafx.print.PrinterJob;
import javafx.scene.Node;
import com.itextpdf.layout.element.Table;
import com.itextpdf.kernel.pdf.*;import com.itextpdf.layout.Document;import com.itextpdf.layout.element.*;import javafx.beans.property.*;import javafx.collections.FXCollections;import javafx.fxml.*;import javafx.geometry.Pos;import javafx.scene.Parent;import javafx.scene.control.*;import javafx.scene.layout.*;import javafx.stage.FileChooser;import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.example.model.Purchase;import org.example.navigation.NavigationManager;import org.example.service.*;import java.io.*;import java.nio.file.Path;import java.text.NumberFormat;import java.time.LocalDate;import java.util.*;
public class PurchaseListController implements ScreenLifecycle{
 public PurchaseListController(){}
 @FXML private Label lblTotal,lblTotalCount,lblToday,lblTodayCount,lblPending,lblPendingCount,lblOverdue,lblOverdueCount,lblPaid,lblSummary,lblPageInfo,lblPageNumber,lblDetailInvoice,lblDetailSupplier,lblDetailContact,lblDetailAmount,lblDetailPaid,lblDetailBalance,lblDetailDue;@FXML private Button btnNewPurchase,btnReset,btnRefresh,btnFirstPage,btnPreviousPage,btnNextPage,btnLastPage,btnExportExcel,btnExportPdf,btnTodayRange,btnYesterdayRange,btnSevenDaysRange,btnThirtyDaysRange,btnCustomRange;@FXML private TextField txtSearch;@FXML private ComboBox<String>cmbSupplier,cmbPaymentStatus,cmbMailStatus;@FXML private ComboBox<Integer>cmbPageSize;@FXML private DatePicker dpFrom,dpTo;@FXML private ToggleButton btnAdvanced;@FXML private GridPane advancedFilters;@FXML private TableView<Purchase>tablePurchase;@FXML private TableColumn<Purchase,String>colInvoice,colDate,colSupplier,colMobile,colDue,colStatus,colMail;private final TableColumn<Purchase,String>colWhatsapp=new TableColumn<>("WhatsApp");@FXML private TableColumn<Purchase,Double>colAmount,colPaid,colBalance;@FXML private TableColumn<Purchase,Void>colActions;@FXML private SplitPane mainSplit;@FXML private VBox detailDrawer;@FXML private Button btnCloseDetails;@FXML private StackPane purchaseTotalIcon,purchaseOrdersIcon,purchaseSuppliersIcon,purchaseItemsIcon,purchasePaidIcon;
 private final PurchaseService service=new PurchaseService();private final SupportApiClient support=new SupportApiClient();private final FxDebouncer searchDebouncer=new FxDebouncer(java.time.Duration.ofMillis(220));private final NumberFormat money=NumberFormat.getCurrencyInstance(Locale.of("en", "IN"));private final Map<Integer,Boolean>whatsappState=new HashMap<>();private List<Purchase>all=List.of(),filtered=List.of();private Purchase selected;private int currentPage;
 @FXML public void initialize(){
        installKpiIcons();configureExplicitTableHeaderIcons();applyRangeButtonIcons();configureExplicitButtonIcons();configureDetailsCloseButton();colInvoice.setCellValueFactory(v->new SimpleStringProperty(v.getValue().getInvoiceNo()));colDate.setCellValueFactory(v->new SimpleStringProperty(v.getValue().getInvoiceDate().toString()));colSupplier.setCellValueFactory(v->new SimpleStringProperty(v.getValue().getSupplier().getName()));colMobile.setCellValueFactory(v->new SimpleStringProperty(s(v.getValue().getSupplier().getPhone())));colAmount.setCellValueFactory(v->new SimpleDoubleProperty(v.getValue().getTotalAmount()).asObject());colPaid.setCellValueFactory(v->new SimpleDoubleProperty(v.getValue().getPaidAmount()).asObject());colBalance.setCellValueFactory(v->new SimpleDoubleProperty(v.getValue().getBalanceAmount()).asObject());colDue.setCellValueFactory(v->new SimpleStringProperty(due(v.getValue())));colStatus.setCellValueFactory(v->new SimpleStringProperty(v.getValue().getPaymentStatus()));colMail.setCellValueFactory(v->new SimpleStringProperty(v.getValue().isEmailSent()?"Sent":"Not Sent"));colAmount.setCellFactory(x->totalMoneyCell());colPaid.setCellFactory(x->paidMoneyCell());colBalance.setCellFactory(x->balanceMoneyCell());colStatus.setCellFactory(x->pill());colMail.setCellFactory(x->pill());setupActions();cmbPaymentStatus.getItems().setAll("All","PENDING","PARTIAL","PAID","OVERDUE");cmbPaymentStatus.setValue("All");cmbMailStatus.getItems().setAll("All","Sent","Not Sent");cmbMailStatus.setValue("All");cmbSupplier.getItems().setAll("All Suppliers");cmbSupplier.setValue("All Suppliers");cmbPageSize.getItems().setAll(10,25,50,100);cmbPageSize.setValue(25);cmbPageSize.valueProperty().addListener((o,a,b)->{currentPage=0;renderPage();});dpFrom.setValue(null);dpTo.setValue(null);txtSearch.textProperty().addListener((o,a,b)->searchDebouncer.submit(this::filter));cmbSupplier.valueProperty().addListener((o,a,b)->filter());cmbPaymentStatus.valueProperty().addListener((o,a,b)->filter());cmbMailStatus.valueProperty().addListener((o,a,b)->filter());tablePurchase.getSelectionModel().selectedItemProperty().addListener((o,a,b)->{if(b!=null)details(b);});detailDrawer.setManaged(false);detailDrawer.setVisible(false);mainSplit.setDividerPositions(1);refresh();configureModernTable();installRegisterTools();}

 private void installKpiIcons(){
  setKpiIcon(purchaseTotalIcon,"purchase");setKpiIcon(purchaseOrdersIcon,"document");setKpiIcon(purchaseSuppliersIcon,"supplier");setKpiIcon(purchaseItemsIcon,"item");setKpiIcon(purchasePaidIcon,"payment");
 }
 private void setKpiIcon(StackPane pane,String semantic){if(pane!=null)pane.getChildren().setAll(IconFactory.compactIcon(semantic,22));}

 private TableCell<Purchase,Double> moneyCell(){return new TableCell<>(){protected void updateItem(Double v,boolean e){super.updateItem(v,e);setText(e||v==null?null:fmt(v));setAlignment(Pos.CENTER_RIGHT);}};}
 private TableCell<Purchase,Double> totalMoneyCell(){return coloredMoneyCell("register-total-amount",null);}
 private TableCell<Purchase,Double> balanceMoneyCell(){return coloredMoneyCell("register-balance-pending","register-balance-settled");}
 private TableCell<Purchase,Double> coloredMoneyCell(String positiveClass,String zeroClass){return new TableCell<>(){protected void updateItem(Double v,boolean e){super.updateItem(v,e);setText(e||v==null?null:fmt(v));setAlignment(Pos.CENTER_RIGHT);getStyleClass().removeAll("register-total-amount","register-balance-pending","register-balance-settled");if(!e&&v!=null){String style=v>.009?positiveClass:zeroClass;if(style!=null)getStyleClass().add(style);}}};}
 private TableCell<Purchase,Double> paidMoneyCell(){return new TableCell<>(){protected void updateItem(Double v,boolean e){super.updateItem(v,e);setText(e||v==null?null:fmt(v));setAlignment(Pos.CENTER_RIGHT);getStyleClass().removeAll("purchase-paid-positive","purchase-paid-zero");if(!e&&v!=null)getStyleClass().add(v>.009?"purchase-paid-positive":"purchase-paid-zero");}};}
 private void configureExplicitButtonIcons(){
  setButtonIcon(btnNewPurchase,"purchase");setButtonIcon(btnAdvanced,"filter");setButtonIcon(btnReset,"refresh");setButtonIcon(btnRefresh,"refresh");
  setButtonIcon(btnFirstPage,"first");setButtonIcon(btnPreviousPage,"previous");setButtonIcon(btnNextPage,"next");setButtonIcon(btnLastPage,"last");
  setButtonIcon(btnExportExcel,"excel");setButtonIcon(btnExportPdf,"pdf");
 }
 private void setButtonIcon(ButtonBase button,String semantic){UiActionIcons.apply(button, semantic);}
 private void configureModernTable(){
 colStatus.setText("Doc Status");colStatus.setMinWidth(118);colStatus.setPrefWidth(118);colStatus.setCellValueFactory(v->new SimpleStringProperty(documentStatus(v.getValue())));
 colWhatsapp.setMinWidth(100);colWhatsapp.setPrefWidth(100);colWhatsapp.setCellValueFactory(v->new SimpleStringProperty(Boolean.TRUE.equals(whatsappState.get(v.getValue().getId()))?"Sent":"Not Sent"));
  tablePurchase.getColumns().add(tablePurchase.getColumns().indexOf(colActions),colWhatsapp);
  colDue.setGraphic(IconFactory.icon("reminder"));colStatus.setGraphic(IconFactory.icon("status"));colMail.setGraphic(IconFactory.icon("email"));colWhatsapp.setGraphic(IconFactory.icon("whatsapp"));
  colStatus.setCellFactory(x->SemanticTableCells.status("document"));colMail.setCellFactory(x->SemanticTableCells.status("email"));colWhatsapp.setCellFactory(x->SemanticTableCells.status("whatsapp"));colDue.setCellFactory(x->SemanticTableCells.dueDate());
  tablePurchase.setRowFactory(tv->{TableRow<Purchase> row=new TableRow<>();row.setOnMouseClicked(e->{if(e.getClickCount()==2&&!row.isEmpty())showPaymentDetails(row.getItem());});return row;});
  // Apply the resize policy after every dynamic column has been installed. This
  // makes the register consume the complete available width in both themes.
  colActions.setMinWidth(118);colActions.setPrefWidth(118);colActions.setMaxWidth(118);
  tablePurchase.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);
 }
 private void showPaymentDetails(Purchase purchase){try{InvoicePaymentDetailsDialog.show(tablePurchase,support,"PURCHASE",purchase.getId(),purchase.getInvoiceNo(),"Supplier",purchase.getSupplier()==null?"":purchase.getSupplier().getName(),purchase.getTotalAmount(),purchase.getPaidAmount(),purchase.getBalanceAmount());}catch(Exception e){error(e);}}
 private TableCell<Purchase,String>purchaseDueCell(){return new TableCell<>(){@Override protected void updateItem(String value,boolean empty){super.updateItem(value,empty);setText(empty?null:value);setGraphic(null);getStyleClass().removeAll("pill-success","pill-warning","pill-danger");if(!empty&&value!=null){boolean paid=value.startsWith("Paid"),overdue=value.startsWith("Overdue");getStyleClass().add(paid?"pill-success":overdue?"pill-danger":"pill-warning");setGraphic(IconFactory.statusIcon(overdue?"error":paid?"save":"reminder",overdue?"#dc2626":paid?"#16a34a":"#2563eb"));}}};}
 private TableCell<Purchase,String>pill(){return pill("document");}private TableCell<Purchase,String>pill(String icon){return new TableCell<>(){protected void updateItem(String v,boolean e){super.updateItem(v,e);setText(e?null:v);setGraphic(null);getStyleClass().removeAll("pill-success","pill-warning","pill-danger");if(!e&&v!=null){boolean good="COMPLETED".equals(v)||"Sent".equals(v),pending="IN PROGRESS".equals(v)||"PENDING".equals(v);getStyleClass().add(good?"pill-success":pending?"pill-warning":"pill-danger");setGraphic(IconFactory.statusIcon(good?icon:pending?("document".equals(icon)?"reminder":icon):"error",good?"#16a34a":pending?"#2563eb":"#dc2626"));}}};}
 private String documentStatus(Purchase p){if("CANCELLED".equalsIgnoreCase(p.getDocumentStatus()))return "CANCELLED";if(p.getBalanceAmount()<=.01)return "COMPLETED";if(p.getPaidAmount()>0)return "IN PROGRESS";return "PENDING";}
 private void installRegisterTools(){Node parent=tablePurchase.getParent();if(!(parent instanceof VBox box))return;HBox bar=null;for(Node n:box.getChildren())if(n instanceof HBox h&&h.getStyleClass().contains("export-bar")){bar=h;break;}if(bar==null||bar.getProperties().putIfAbsent("tools-installed",true)!=null)return;Button print=new Button("Print");print.setGraphic(IconFactory.icon("print"));print.getStyleClass().add("secondary-button");print.setOnAction(e->printRegister());bar.getChildren().add(Math.min(2,bar.getChildren().size()),print);}
 private void printRegister(){PrinterJob job=PrinterJob.createPrinterJob();if(job!=null&&job.showPrintDialog(tablePurchase.getScene().getWindow())){if(job.printPage(tablePurchase))job.endJob();}}
 private void setupActions(){colActions.setCellFactory(c->new TableCell<>(){
  final MenuButton m=new MenuButton();
  {m.getProperties().put("erp.icon.semantic","actions");m.setGraphic(IconFactory.compactIcon("actions",15));item("View Details","view",e->details(row()));item("Edit Purchase","edit",e->edit(row()));item("Duplicate Purchase","purchase",e->duplicate(row()));item("Print / Download PDF","print",e->pdf(row()));item("Send Email","email",e->email(row()));item("Send WhatsApp","whatsapp",e->whatsapp(row()));item("Record Payment","payment",e->payment(row()));item("View Payments","payment",e->viewPayments(row()));item("Create Purchase Return","return",e->createReturn(row()));item("Attach Document","attachment",e->attach(row()));item("Notes / Remarks","document",e->notes(row()));MenuItem cancel=item("Cancel Purchase","cancel",e->cancelPurchase(row()));MenuItem delete=item("Delete Purchase","delete",e->delete(row()));m.setOnShowing(e->{Purchase current=getTableRow()==null?null:getTableRow().getItem();boolean locked=current!=null&&isFinanciallyLocked(current);cancel.setDisable(locked);cancel.setVisible(!locked);delete.setDisable(locked);delete.setVisible(!locked);});m.getStyleClass().add("row-actions");m.setGraphic(IconFactory.compactIcon("actions",16));m.setContentDisplay(ContentDisplay.GRAPHIC_ONLY);m.setTooltip(new Tooltip("Actions"));}
  private Purchase row(){Purchase value=getTableRow()==null?null:getTableRow().getItem();if(value==null)throw new IllegalStateException("This purchase row is no longer available. Refresh the register and try again.");return value;}
  private MenuItem item(String n,String icon,javafx.event.EventHandler<javafx.event.ActionEvent>h){MenuItem i=new MenuItem(n);i.setGraphic(IconFactory.icon(icon));i.setOnAction(event->{try{h.handle(event);}catch(Throwable failure){error(failure);}});m.getItems().add(i);return i;}
  protected void updateItem(Void v,boolean e){super.updateItem(v,e);setGraphic(e?null:m);setAlignment(Pos.CENTER);}
 });}
 @FXML public void refresh(){
  btnRefresh.setDisable(true);
  UiTaskExecutor.submitLatest("purchase-register-load",
   () -> {
    List<Purchase> rows=service.getAll();
    return new PurchaseLoad(rows==null?List.of():List.copyOf(rows),readWhatsappState());
   },
   this::applyPurchaseLoad,
   failure -> {btnRefresh.setDisable(false);this.error(failure);});
 }
 private void applyPurchaseLoad(PurchaseLoad loaded){
  long started=System.nanoTime();
  all=loaded.rows();
  whatsappState.clear();whatsappState.putAll(loaded.whatsapp());
  cmbSupplier.getItems().setAll("All Suppliers");
  cmbSupplier.getItems().addAll(all.stream().map(Purchase::getSupplier).filter(Objects::nonNull).map(p->p.getName()).filter(Objects::nonNull).map(String::trim).filter(name->!name.isBlank()).distinct().sorted(String.CASE_INSENSITIVE_ORDER).toList());
  if(cmbSupplier.getValue()==null||cmbSupplier.getValue().startsWith("All"))cmbSupplier.setValue("All Suppliers");
  metrics();filter();ScreenRefreshPolicy.markRefreshed("purchase-register");btnRefresh.setDisable(false);
  long ms=(System.nanoTime()-started)/1_000_000L;PerformanceMonitor.event("controller-phase","purchase-register-apply | "+ms+" ms | rows="+all.size());
 }
 private Map<Integer,Boolean> readWhatsappState(){Map<Integer,Boolean> state=new HashMap<>();try{for(SupportApiClient.CommunicationRow r:support.communications())if("PURCHASE".equalsIgnoreCase(r.entityType())&&"WHATSAPP".equalsIgnoreCase(r.channel())&&"SENT".equalsIgnoreCase(r.status()))state.put(r.entityId(),true);}catch(Exception ignored){}return state;}
 private void metrics(){double total=all.stream().mapToDouble(Purchase::getTotalAmount).sum(),paid=all.stream().mapToDouble(Purchase::getPaidAmount).sum(),items=all.stream().mapToDouble(Purchase::getQuantity).sum();long suppliers=all.stream().map(Purchase::getSupplier).filter(Objects::nonNull).map(p->p.getId()).distinct().count();lblTotal.setText(fmt(total));lblTotalCount.setText("All Time");lblToday.setText(String.valueOf(all.size()));lblTodayCount.setText("All Time");lblPending.setText(String.valueOf(suppliers));lblPendingCount.setText("All Time");lblOverdue.setText(String.valueOf((long)items));lblOverdueCount.setText("All Time");lblPaid.setText(fmt(paid));}
 private void filter(){String q=s(txtSearch.getText()).toLowerCase(),sup=cmbSupplier.getValue(),ps=cmbPaymentStatus.getValue(),mail=cmbMailStatus.getValue();filtered=all.stream().filter(p->q.isBlank()||(p.getInvoiceNo()+p.getSupplier().getName()+s(p.getSupplier().getPhone())+s(p.getSupplier().getGstin())).toLowerCase().contains(q)).filter(p->sup==null||sup.startsWith("All")||sup.equals(p.getSupplier().getName())).filter(p->dpFrom.getValue()==null||!p.getInvoiceDate().isBefore(dpFrom.getValue())).filter(p->dpTo.getValue()==null||!p.getInvoiceDate().isAfter(dpTo.getValue())).filter(p->ps==null||ps.equals("All")||ps.equals(p.getPaymentStatus())).filter(p->mail==null||mail.equals("All")||mail.equals(p.isEmailSent()?"Sent":"Not Sent")).toList();currentPage=0;renderPage();lblSummary.setText(filtered.size()+" purchases • Total "+fmt(filtered.stream().mapToDouble(Purchase::getTotalAmount).sum())+" • Balance "+fmt(filtered.stream().mapToDouble(Purchase::getBalanceAmount).sum()));}
 private void renderPage(){int size=cmbPageSize.getValue()==null?25:cmbPageSize.getValue(),pages=Math.max(1,(int)Math.ceil(filtered.size()/(double)size));currentPage=Math.min(currentPage,pages-1);int from=Math.min(currentPage*size,filtered.size()),to=Math.min(from+size,filtered.size());tablePurchase.setItems(FXCollections.observableArrayList(filtered.subList(from,to)));lblPageNumber.setText((currentPage+1)+" / "+pages);lblPageInfo.setText(filtered.isEmpty()?"No entries":"Showing "+(from+1)+" to "+to+" of "+filtered.size()+" entries");}
 @FXML private void firstPage(){currentPage=0;renderPage();}@FXML private void previousPage(){if(currentPage>0)currentPage--;renderPage();}@FXML private void nextPage(){int size=cmbPageSize.getValue()==null?25:cmbPageSize.getValue(),pages=Math.max(1,(int)Math.ceil(filtered.size()/(double)size));if(currentPage<pages-1)currentPage++;renderPage();}@FXML private void lastPage(){int size=cmbPageSize.getValue()==null?25:cmbPageSize.getValue();currentPage=Math.max(0,(int)Math.ceil(filtered.size()/(double)size)-1);renderPage();}
 @FXML private void showToday(){applyDateRange(LocalDate.now(),LocalDate.now());}
 @FXML private void showYesterday(){LocalDate d=LocalDate.now().minusDays(1);applyDateRange(d,d);}
 @FXML private void showSevenDays(){applyDateRange(LocalDate.now().minusDays(6),LocalDate.now());}
 @FXML private void showThirtyDays(){applyDateRange(LocalDate.now().minusDays(29),LocalDate.now());}
 @FXML private void showCustomRange(){dpFrom.requestFocus();}
 private void applyDateRange(LocalDate from,LocalDate to){dpFrom.setValue(from);dpTo.setValue(to);filter();}
 @FXML private void toggleAdvanced(){advancedFilters.setManaged(btnAdvanced.isSelected());advancedFilters.setVisible(btnAdvanced.isSelected());}@FXML private void resetFilters(){txtSearch.clear();cmbSupplier.setValue("All Suppliers");cmbPaymentStatus.setValue("All");cmbMailStatus.setValue("All");dpFrom.setValue(null);dpTo.setValue(null);filter();}
 @FXML private void newPurchase(){StackPane p=(StackPane)tablePurchase.getScene().lookup("#contentPane");if(p!=null)NavigationManager.forPane(p).loadPage("/fxml/pages/Purchase.fxml");}private void edit(Purchase p){try{FXMLLoader l=new FXMLLoader(getClass().getResource("/fxml/pages/Purchase.fxml"));Parent root=l.load();((PurchaseController)l.getController()).loadPurchase(service.getByInvoice(p.getInvoiceNo()));((StackPane)tablePurchase.getScene().lookup("#contentPane")).getChildren().setAll(root);}catch(Exception e){error(e);}}
 private void details(Purchase p){selected=p;detailDrawer.setManaged(true);detailDrawer.setVisible(true);mainSplit.setDividerPositions(.8);lblDetailInvoice.setText(p.getInvoiceNo());lblDetailSupplier.setText(p.getSupplier().getName());lblDetailContact.setText(s(p.getSupplier().getPhone())+"\n"+s(p.getSupplier().getEmail())+"\n"+s(p.getSupplier().getGstin()));lblDetailAmount.setText(fmt(p.getTotalAmount()));lblDetailPaid.setText(fmt(p.getPaidAmount()));lblDetailBalance.setText(fmt(p.getBalanceAmount()));lblDetailDue.setText(due(p));}private void configureDetailsCloseButton(){
     if(btnCloseDetails == null) return;
     btnCloseDetails.setGraphic(IconFactory.icon("cancel"));
     btnCloseDetails.getProperties().put("erp-icon-preserve", true);
     btnCloseDetails.setAccessibleText("Close purchase details");
 }
 @FXML private void closeDetails(){selected=null;detailDrawer.setManaged(false);detailDrawer.setVisible(false);mainSplit.setDividerPositions(1);}@FXML private void paySelected(){if(selected!=null)payment(selected);}@FXML private void pdfSelected(){if(selected!=null)pdf(selected);}@FXML private void emailSelected(){if(selected!=null)email(selected);}
 private void payment(Purchase p){if(p.getBalanceAmount()<=0){info("Invoice is fully paid.");return;}TextInputDialog d=new OwnedTextInputDialog(String.format(Locale.ROOT,"%.2f",p.getBalanceAmount()));d.setTitle("Supplier Payment");d.setHeaderText(p.getInvoiceNo()+" • Balance "+fmt(p.getBalanceAmount()));d.setContentText("Payment amount:");d.showAndWait().ifPresent(v->{try{double amount=Double.parseDouble(v);if(amount<=0||amount>p.getBalanceAmount()+.01)throw new IllegalArgumentException("Invalid payment amount");support.recordPayment(new SupportApiClient.PaymentRequest("PURCHASE",p.getId(),LocalDate.now().toString(),amount,"Bank","","",p.getSupplier()==null?"":p.getSupplier().getName(),"PAYMENT",null,user()));refresh();info("Supplier payment recorded.");}catch(Exception e){error(e);}});}
 private void pdf(Purchase p){try{Purchase full=requirePurchase(p);java.awt.Desktop.getDesktop().open(InvoicePdfService.purchase(full).toFile());}catch(Exception e){error(e);}}
 private void email(Purchase p){String stage="loading the purchase invoice";String recipient="";try{Purchase full=requirePurchase(p);if(full.getSupplier()==null)throw new IllegalStateException("No supplier is linked to "+full.getInvoiceNo()+".");recipient=s(full.getSupplier().getEmail()).trim();if(recipient.isBlank())throw new IllegalStateException("Supplier email is missing for "+full.getSupplier().getName()+". Update Supplier Master and try again.");stage="generating the purchase invoice PDF";Path pdf=InvoicePdfService.purchase(full);stage="sending the email";EmailService.send(recipient,"Purchase Invoice "+full.getInvoiceNo(),"Dear "+s(full.getSupplier().getName())+",\n\nPlease find the purchase invoice attached.\n\nRegards,\n"+org.example.config.ConfigManager.get("company.name","DSE ERP"),pdf);service.markEmailSent(full.getId());logCommunication(full.getId(),recipient,"Purchase Invoice "+full.getInvoiceNo(),"SENT",null);refresh();info("Email sent successfully to "+recipient+".");}catch(Exception failure){logCommunication(p.getId(),recipient,"Purchase Invoice "+p.getInvoiceNo(),"FAILED",stage+": "+rootMessage(failure));error(new IllegalStateException("Email failed while "+stage+".\n\n"+rootMessage(failure),failure));}}
 private Purchase requirePurchase(Purchase row){Purchase full=service.getByInvoice(row.getInvoiceNo());if(full==null)throw new IllegalStateException("Purchase invoice "+row.getInvoiceNo()+" was not found. Refresh the register and try again.");return full;}
 private void logCommunication(int id,String recipient,String subject,String status,String error){try{support.communication(new SupportApiClient.CommunicationRequest("PURCHASE",id,"EMAIL",recipient,subject,status,error,user()));}catch(Exception ignored){}}
 private String rootMessage(Throwable failure){Throwable root=failure;while(root.getCause()!=null)root=root.getCause();String message=root.getMessage();return message==null||message.isBlank()?root.getClass().getSimpleName():message;}
 private void whatsapp(Purchase p){try{Purchase full=service.getByInvoice(p.getInvoiceNo());String phone=s(full.getSupplier().getPhone()).replaceAll("\\D","");if(phone.length()==10)phone="91"+phone;if(phone.isBlank())throw new IllegalStateException("Supplier mobile number is missing. Update it in Supplier Master.");Path pdf=InvoicePdfService.purchase(full);WhatsappService.openWhatsappWithMessage(phone,PaymentMessageService.purchaseMessage(full),pdf,PaymentMessageService.configuredQrPath());support.communication(new SupportApiClient.CommunicationRequest("PURCHASE",full.getId(),"WHATSAPP",phone,"Purchase Invoice "+full.getInvoiceNo(),"SENT",null,user()));refresh();info("WhatsApp is ready. The purchase PDF and configured UPI QR are on the clipboard for attachment.");}catch(Exception e){error(e);}}
 private void delete(Purchase p){if(isFinanciallyLocked(p)){info("Paid or settled purchases cannot be deleted. Create a purchase return instead.");return;}if(new OwnedAlert(Alert.AlertType.CONFIRMATION,"Delete "+p.getInvoiceNo()+" and reverse received stock?",ButtonType.YES,ButtonType.NO).showAndWait().orElse(ButtonType.NO)!=ButtonType.YES)return;try{service.delete(p.getInvoiceNo());refresh();closeDetails();}catch(Exception e){error(e);}}
 private void duplicate(Purchase p){try{FXMLLoader l=new FXMLLoader(getClass().getResource("/fxml/pages/Purchase.fxml"));Parent root=l.load();PurchaseController c=l.getController();c.loadPurchase(service.getByInvoice(p.getInvoiceNo()));c.prepareDuplicate();((StackPane)tablePurchase.getScene().lookup("#contentPane")).getChildren().setAll(root);}catch(Exception e){error(e);}}
 private void viewPayments(Purchase p){StringBuilder b=new StringBuilder();try{for(SupportApiClient.PaymentRow r:support.payments("PURCHASE",p.getId()))b.append(r.date()).append("   ").append(fmt(r.amount())).append("   ").append(r.mode()).append("   ").append(r.reference()).append('\n');if(b.isEmpty())b.append("No payments recorded.");Alert a=new OwnedAlert(Alert.AlertType.INFORMATION,b.toString());a.setHeaderText("Payments • "+p.getInvoiceNo());a.showAndWait();}catch(Exception e){error(e);}}
 private void attach(Purchase p){FileChooser chooser=new FileChooser();File file=chooser.showOpenDialog(tablePurchase.getScene().getWindow());if(file==null)return;try{support.attachment("PURCHASE",p.getId(),file.getAbsolutePath());info("Document attached.");}catch(Exception e){error(e);}}
 private void notes(Purchase p){TextInputDialog d=new OwnedTextInputDialog(p.getRemarks());d.setHeaderText("Notes / Remarks • "+p.getInvoiceNo());d.showAndWait().ifPresent(v->{try{support.notes("PURCHASE",p.getId(),v);refresh();}catch(Exception e){error(e);}});}
 private void cancelPurchase(Purchase p){if(isFinanciallyLocked(p)){info("Paid or settled purchases cannot be cancelled. Create a purchase return instead.");return;}if(new OwnedAlert(Alert.AlertType.CONFIRMATION,"Cancel "+p.getInvoiceNo()+" and reverse its stock receipt?",ButtonType.YES,ButtonType.NO).showAndWait().orElse(ButtonType.NO)!=ButtonType.YES)return;try{support.cancelPurchase(p.getId());refresh();}catch(Exception e){error(e);}}
 private void createReturn(Purchase p){Purchase full=service.getByInvoice(p.getInvoiceNo());if(full==null){info("Purchase invoice not found. Refresh and try again.");return;}List<ReturnEditorService.InvoiceItem> items=full.getLines().stream().map(line->new ReturnEditorService.InvoiceItem(line.getItemCode(),line.getItemDescription(),line.getQuantity(),line.getRate(),line.getGstPercent())).toList();ReturnEditorService.show(tablePurchase.getScene().getWindow(),ReturnEditorService.Type.PURCHASE,p.getInvoiceNo(),p.getSupplier().getName(),p.getSupplier().getId(),items).ifPresent(no->{refresh();info("Purchase return created: "+no);});}
 @FXML private void exportPurchase(){File f=choose("Purchase_Register.xlsx","Excel","*.xlsx");if(f==null)return;try(Workbook w=new XSSFWorkbook();FileOutputStream o=new FileOutputStream(f)){Sheet sh=w.createSheet("Purchases");String[]h={"Invoice","Date","Supplier","Amount","Paid","Balance","Due","Status","Email"};Row r=sh.createRow(0);for(int i=0;i<h.length;i++)r.createCell(i).setCellValue(h[i]);int n=1;for(Purchase p:filtered){r=sh.createRow(n++);String[]v={p.getInvoiceNo(),p.getInvoiceDate().toString(),p.getSupplier().getName(),String.valueOf(p.getTotalAmount()),String.valueOf(p.getPaidAmount()),String.valueOf(p.getBalanceAmount()),String.valueOf(p.getDueDate()),p.getPaymentStatus(),p.isEmailSent()?"Sent":"Not Sent"};for(int i=0;i<v.length;i++)r.createCell(i).setCellValue(v[i]);}w.write(o);}catch(Exception e){error(e);}}@FXML private void exportPdf(){File f=choose("Purchase_Register.pdf","PDF","*.pdf");if(f==null)return;try{org.example.service.BrandedRegisterPdfService.export(f.toPath(),"Purchase Register",new String[]{"Invoice","Date","Supplier","Amount","Paid","Balance","Due","Status"},filtered.stream().map(x->new String[]{x.getInvoiceNo(),x.getInvoiceDate().toString(),x.getSupplier().getName(),fmt(x.getTotalAmount()),fmt(x.getPaidAmount()),fmt(x.getBalanceAmount()),due(x),x.getPaymentStatus()}).toList(),new float[]{2,1.3f,2.6f,1.4f,1.4f,1.4f,1.4f,1.2f});}catch(Exception e){error(e);}}

 private boolean isFinanciallyLocked(Purchase p){String payment=s(p.getPaymentStatus()).toUpperCase(java.util.Locale.ROOT),document=s(p.getDocumentStatus()).toUpperCase(java.util.Locale.ROOT);return p.getPaidAmount()>.009||p.getBalanceAmount()<=.009||payment.contains("PAID")||payment.contains("SETTLED")||document.contains("COMPLETED");}
 private File choose(String n,String l,String x){FileChooser c=new FileChooser();c.setInitialFileName(n);c.getExtensionFilters().add(new FileChooser.ExtensionFilter(l,x));return c.showSaveDialog(tablePurchase.getScene().getWindow());}private String due(Purchase p){String document=s(p.getDocumentStatus()).toUpperCase(java.util.Locale.ROOT);if(document.contains("CANCEL"))return"Cancelled";String status=s(p.getPaymentStatus()).toUpperCase(java.util.Locale.ROOT);if(status.contains("CANCEL"))return"Cancelled";if(p.getBalanceAmount()<=.01)return"Paid";if(p.getDueDate()==null)return"Not set";long d=java.time.temporal.ChronoUnit.DAYS.between(LocalDate.now(),p.getDueDate());return d<0?"Overdue by "+Math.abs(d)+" days":d==0?"Due today":"Due in "+d+" days";}private String fmt(double v){return money.format(v).replace("₹","₹ ");}private String s(String v){return v==null?"":v;}private String user(){return SessionService.current()==null?"System":SessionService.current().getFullName();}private void info(String m){org.example.util.ToastManager.success(tablePurchase,"Completed",m);}private void error(Throwable e){e.printStackTrace();String message=e.getMessage()==null?"Operation failed":e.getMessage();org.example.util.ModernDialog.error(tablePurchase,"Operation failed","Something went wrong",message);}


    private void applyRangeButtonIcons() {
        applyIcon(btnTodayRange,"calendar"); applyIcon(btnYesterdayRange,"history");
        applyIcon(btnSevenDaysRange,"calendar"); applyIcon(btnThirtyDaysRange,"calendar"); applyIcon(btnCustomRange,"calendar");
    }
    private void applyIcon(ButtonBase b,String semantic){ if(b!=null){b.setGraphic(IconFactory.compactIcon(semantic,15));b.getProperties().put("erp-icon-preserve",true);} }

    private void configureExplicitTableHeaderIcons() {
        IconFactory.applyTableHeaderIcon(colInvoice, "document");
        IconFactory.applyTableHeaderIcon(colDate, "calendar");
        IconFactory.applyTableHeaderIcon(colSupplier, "supplier");
        IconFactory.applyTableHeaderIcon(colMobile, "phone");
        IconFactory.applyTableHeaderIcon(colAmount, "currency");
        IconFactory.applyTableHeaderIcon(colPaid, "complete");
        IconFactory.applyTableHeaderIcon(colBalance, "payment");
        IconFactory.applyTableHeaderIcon(colDue, "reminder");
        IconFactory.applyTableHeaderIcon(colStatus, "status");
        IconFactory.applyTableHeaderIcon(colMail, "email");
        IconFactory.applyTableHeaderIcon(colWhatsapp, "whatsapp");
        IconFactory.applyTableHeaderIcon(colActions, "actions");
    }

 @Override public void onScreenShown(boolean reusedFromCache){if(!reusedFromCache||ScreenRefreshPolicy.shouldRefresh("purchase-register",ScreenRefreshPolicy.Mode.WHEN_STALE))refresh();}
 @Override public void onScreenHidden(){UiTaskExecutor.cancel("purchase-register-load");searchDebouncer.cancel();}
 private record PurchaseLoad(List<Purchase> rows,Map<Integer,Boolean> whatsapp){}
}
