package org.example.controller;

import org.example.util.BusinessClock;
import org.example.navigation.NavigationManager;

import org.example.util.OwnedAlert;
import org.example.util.OwnedDialog;
import org.example.util.OwnedTextInputDialog;


import org.example.util.IconFactory;
import org.example.util.UiTaskExecutor;
import org.example.util.RegisterPageState;
import org.example.util.RegisterUiSupport;
import org.example.util.AttachmentPreviewSupport;
import com.itextpdf.kernel.pdf.PdfDocument;import com.itextpdf.kernel.pdf.PdfWriter;import com.itextpdf.layout.Document;import com.itextpdf.layout.element.Paragraph;import com.itextpdf.layout.element.Table;
import javafx.beans.property.*;import javafx.fxml.FXML;import javafx.geometry.Pos;import javafx.scene.chart.*;import javafx.scene.control.*;import javafx.scene.layout.*;import javafx.stage.FileChooser;
import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.example.config.ConfigManager;import org.example.config.WorkspaceManager;import org.example.api.quotation.QuotationApiClient;import org.example.api.support.SupportApiClient;import org.example.api.insights.InsightsApiClient;import org.example.service.*;
import java.io.*;import java.nio.file.*;import java.text.NumberFormat;import java.time.LocalDate;import java.util.*;

public class QuotationController implements org.example.navigation.ScreenLifecycle {
 @FXML private Label lblTotalValue,lblTotalCount,lblPendingValue,lblPendingCount,lblAcceptedValue,lblAcceptedCount,lblExpiredValue,lblExpiredCount,lblConversion,lblAverage,lblFilteredSummary;
 private Button btnSaveView; private MenuButton savedViewsMenu;
 @FXML private TextField txtSearch,txtNumber,txtAmountFrom,txtAmountTo; @FXML private ComboBox<String> cmbCustomer,cmbStatus,cmbSalesperson,cmbFollowUp,cmbSource; @FXML private DatePicker dpFrom,dpTo,dpValid; @FXML private ToggleButton btnAdvanced; @FXML private GridPane advancedFilters; @FXML private FlowPane activeFilterChips; 
 @FXML private Button btnNewQuotation,btnReset,btnRefresh,btnApplyFilters,btnExportExcel,btnExportPdf,btnAllDatesRange,btnTodayRange,btnYesterdayRange,btnSevenDaysRange,btnThirtyDaysRange,btnCustomRange,btnPreviewAttachment,btnRemoveAttachment,btnOpenConvertedSale,btnPrevPage,btnNextPage;
 @FXML private StackPane pageIcon,quotationHeaderSearchIcon,totalMetricIcon,pendingMetricIcon,acceptedMetricIcon,expiredMetricIcon,conversionMetricIcon,averageMetricIcon;
 @FXML private TableView<QuoteRow> table; @FXML private TableColumn<QuoteRow,String> colNo,colDate,colCustomer,colValid,colStatus,colFollowUp,colConverted,colSalesperson,colCreatedBy; @FXML private TableColumn<QuoteRow,Number> colAmount; @FXML private TableColumn<QuoteRow,Void> colActions;
 @FXML private LineChart<String,Number> trendChart; @FXML private PieChart statusChart; @FXML private SplitPane mainSplit; @FXML private VBox detailDrawer; @FXML private Label lblDetailNo,lblDetailDate,lblDetailStatus,lblDetailCustomer,lblDetailContact,lblDetailAmount,lblDetailDiscount,lblDetailValid,lblDetailFollow,lblDetailConverted,lblDetailAttachment;
 private final NumberFormat money=NumberFormat.getCurrencyInstance(Locale.of("en", "IN")); private boolean explicitRefreshPending; private final QuotationApiClient quotationApi=new QuotationApiClient(); private final LookupService lookupService=new LookupService(); private final SupportApiClient supportApi=new SupportApiClient(); private final InsightsApiClient insightsApi=new InsightsApiClient(); private List<QuoteRow> all=List.of(),filtered=List.of(); private QuoteRow selected; private final RegisterPageState pageState=new RegisterPageState(); private static final int PAGE_SIZE=25;
 private boolean applyingSavedView;
 private String pendingSavedViewName;
 @FXML public void initialize(){org.example.util.RegisterColumnPreferences.install(table,"QUOTATION_REGISTER");
        applyButtonIcon(btnReset,"reset");
        applyButtonIcon(btnRefresh,"refresh");RegisterUiSupport.configureHeaderSearch(txtSearch,quotationHeaderSearchIcon,"Search quotation, customer or source...");
        configureUiIcons();refreshShortcutLabel();configureEmptyState();colNo.setCellValueFactory(v->v.getValue().no);colDate.setCellValueFactory(v->v.getValue().date);colCustomer.setCellValueFactory(v->v.getValue().customer);colValid.setCellValueFactory(v->v.getValue().valid);colStatus.setCellValueFactory(v->v.getValue().status);colFollowUp.setCellValueFactory(v->v.getValue().followUp);colConverted.setCellValueFactory(v->v.getValue().converted);colSalesperson.setCellValueFactory(v->v.getValue().salesperson);colCreatedBy.setCellValueFactory(v->v.getValue().createdBy);colAmount.setCellValueFactory(v->v.getValue().amount);colAmount.setCellFactory(c->new TableCell<>(){protected void updateItem(Number v,boolean e){super.updateItem(v,e);setText(e||v==null?null:fmt(v.doubleValue()));setAlignment(Pos.CENTER_RIGHT);}});colStatus.setCellFactory(c->new TableCell<>(){protected void updateItem(String v,boolean e){super.updateItem(v,e);setText(e?null:v);getStyleClass().removeAll("pill-success","pill-warning","pill-danger","pill-neutral");if(!e)getStyleClass().add("ACCEPTED".equals(v)?"pill-success":"EXPIRED".equals(v)||"REJECTED".equals(v)?"pill-danger":"SENT".equals(v)?"pill-success":"pill-warning");}});setupActions();setupFilters();dpFrom.setValue(BusinessClock.today().minusMonths(6));dpTo.setValue(BusinessClock.today());dpValid.setValue(null);if(org.example.util.PlatformUiSupport.isMac()){if(trendChart!=null){trendChart.setManaged(false);trendChart.setVisible(false);}if(statusChart!=null){statusChart.setManaged(false);statusChart.setVisible(false);}}detailDrawer.setMinWidth(390);detailDrawer.setPrefWidth(410);detailDrawer.setMaxWidth(440);decorateQuotationDrawer();RegisterUiSupport.hideDrawer(detailDrawer,mainSplit,table);org.example.util.OperationalUiSupport.installEscapeClose(mainSplit,()->detailDrawer!=null&&detailDrawer.isVisible(),this::closeDetails);table.setRowFactory(tv->{TableRow<QuoteRow> row=new TableRow<>();row.setOnMouseClicked(event->{if(event.getButton()!=javafx.scene.input.MouseButton.PRIMARY||event.getClickCount()!=1||row.isEmpty()||RegisterUiSupport.isInteractiveTableTarget(event.getPickResult().getIntersectedNode(),row))return;QuoteRow clicked=row.getItem();if(detailDrawer.isVisible()&&selected==clicked)closeDetails();else{table.getSelectionModel().select(clicked);showDetails(clicked);}event.consume();});return row;});txtSearch.textProperty().addListener((o,a,b)->applyFilters());refresh();}

 @FXML private void showAllDates(){dpFrom.setValue(null);dpTo.setValue(null);applyFilters();}
 @FXML private void showToday(){applyDateRange(BusinessClock.today(),BusinessClock.today());}
 @FXML private void showYesterday(){LocalDate d=BusinessClock.today().minusDays(1);applyDateRange(d,d);}
 @FXML private void showSevenDays(){applyDateRange(BusinessClock.today().minusDays(6),BusinessClock.today());}
 @FXML private void showThirtyDays(){applyDateRange(BusinessClock.today().minusDays(29),BusinessClock.today());}
 @FXML private void showCustomRange(){dpFrom.requestFocus();}
 private void applyDateRange(LocalDate from,LocalDate to){dpFrom.setValue(from);dpTo.setValue(to);applyFilters();}
 private void setupFilters(){cmbStatus.getItems().setAll("All","DRAFT","SENT","ACCEPTED","REJECTED","EXPIRED");cmbStatus.setValue("All");cmbFollowUp.getItems().setAll("All","Overdue","Today","Next 7 Days","Not Set");cmbFollowUp.setValue("All");refreshSourceFilter();cmbSource.setOnShowing(e->refreshSourceFilter());cmbSalesperson.getItems().setAll("All");cmbSalesperson.setValue("All");org.example.util.PartySearchUi.install(cmbCustomer,"CUSTOMER","All customers","quotation-register-customer-search");cmbCustomer.valueProperty().addListener((o,a,b)->{if(!applyingSavedView&&!org.example.util.PartySearchUi.isInternalUpdate(cmbCustomer))applyFilters();});cmbStatus.valueProperty().addListener((o,a,b)->applyFilters());dpFrom.valueProperty().addListener((o,a,b)->applyFilters());dpTo.valueProperty().addListener((o,a,b)->applyFilters());txtNumber.textProperty().addListener((o,a,b)->applyFilters());if(advancedFilters!=null){advancedFilters.setVisible(false);advancedFilters.setManaged(false);}if(btnAdvanced!=null){btnAdvanced.setSelected(false);btnAdvanced.setVisible(false);btnAdvanced.setManaged(false);}}
 @FXML public void refresh(){loadPage();}
 @FXML private void refreshWithFeedback(){explicitRefreshPending=true;if(btnRefresh!=null){btnRefresh.setDisable(true);btnRefresh.setText("Refreshing...");}loadPage();}
 private void finishExplicitRefresh(boolean success){if(!explicitRefreshPending)return;explicitRefreshPending=false;if(btnRefresh!=null){btnRefresh.setDisable(false);btnRefresh.setText("Refresh");}if(success)org.example.util.ToastManager.info(table,"Refreshed","Quotation Register is up to date.");}

 private void refreshSourceFilter(){String selected=cmbSource==null?null:cmbSource.getValue();List<String> sources=new ArrayList<>();sources.add("All");try{sources.addAll(lookupService.getValuesByCategoryCode("QUOTATION_SOURCE"));}catch(Exception ignored){}List<String> values=sources.stream().filter(Objects::nonNull).map(String::trim).filter(v->!v.isBlank()).distinct().toList();cmbSource.getItems().setAll(values);if(selected!=null&&values.contains(selected))cmbSource.setValue(selected);else cmbSource.setValue("All");}
 private void loadPage(){org.example.util.OperationalUiSupport.showLoading(table,"Loading quotations…");int requested=pageState.currentPage();String customer=cmbCustomer==null?"":safe(cmbCustomer.getValue()),status=cmbStatus==null?"":safe(cmbStatus.getValue()),salesperson=cmbSalesperson==null?"":safe(cmbSalesperson.getValue()),follow=cmbFollowUp==null?"":safe(cmbFollowUp.getValue()),source=cmbSource==null?"":safe(cmbSource.getValue());UiTaskExecutor.submitLatest("quotation-load",()->quotationApi.page(requested,PAGE_SIZE,safe(txtSearch.getText()),safe(txtNumber.getText()),customer,status,str(dpFrom.getValue()),str(dpTo.getValue()),str(dpValid.getValue()),salesperson,safe(txtAmountFrom.getText()),safe(txtAmountTo.getText()),follow,source),this::applyQuotationPage,failure->{pendingSavedViewName=null;finishExplicitRefresh(false);org.example.util.OperationalUiSupport.showError(table,"Quotation register could not load",failure);error(asException(failure));});}
 private void applyQuotationPage(QuotationApiClient.Page page){pageState.runApplying(()->{long started=System.nanoTime();all=(page==null||page.rows()==null)?List.of():page.rows().stream().map(QuoteRow::new).toList();filtered=all;pageState.apply(page==null?0:page.page(),page==null?0:page.totalPages(),page==null?0:page.totalRows());String selectedCustomer=cmbCustomer.getValue(),selectedSalesperson=cmbSalesperson.getValue();org.example.util.PartySearchUi.preserveSelection(cmbCustomer,selectedCustomer,"All customers");cmbSalesperson.getItems().setAll("All");if(page!=null&&page.salespersons()!=null)cmbSalesperson.getItems().addAll(page.salespersons());cmbSalesperson.setValue(selectedSalesperson!=null&&cmbSalesperson.getItems().contains(selectedSalesperson)?selectedSalesperson:"All");table.getItems().setAll(all);if(all.isEmpty())org.example.util.OperationalUiSupport.showEmpty(table,"No quotations found","Adjust the filters or create a new Quotation.");applyStats(page==null?null:page.metrics());updatePageInfo(page==null?0:page.filteredAmount());renderChips();openLinkedRecordIfRequested();if(!org.example.util.PlatformUiSupport.isMac())javafx.application.Platform.runLater(()->updateCharts(page==null?null:page.metrics()));org.example.util.ScreenRefreshPolicy.markRefreshed("quotations");finishExplicitRefresh(true);notifyAppliedSavedView();long ms=(System.nanoTime()-started)/1_000_000L;if(ms>=20)org.example.util.PerformanceMonitor.event("controller-phase","quotation-page-apply | "+ms+" ms | rows="+all.size()+" | total="+pageState.totalRows());});}
 private void updatePageInfo(double filteredAmount){lblFilteredSummary.setText(pageState.totalRows()==0?"0 quotations":"Showing "+pageState.firstRow(PAGE_SIZE)+"–"+pageState.lastRow(PAGE_SIZE,all.size())+" of "+pageState.totalRows()+" • "+fmt(filteredAmount)+" • Page "+(pageState.currentPage()+1)+" / "+Math.max(1,pageState.totalPages()));RegisterUiSupport.updatePageNavigation(pageState,btnPrevPage,btnNextPage);}
 private void openLinkedRecordIfRequested(){LinkedRecordContext.Target target=LinkedRecordContext.consume("QUOTATION");if(target==null)return;QuoteRow quote=all.stream().filter(x->(target.recordId()!=null&&x.id==target.recordId())||(!target.documentNo().isBlank()&&target.documentNo().equalsIgnoreCase(x.no.get()))).findFirst().orElse(null);if(quote!=null){selectLinked(quote,target);return;}if(target.recordId()!=null){UiTaskExecutor.submitLatest("quotation-linked-record",()->quotationApi.quote(target.recordId()),dto->selectLinked(new QuoteRow(dto),target),failure->info("The linked Quotation is no longer available"+(target.documentNo().isBlank()?".":": "+target.documentNo())));return;}if(!target.documentNo().isBlank()){UiTaskExecutor.submitLatest("quotation-linked-record",()->quotationApi.page(0,10,"",target.documentNo(),"","","","","","","","","",""),pg->{if(pg.rows()==null||pg.rows().isEmpty()){info("The linked Quotation is no longer available: "+target.documentNo());return;}selectLinked(new QuoteRow(pg.rows().getFirst()),target);},failure->info("The linked Quotation is no longer available: "+target.documentNo()));}}
 private void selectLinked(QuoteRow quote,LinkedRecordContext.Target target){table.getSelectionModel().select(quote);if(!table.getItems().contains(quote))table.getItems().setAll(quote);table.scrollTo(quote);org.example.navigation.DeepLinkSupport.pulse(table);showDetails(quote);org.example.util.PerformanceMonitor.event("linked-navigation","QUOTATION -> "+quote.no.get()+" | source="+target.source());}
 @Override public void onScreenShown(boolean reused){refreshShortcutLabel();refreshSourceFilter();org.example.util.OperationalUiSupport.focusWorkArea(table);if(!reused)return;if(org.example.util.ScreenRefreshPolicy.shouldRefresh("quotations",org.example.util.ScreenRefreshPolicy.Mode.WHEN_STALE,java.time.Duration.ofSeconds(60)))refresh();}

 private void refreshShortcutLabel(){org.example.shortcut.ShortcutRegistry.bindLabel(btnNewQuotation,org.example.shortcut.ShortcutRegistry.Action.NEW_QUOTATION,"New Quotation");}
 @Override public void onScreenHidden(){org.example.util.UiTaskExecutor.cancelPrefix("quotation-");}
 // Filters may fire while dropdowns are still being populated; null means "All".
 @FXML public void applyFilters(){if(applyingSavedView)return;pageState.runWhenIdle(()->{if(applyingSavedView)return;pageState.reset();loadPage();});}
 @FXML private void previousPage(){if(pageState.previous())loadPage();}
 @FXML private void nextPage(){if(pageState.next())loadPage();}
 private boolean all(ComboBox<String> box){String value=box.getValue();return value==null||value.startsWith("All");}
 private void applyStats(QuotationApiClient.Metrics m){if(m==null)return;lblTotalValue.setText(fmt(m.totalValue()));lblTotalCount.setText(m.totalCount()+" quotations");lblPendingValue.setText(fmt(m.pendingValue()));lblPendingCount.setText(m.pendingCount()+" quotations");lblAcceptedValue.setText(fmt(m.acceptedValue()));lblAcceptedCount.setText(m.acceptedCount()+" quotations");lblExpiredValue.setText(fmt(m.expiredValue()));lblExpiredCount.setText(m.expiredCount()+" quotations");lblConversion.setText(String.format("%.1f%%",m.conversionRate()));lblAverage.setText(fmt(m.average()));}
 private void updateCharts(QuotationApiClient.Metrics m){if(m==null||trendChart==null||statusChart==null)return;XYChart.Series<String,Number> series=new XYChart.Series<>();for(var point:m.trend()==null?List.<QuotationApiClient.MetricPoint>of():m.trend())series.getData().add(new XYChart.Data<>(point.label(),point.value()));trendChart.getData().setAll(series);statusChart.getData().setAll((m.statuses()==null?List.<QuotationApiClient.MetricPoint>of():m.statuses()).stream().map(x->new PieChart.Data(x.label(),x.value())).toList());}
private void setupActions(){colActions.setCellFactory(c->new TableCell<>(){final MenuButton m=new MenuButton("Actions");{add("View","view",e->showDetails(row()));add("Activity Timeline","history",e->{QuoteRow q=row();if(q!=null)org.example.util.ActivityTimelineDialog.show(table,"QUOTATION",q.id,q.no.get());});add("Edit","edit",e->edit(row()));add("View PDF","pdf",e->openPdf(row()));add("View / Download Excel","excel",e->openExcel(row()));add("Send Email","email",e->sendEmail(row()));add("Send WhatsApp","whatsapp",e->sendWhatsapp(row()));add("Create Follow Up","reminder",e->followUp(row()));add("Convert to Sale","sale",e->convert(row()));add("Duplicate","copy",e->duplicate(row()));add("Delete","delete",e->delete(row()));m.getStyleClass().add("row-actions");m.setGraphic(IconFactory.compactIcon("actions",16));m.setText("Actions");m.setContentDisplay(ContentDisplay.LEFT);m.setGraphicTextGap(6);m.setTooltip(new Tooltip("Actions"));m.getProperties().put("erp-icon-preserve",true);IconFactory.decorateActionMenu(m);}private QuoteRow row(){int index=getIndex();return index<0||index>=getTableView().getItems().size()?null:getTableView().getItems().get(index);}private void add(String t,String semantic,javafx.event.EventHandler<javafx.event.ActionEvent>h){MenuItem i=new MenuItem(t);i.setGraphic(IconFactory.compactIcon(semantic,16));i.setOnAction(h);m.getItems().add(i);}protected void updateItem(Void v,boolean e){super.updateItem(v,e);setGraphic(e?null:m);setAlignment(Pos.CENTER);}});}
 @FXML private void newQuotation(){QuotationEditorContext.open(null);org.example.navigation.NavigationManager.getInstance().loadPage("/fxml/pages/QuotationEditor.fxml");}
 private void edit(QuoteRow q){if(q==null)return;if(q.converted.get()!=null&&!q.converted.get().isBlank()){info("Converted quotations are read-only. Duplicate the quotation if a new revision is required.");return;}QuotationEditorContext.open(q.id);org.example.navigation.NavigationManager.getInstance().loadPage("/fxml/pages/QuotationEditor.fxml");}

 private void decorateQuotationDrawer(){if(detailDrawer==null)return;decorateQuotationNode(detailDrawer);applyQuoteValueIcon(lblDetailNo,"quotation");applyQuoteValueIcon(lblDetailDate,"calendar");applyQuoteValueIcon(lblDetailCustomer,"customer");applyQuoteValueIcon(lblDetailContact,"user");applyQuoteValueIcon(lblDetailAmount,"currency");applyQuoteValueIcon(lblDetailDiscount,"discount");applyQuoteValueIcon(lblDetailValid,"calendar");applyQuoteValueIcon(lblDetailFollow,"reminder");applyQuoteValueIcon(lblDetailConverted,"sale");}
 private void decorateQuotationNode(javafx.scene.Node node){if(node instanceof Label l&&l.getGraphic()==null){String sem=quotationDrawerSemantic(l.getText());if(sem!=null){l.setGraphic(IconFactory.compactIcon(sem,14));l.setGraphicTextGap(6);l.getProperties().put("erp-icon-preserve",true);}}if(node instanceof ButtonBase b&&b.getGraphic()==null){String sem=quotationDrawerSemantic(b.getText());if(sem!=null){b.setGraphic(IconFactory.compactIcon(sem,14));b.setGraphicTextGap(6);b.getProperties().put("erp-icon-preserve",true);}}if(node instanceof javafx.scene.Parent p)for(javafx.scene.Node c:p.getChildrenUnmodifiable())decorateQuotationNode(c);}
 private void applyQuoteValueIcon(Label l,String sem){if(l!=null&&l.getGraphic()==null){l.setGraphic(IconFactory.compactIcon(sem,15));l.setGraphicTextGap(7);l.getProperties().put("erp-icon-preserve",true);}}
 private String quotationDrawerSemantic(String text){String t=safe(text).toLowerCase(java.util.Locale.ROOT);if(t.contains("quotation"))return"quotation";if(t.contains("amount"))return"currency";if(t.contains("discount"))return"discount";if(t.contains("valid"))return"calendar";if(t.contains("follow"))return"reminder";if(t.contains("converted")||t.contains("convert"))return"sale";if(t.contains("edit"))return"edit";if(t.equals("pdf")||t.contains("pdf"))return"pdf";if(t.contains("email"))return"email";if(t.contains("whatsapp"))return"whatsapp";if(t.contains("notes")||t.contains("save notes"))return"document";if(t.contains("close"))return"cancel";return null;}

 private String quotationStatusState(String status){String v=safe(status).toUpperCase(java.util.Locale.ROOT);return "ACCEPTED".equals(v)||"SENT".equals(v)?"success":"EXPIRED".equals(v)||"REJECTED".equals(v)?"danger":"warning";}
 private String quotationStatusSemantic(String status){String v=safe(status).toUpperCase(java.util.Locale.ROOT);if("ACCEPTED".equals(v))return"complete";if("SENT".equals(v))return"sent";if("EXPIRED".equals(v)||"REJECTED".equals(v))return"cancel";if("DRAFT".equals(v))return"draft";return"status";}
 private void showDetails(QuoteRow q){selected=q;RegisterUiSupport.showDrawer(detailDrawer,mainSplit,.8);lblDetailNo.setText(q.no.get());lblDetailDate.setText(q.date.get());lblDetailStatus.setText(q.status.get());lblDetailStatus.setGraphic(IconFactory.statusIcon(quotationStatusSemantic(q.status.get()),quotationStatusState(q.status.get())));lblDetailStatus.setGraphicTextGap(6);lblDetailCustomer.setText(q.customer.get());lblDetailContact.setText(q.phone+"\n"+q.email+"\n"+q.gstin);lblDetailAmount.setText(fmt(q.amount.get()));lblDetailDiscount.setText(fmt(q.discount));lblDetailValid.setText(q.valid.get());lblDetailFollow.setText(q.followUp.get());boolean converted=q.converted.get()!=null&&!q.converted.get().isBlank();lblDetailConverted.setText(converted?q.converted.get():"—");if(btnOpenConvertedSale!=null)btnOpenConvertedSale.setDisable(!converted);updateAttachmentActions(q);}
 private void updateAttachmentActions(QuoteRow q){boolean attached=q!=null&&q.attachment!=null&&!q.attachment.isBlank();if(lblDetailAttachment!=null)lblDetailAttachment.setText(attached?attachmentDisplayName(q.attachment):"No document attached");if(btnPreviewAttachment!=null)btnPreviewAttachment.setDisable(!attached);if(btnRemoveAttachment!=null)btnRemoveAttachment.setDisable(!attached);}
 @FXML private void closeDetails(){selected=null;detailDrawer.setMinWidth(390);detailDrawer.setPrefWidth(410);detailDrawer.setMaxWidth(440);RegisterUiSupport.hideDrawer(detailDrawer,mainSplit,table);table.getSelectionModel().clearSelection();}private QuoteRow req(){if(selected==null)new OwnedAlert(Alert.AlertType.WARNING,"Select a quotation first.").showAndWait();return selected;}
 @FXML private void openConvertedSale(){QuoteRow q=req();if(q==null||safe(q.converted.get()).isBlank()){info("This quotation is not linked to a Sale yet.");return;}LinkedRecordContext.open("SALE",null,q.converted.get(),"VIEW","Quotation "+q.no.get());NavigationManager.getInstance().loadPage("/fxml/pages/SalesList.fxml");}
 @FXML private void editSelected(){QuoteRow q=req();if(q!=null)edit(q);}@FXML private void pdfSelected(){QuoteRow q=req();if(q!=null)openPdf(q);}@FXML private void emailSelected(){QuoteRow q=req();if(q!=null)sendEmail(q);}@FXML private void whatsappSelected(){QuoteRow q=req();if(q!=null)sendWhatsapp(q);}@FXML private void convertSelected(){QuoteRow q=req();if(q!=null)convert(q);}@FXML private void followUpSelected(){QuoteRow q=req();if(q!=null)followUp(q);} /** Returns the same branded quotation used by download, email and WhatsApp actions. */
 private Path quotePdf(QuoteRow q)throws Exception{return ManagedInvoicePdfService.quotation(q.no.get());}
 private void openPdf(QuoteRow q){try{java.awt.Desktop.getDesktop().open(quotePdf(q).toFile());log(q.id,"PDF_OPENED",q.no.get());}catch(Exception e){error(e);}}
 private void openExcel(QuoteRow q){if(q==null)return;try{java.awt.Desktop.getDesktop().open(org.example.documentstudio.service.ExcelOutputService.generate(org.example.documentstudio.model.DocumentType.QUOTATION,q.no.get()).toFile());log(q.id,"EXCEL_OPENED",q.no.get());}catch(Exception e){error(e);}}
 private void sendEmail(QuoteRow q){try{if(q.email.isBlank())throw new IllegalStateException("Customer email is missing");EmailService.send(q.email,"Quotation "+q.no.get(),"Please find our quotation attached.",quotePdf(q));quotationApi.markSent(q.id,"EMAIL");comm(q,"EMAIL",q.email,"SENT",null);refresh();}catch(Exception e){comm(q,"EMAIL",q.email,"FAILED",e.getMessage());error(e);}}
 @FXML private void attachSelected(){QuoteRow q=req();if(q==null)return;FileChooser chooser=new FileChooser();chooser.setTitle("Attach quotation document");chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Documents","*.pdf","*.png","*.jpg","*.jpeg","*.doc","*.docx","*.xls","*.xlsx","*.csv","*.txt"));File file=chooser.showOpenDialog(table.getScene().getWindow());if(file==null)return;Path path=file.toPath();UiTaskExecutor.submitAction("quotation-attachment-upload-"+q.id,()->supportApi.uploadDocumentAttachment("QUOTATION",q.id,path),attachment->{q.attachment=attachment;updateAttachmentActions(q);log(q.id,"ATTACHMENT","Quotation attachment added/replaced");success("Quotation attachment saved.");},failure->error(asException(failure)));}
 @FXML private void previewAttachmentSelected(){QuoteRow q=req();if(q==null)return;if(q.attachment==null||q.attachment.isBlank()){info("No quotation attachment is available.");updateAttachmentActions(q);return;}UiTaskExecutor.submitLatest("quotation-attachment-preview-"+q.id,()->materializeQuotationAttachment(supportApi.documentAttachment("QUOTATION",q.id)),target->{try{java.awt.Desktop.getDesktop().open(target.toFile());}catch(Exception e){error(e);}},failure->error(asException(failure)));}
 private Path materializeQuotationAttachment(SupportApiClient.DownloadedAttachment d)throws Exception{return AttachmentPreviewSupport.materializeRequired(d,"quotation-attachment");}
 @FXML private void removeAttachmentSelected(){QuoteRow q=req();if(q==null)return;if(q.attachment==null||q.attachment.isBlank()){info("No quotation attachment is available.");updateAttachmentActions(q);return;}if(!confirm("Remove the quotation attachment?"))return;UiTaskExecutor.submitAction("quotation-attachment-delete-"+q.id,()->{supportApi.deleteDocumentAttachment("QUOTATION",q.id);return true;},ignored->{q.attachment="";updateAttachmentActions(q);log(q.id,"ATTACHMENT","Quotation attachment removed");success("Quotation attachment removed.");},failure->error(asException(failure)));}
 private String attachmentDisplayName(String value){if(value==null||value.isBlank())return "No document attached";String normalized=value.replace('\\','/');int i=normalized.lastIndexOf('/');return i>=0&&i+1<normalized.length()?normalized.substring(i+1):normalized;}

 private void sendWhatsapp(QuoteRow q){try{String phone=q.phone.replaceAll("\\D","");if(phone.length()==10)phone="91"+phone;if(phone.isBlank())throw new IllegalStateException("Customer mobile number is missing");WhatsappService.openWhatsappWithMessage(phone,PaymentMessageService.quotationMessage(q.id),quotePdf(q),PaymentMessageService.configuredQrPath());quotationApi.markSent(q.id,"WHATSAPP");comm(q,"WHATSAPP",phone,"SENT",null);refresh();success("WhatsApp is ready. The quotation PDF and configured UPI QR are on the clipboard for attachment.");}catch(Exception e){error(e);}}
 private void followUp(QuoteRow q){if(q==null)return;if(q.converted.get()!=null&&!q.converted.get().isBlank()){info("Converted quotations are read-only. Duplicate the quotation if a new follow-up/revision is required.");return;}DatePicker date=new DatePicker(q.followDate==null?BusinessClock.today().plusDays(1):q.followDate);Dialog<ButtonType>d=new OwnedDialog<>();d.setTitle("Create Follow Up");TextArea notes=new TextArea("Follow up for "+q.no.get());VBox box=new VBox(8,new Label("Follow-up date"),date,new Label("Notes"),notes);d.getDialogPane().setContent(box);d.getDialogPane().getButtonTypes().addAll(ButtonType.OK,ButtonType.CANCEL);d.showAndWait().filter(b->b==ButtonType.OK).ifPresent(b->{String due=date.getValue().toString(),text=notes.getText();UiTaskExecutor.submitAction("quotation-followup-"+q.id,()->{quotationApi.followUp(q.id,due,text);return true;},ignored->{org.example.util.ToastManager.success(table,"Follow-up saved",q.no.get()+" follow-up was scheduled successfully.");refresh();},failure->error(asException(failure)));});}
 private void convert(QuoteRow q){if(q.converted.get()!=null&&!q.converted.get().isBlank()){info("Already converted to "+q.converted.get());return;}String state=safe(q.status.get()).toUpperCase(java.util.Locale.ROOT);if("REJECTED".equals(state)||"EXPIRED".equals(state)){info("A "+state.toLowerCase(java.util.Locale.ROOT)+" quotation cannot be converted to a Sale.");return;}if(!confirm("Convert "+q.no.get()+" to a sales invoice and reduce stock?"))return;String actor=user();UiTaskExecutor.submitSerial("quotation-convert-"+q.id,()->quotationApi.convert(q.id,actor),invoice->{log(q.id,"CONVERTED",invoice);refresh();org.example.util.ToastManager.success(table,"Sale created","Sales invoice "+invoice+" created.");},failure->error(asException(failure)));}
 private void duplicate(QuoteRow q){if(!confirm("Duplicate "+q.no.get()+"?"))return;String actor=user();UiTaskExecutor.submitAction("quotation-duplicate-"+q.id,()->{quotationApi.duplicate(q.id,actor);return true;},ignored->{org.example.util.ToastManager.success(table,"Quotation duplicated",q.no.get()+" was duplicated successfully.");refresh();},failure->error(asException(failure)));}
 private void delete(QuoteRow q){if("ACCEPTED".equalsIgnoreCase(q.status.get())){info("Accepted quotations cannot be deleted. Convert, duplicate, or retain the quotation for audit history.");return;}if(!confirm("Delete "+q.no.get()+"?"))return;UiTaskExecutor.submitAction("quotation-delete-"+q.id,()->{quotationApi.delete(q.id);return true;},ignored->{org.example.util.ToastManager.success(table,"Quotation deleted",q.no.get()+" was deleted successfully.");refresh();closeDetails();},failure->error(asException(failure)));}
 @FXML private void toggleAdvanced(){advancedFilters.setManaged(btnAdvanced.isSelected());advancedFilters.setVisible(btnAdvanced.isSelected());}@FXML private void resetFilters(){txtSearch.clear();txtNumber.clear();txtAmountFrom.clear();txtAmountTo.clear();dpFrom.setValue(BusinessClock.today().minusMonths(6));dpTo.setValue(BusinessClock.today());dpValid.setValue(null);cmbCustomer.setValue("All customers");cmbStatus.setValue("All");cmbSalesperson.setValue("All");cmbFollowUp.setValue("All");cmbSource.setValue("All");applyFilters();}
 private void renderChips(){activeFilterChips.getChildren().clear();chip("Status",cmbStatus.getValue());chip("Customer",cmbCustomer.getValue());chip("Follow Up",cmbFollowUp.getValue());chip("Source",cmbSource.getValue());}private void chip(String n,String v){if(v==null||v.startsWith("All"))return;Label l=new Label(n+": "+v);l.getStyleClass().add("filter-chip");activeFilterChips.getChildren().add(l);}
 @FXML private void saveCurrentView(){TextInputDialog d=new OwnedTextInputDialog();d.setHeaderText("Save current quotation filters");d.setContentText("View name:");d.showAndWait().filter(x->!x.isBlank()).ifPresent(name->{String data=String.join("|",safe(txtNumber.getText()),safe(cmbCustomer.getValue()),str(dpFrom.getValue()),str(dpTo.getValue()),safe(cmbStatus.getValue()),str(dpValid.getValue()),safe(cmbSalesperson.getValue()),safe(txtAmountFrom.getText()),safe(txtAmountTo.getText()),safe(cmbFollowUp.getValue()),safe(cmbSource.getValue()),safe(txtSearch.getText()));Integer uid=SessionService.current()==null?null:SessionService.current().getId();UiTaskExecutor.submitAction("quotation-save-view",()->{supportApi.saveView(uid,"QUOTATION_REGISTER",name,data);return true;},ignored->{success("Saved view created.");},failure->error(asException(failure)));});}
 private MenuItem savedViewPlaceholder(){MenuItem i=new MenuItem("No saved views");i.getStyleClass().add("register-saved-view-item");i.setDisable(true);return i;}
 private void loadSavedViews(){Integer uid=SessionService.current()==null?null:SessionService.current().getId();UiTaskExecutor.submitLatest("quotation-saved-views",()->supportApi.savedViews("QUOTATION_REGISTER",uid),views->{savedViewsMenu.getItems().clear();for(SupportApiClient.SavedView v:views){MenuItem i=new MenuItem(v.name());i.getStyleClass().add("register-saved-view-item");i.setOnAction(e->applySaved(v.name(),v.data()));savedViewsMenu.getItems().add(i);}if(savedViewsMenu.getItems().isEmpty())savedViewsMenu.getItems().add(savedViewPlaceholder());},failure->{savedViewsMenu.getItems().setAll(savedViewPlaceholder());org.example.util.PerformanceMonitor.event("quotation-saved-views",String.valueOf(failure.getMessage()));});}
private void applySaved(String name,String d){String[]x=d==null?new String[0]:d.split("\\|",-1);if(x.length==0){info("The saved view is empty and cannot be applied.");return;}applyingSavedView=true;try{txtNumber.setText(part(x,0));String customer=part(x,1);org.example.util.PartySearchUi.preserveSelection(cmbCustomer,customer.isBlank()?"All customers":customer,"All customers");dpFrom.setValue(parseDate(part(x,2)));dpTo.setValue(parseDate(part(x,3)));selectSaved(cmbStatus,part(x,4),"All");dpValid.setValue(parseDate(part(x,5)));selectSaved(cmbSalesperson,part(x,6),"All");txtAmountFrom.setText(part(x,7));txtAmountTo.setText(part(x,8));selectSaved(cmbFollowUp,part(x,9),"All");selectSaved(cmbSource,part(x,10),"All");txtSearch.setText(part(x,11));pageState.reset();pendingSavedViewName=name;}finally{applyingSavedView=false;}renderChips();loadPage();}
private void notifyAppliedSavedView(){if(pendingSavedViewName==null)return;String name=pendingSavedViewName;pendingSavedViewName=null;org.example.util.ToastManager.info(table,"Saved view applied",name+" filters are now active.");}
private static String part(String[] values,int index){return values!=null&&index>=0&&index<values.length&&values[index]!=null?values[index]:"";}private static void selectSaved(ComboBox<String> box,String raw,String fallback){if(box==null)return;String value=raw==null||raw.isBlank()?fallback:raw.trim();String match=box.getItems().stream().filter(v->v!=null&&v.equalsIgnoreCase(value)).findFirst().orElse(null);if(match==null&&!value.equalsIgnoreCase(fallback)){box.getItems().add(value);match=value;}box.setValue(match!=null?match:fallback);}
 @FXML private void exportExcel(){
  org.example.service.PermissionService.require("QUOTATION.EXPORT", "Export Quotations");
  File f=choose("Quotation_Register.xlsx","Excel","*.xlsx");if(f==null)return;
  String q=safe(txtSearch.getText()),number=safe(txtNumber.getText()),customer=safe(cmbCustomer.getValue()),status=safe(cmbStatus.getValue()),from=str(dpFrom.getValue()),to=str(dpTo.getValue()),valid=str(dpValid.getValue()),salesperson=safe(cmbSalesperson.getValue()),min=safe(txtAmountFrom.getText()),max=safe(txtAmountTo.getText()),follow=safe(cmbFollowUp.getValue()),source=safe(cmbSource.getValue());
  UiTaskExecutor.submitAction("quotation-register-export-excel",()->{List<QuotationApiClient.QuoteDto> rows=quotationApi.allFiltered(q,number,customer,status,from,to,valid,salesperson,min,max,follow,source);writeQuotationExcel(f,rows);return rows.size();},count->success("Quotation register exported • "+count+" records."),failure->error(asException(failure)));
 }
 @FXML private void exportRegisterPdf(){
  org.example.service.PermissionService.require("QUOTATION.EXPORT", "Export Quotations");
  File f=choose("Quotation_Register.pdf","PDF","*.pdf");if(f==null)return;
  String q=safe(txtSearch.getText()),number=safe(txtNumber.getText()),customer=safe(cmbCustomer.getValue()),status=safe(cmbStatus.getValue()),from=str(dpFrom.getValue()),to=str(dpTo.getValue()),valid=str(dpValid.getValue()),salesperson=safe(cmbSalesperson.getValue()),min=safe(txtAmountFrom.getText()),max=safe(txtAmountTo.getText()),follow=safe(cmbFollowUp.getValue()),source=safe(cmbSource.getValue());
  UiTaskExecutor.submitAction("quotation-register-export-pdf",()->{List<QuotationApiClient.QuoteDto> rows=quotationApi.allFiltered(q,number,customer,status,from,to,valid,salesperson,min,max,follow,source);org.example.service.BrandedRegisterPdfService.export(f.toPath(),"Quotation Register",new String[]{"Quotation","Date","Customer","Amount","Status"},rows.stream().map(x->new String[]{x.no(),BusinessClock.formatDate(x.date()),safe(x.customer()),exportMoney(x.amount()),safe(x.status())}).toList(),new float[]{2,1.3f,3,1.5f,1.2f});return rows.size();},count->success("Quotation register PDF exported • "+count+" records."),failure->error(asException(failure)));
 }
 private File choose(String name,String label,String ext){FileChooser c=new FileChooser();c.setInitialFileName(name);c.getExtensionFilters().add(new FileChooser.ExtensionFilter(label,ext));return c.showSaveDialog(table.getScene().getWindow());}
 private void writeQuotationExcel(File f,List<QuotationApiClient.QuoteDto> rows)throws Exception{try(Workbook w=new XSSFWorkbook();FileOutputStream o=new FileOutputStream(f)){Sheet sheet=w.createSheet("Quotations");String[]h={"Quotation","Date","Customer","Amount","Valid Upto","Status","Follow Up","Converted To","Sales Person","Created By"};Row r=sheet.createRow(0);for(int i=0;i<h.length;i++)r.createCell(i).setCellValue(h[i]);int n=1;for(QuotationApiClient.QuoteDto x:rows){r=sheet.createRow(n++);String[]v={x.no(),BusinessClock.formatDate(x.date()),safe(x.customer()),String.valueOf(x.amount()),BusinessClock.formatDate(x.valid()),safe(x.status()),BusinessClock.formatDate(x.followUp()),safe(x.converted()),safe(x.salesperson()),safe(x.createdBy())};for(int i=0;i<v.length;i++)r.createCell(i).setCellValue(v[i]);}w.write(o);}}
 private String exportMoney(double value){return NumberFormat.getCurrencyInstance(Locale.of("en","IN")).format(value).replace("₹","₹ ");}

 private void log(int id,String action,String detail){try{supportApi.activity("QUOTATION",id,action,detail,user());}catch(Exception ignored){}}private void comm(QuoteRow q,String channel,String recipient,String status,String error){try{supportApi.communication(new SupportApiClient.CommunicationRequest("QUOTATION",q.id,channel,recipient,"Quotation "+q.no.get(),status,error,user()));}catch(Exception ignored){}}
 private String user(){return SessionService.current()==null?"System":SessionService.current().getFullName();}private String fmt(double v){return money.format(v).replace("₹","₹ ");}private String safe(String v){return v==null?"":v;}private String low(String v){return safe(v).toLowerCase(Locale.ROOT);}private String str(Object v){return v==null?"":v.toString();}private double num(String v,double d){try{return v==null||v.isBlank()?d:Double.parseDouble(v.replace(",",""));}catch(Exception e){return d;}}private LocalDate parseDate(String v){try{return v.isBlank()?null:LocalDate.parse(v);}catch(Exception e){return null;}}private boolean confirm(String m){return new OwnedAlert(Alert.AlertType.CONFIRMATION,m,ButtonType.YES,ButtonType.NO).showAndWait().orElse(ButtonType.NO)==ButtonType.YES;}private void info(String m){new OwnedAlert(Alert.AlertType.INFORMATION,m).showAndWait();}private void success(String m){org.example.util.ToastManager.success(table,"Completed",m);}private Exception asException(Throwable failure){return failure instanceof Exception e?e:new RuntimeException(failure);}private void error(Exception e){e.printStackTrace();new OwnedAlert(Alert.AlertType.ERROR,e.getMessage()==null?"Operation failed":e.getMessage()).showAndWait();}
 public static final class QuoteRow{final int id,customerId;final SimpleStringProperty no,date,customer,valid,status,followUp,converted,salesperson,createdBy;final SimpleDoubleProperty amount;final LocalDate quoteDate,validDate,followDate;final String phone,email,gstin,source,remarks;String attachment;final double discount;QuoteRow(QuotationApiClient.QuoteDto d){id=d.id();customerId=d.customerId();no=new SimpleStringProperty(d.no());quoteDate=parse(d.date());date=new SimpleStringProperty(quoteDate==null?s(d.date()):BusinessClock.formatDate(quoteDate));customer=new SimpleStringProperty(d.customer());validDate=parse(d.valid());valid=new SimpleStringProperty(validDate==null?"":BusinessClock.formatDate(validDate));status=new SimpleStringProperty(d.status());followDate=parse(d.followUp());followUp=new SimpleStringProperty(followDate==null?"—":BusinessClock.formatDate(followDate));converted=new SimpleStringProperty(s(d.converted()));salesperson=new SimpleStringProperty(s(d.salesperson()));createdBy=new SimpleStringProperty(s(d.createdBy()));amount=new SimpleDoubleProperty(d.amount());phone=s(d.phone());email=s(d.email());gstin=s(d.gstin());source=s(d.source());remarks=s(d.remarks());discount=d.discount();attachment=s(d.attachment());}static LocalDate parse(String v){try{return v==null||v.isBlank()?null:LocalDate.parse(v.substring(0,Math.min(10,v.length())));}catch(Exception e){return null;}}static String s(String v){return v==null?"":v;}}


    private void configureUiIcons() {
        pageIcon.getChildren().setAll(IconFactory.icon("quotation", 24));
        if(quotationHeaderSearchIcon!=null)quotationHeaderSearchIcon.getChildren().setAll(IconFactory.compactIcon("search",16));
        totalMetricIcon.getChildren().setAll(IconFactory.icon("quotation", 22));
        pendingMetricIcon.getChildren().setAll(IconFactory.icon("reminder", 22));
        acceptedMetricIcon.getChildren().setAll(IconFactory.icon("complete", 22));
        expiredMetricIcon.getChildren().setAll(IconFactory.icon("cancel", 22));
        conversionMetricIcon.getChildren().setAll(IconFactory.icon("report", 22));
        averageMetricIcon.getChildren().setAll(IconFactory.icon("report", 22));

        applyButtonIcon(btnNewQuotation, "add");
        applyButtonIcon(btnReset, "reset");
        applyButtonIcon(btnRefresh, "refresh");
        applyButtonIcon(btnApplyFilters, "filter");
        applyButtonIcon(btnExportExcel, "excel");
        applyButtonIcon(btnExportPdf, "pdf");
        applyButtonIcon(btnAllDatesRange, "calendar");
        applyButtonIcon(btnTodayRange, "calendar");
        applyButtonIcon(btnYesterdayRange, "history");
        applyButtonIcon(btnSevenDaysRange, "calendar");
        applyButtonIcon(btnThirtyDaysRange, "calendar");
        applyButtonIcon(btnCustomRange, "calendar");
        btnAdvanced.setGraphic(IconFactory.icon("filter", 15));
        btnAdvanced.getProperties().put("erp-icon-preserve", true);
    }

    private void applyButtonIcon(ButtonBase button, String semantic) {
        if (button == null) return;
        button.setGraphic(IconFactory.icon(semantic, 15));
        button.getProperties().put("erp-icon-preserve", true);
    }

    private void configureEmptyState() {
        VBox empty = new VBox(8,
                IconFactory.icon("quotation", 34),
                new Label("No quotations found"),
                new Label("Create a quotation or adjust the active filters."));
        empty.setAlignment(Pos.CENTER);
        empty.getStyleClass().add("quotation-empty-state");
        empty.getChildren().get(1).getStyleClass().add("quotation-empty-title");
        empty.getChildren().get(2).getStyleClass().add("quotation-empty-message");
        table.setPlaceholder(empty);
    }
}
