package org.example.server.support;
import org.example.server.persistence.JpaNativeRepository;import org.example.server.audit.AuditService;import org.example.server.insights.BusinessKpiPolicy;import org.example.server.operations.BusinessOperationsService;import org.example.server.security.CurrentUser;import org.example.server.util.BusinessClock;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.beans.factory.annotation.Value;import java.time.LocalDate;import java.util.*;import java.nio.file.*;import java.io.IOException;
@Service public class SupportService {
 @Value("${dse.workspace.path:}") private String workspacePath;
 private final JpaNativeRepository jdbc; private final PaymentIntegrityService paymentIntegrity; private final BusinessOperationsService operations; private final AuditService audit; public SupportService(JpaNativeRepository jdbc,PaymentIntegrityService paymentIntegrity,BusinessOperationsService operations,AuditService audit){this.jdbc=jdbc;this.paymentIntegrity=paymentIntegrity;this.operations=operations;this.audit=audit;}
 @Transactional(readOnly=true) public List<SupportDtos.SavedView> savedViews(String screen,Integer ignoredUserId){return jdbc.query("SELECT view_name,filter_json FROM saved_filter WHERE screen_key=? AND (user_id=? OR user_id IS NULL) ORDER BY view_name",(r,i)->new SupportDtos.SavedView(r.getString(1),r.getString(2)),screen,CurrentUser.require().id());}
 @Transactional public void saveView(SupportDtos.SavedViewSave d){jdbc.update("INSERT INTO saved_filter(user_id,screen_key,view_name,filter_json,created_at) VALUES(?,?,?,?,?) ON CONFLICT(user_id,screen_key,view_name) DO UPDATE SET filter_json=excluded.filter_json",CurrentUser.require().id(),d.screen(),d.name(),d.data(),BusinessClock.nowUtcText());}
 @Transactional(readOnly=true) public List<SupportDtos.PaymentRow> payments(String type,int id){requireSalesDocument(type);return jdbc.query("SELECT id,payment_date,COALESCE(reference_no,''),payment_mode,amount,COALESCE(notes,''),COALESCE(received_from,''),COALESCE(attachment_path,''),COALESCE(payment_type,'PARTIAL') FROM payment_record WHERE document_type=? AND document_id=? ORDER BY payment_date DESC,id DESC",(r,i)->new SupportDtos.PaymentRow(r.getInt(1),String.valueOf(r.getObject(2)),r.getString(3),r.getString(4),r.getDouble(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9)),type,id);}
 @Transactional public void recordPayment(SupportDtos.PaymentRequest d){requireSalesDocument(d==null?null:d.documentType());paymentIntegrity.record(d);}
 @Transactional public int recordPaymentWithId(SupportDtos.PaymentRequest d){requireSalesDocument(d==null?null:d.documentType());return paymentIntegrity.record(d);}
 @Transactional public void updatePayment(int paymentId,SupportDtos.PaymentUpdateRequest d){paymentIntegrity.update(paymentId,d);}
 @Transactional public void communication(SupportDtos.CommunicationRequest d){CurrentUser.requirePermission("COMMUNICATION.CREATE","Log communication");requireEntityPermission(d.entityType(),"EDIT","Log communication");jdbc.update("INSERT INTO communication_log(entity_type,entity_id,channel,recipient,subject,status,error_message,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)",d.entityType(),d.entityId(),d.channel(),d.recipient(),d.subject(),d.status(),d.errorMessage(),CurrentUser.require().username(),BusinessClock.nowUtcText());audit.logChanges(d.entityType(),d.entityId(),(d.channel()==null?"COMMUNICATION":d.channel().toUpperCase())+("FAILED".equalsIgnoreCase(d.status())?"_FAILED":"_SENT"),d.recipient()+" • "+d.subject()+" • "+d.status(),java.util.List.of(new AuditService.Change("Recipient",null,d.recipient()),new AuditService.Change("Status",null,d.status())));}
 @Transactional(readOnly=true) public List<SupportDtos.CommunicationRow> communications(){CurrentUser.requirePermission("COMMUNICATION.VIEW","View communications");return jdbc.query("SELECT c.id,c.entity_type,c.entity_id,COALESCE(CASE WHEN c.entity_type='SALE' THEN (SELECT invoice_no FROM sales_header WHERE id=c.entity_id) WHEN c.entity_type='PURCHASE' THEN (SELECT invoice_no FROM purchase_header WHERE id=c.entity_id) WHEN c.entity_type='QUOTATION' THEN (SELECT quotation_no FROM quotation_header WHERE id=c.entity_id) END,c.subject,c.entity_type||' #'||c.entity_id),c.channel,COALESCE(c.recipient,''),COALESCE(c.subject,''),COALESCE(c.status,''),COALESCE(c.error_message,''),COALESCE(c.created_by,''),COALESCE(c.created_at::text,'') FROM communication_log c ORDER BY c.created_at DESC,c.id DESC LIMIT 500",(r,i)->new SupportDtos.CommunicationRow(r.getInt(1),r.getString(2),r.getInt(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11)));}
 @Transactional public void markWhatsappSent(String type,int id){requireEntityPermission(type,"EDIT","Update WhatsApp status");String normalized=type==null?"":type.trim().toUpperCase(Locale.ROOT);String table=documentTableUnchecked(type);String old=Objects.toString(jdbc.queryForObject("SELECT COALESCE(whatsapp_sent,0)::text FROM "+table+" WHERE id=?",String.class,id),"0");int updated=jdbc.update("UPDATE "+table+" SET whatsapp_sent=1,row_version=row_version+1 WHERE id=?",id);if(updated!=1)throw new IllegalArgumentException("Document not found while updating WhatsApp status");audit.logChange(normalized,id,"WHATSAPP_SENT","WhatsApp marked as sent","WhatsApp Sent",old,"1");}
 @Transactional public void setNotes(String type,int id,String notes){requireEntityPermission(type,"EDIT","Update document notes");String normalized=type==null?"":type.trim().toUpperCase(Locale.ROOT);String table=documentTableUnchecked(type);String old=jdbc.queryForObject("SELECT COALESCE(notes,'') FROM "+table+" WHERE id=?",String.class,id);jdbc.update("UPDATE "+table+" SET notes=?,updated_at=?,row_version=row_version+1 WHERE id=?",notes,BusinessClock.nowUtcText(),id);audit.logChange(normalized,id,"NOTES_UPDATED","Document notes updated","Notes",old,notes);}
 @Transactional public String storeDocumentAttachment(String type,int id,String fileName,byte[] data){
  String normalized=requireAttachmentDocument(type,true); assertDocumentExists(normalized,id);
  String old=documentAttachmentReference(normalized,id); String ref=storeManagedAttachment(normalized,String.valueOf(id),fileName,data);
  try{setDocumentAttachmentReference(normalized,id,ref);}catch(RuntimeException ex){deleteReferenceQuietly(ref);throw ex;}
  deleteSupersededManagedReference(old,ref);audit.logChange(normalized,id,"ATTACHMENT_UPDATED","Primary attachment updated","Attachment",old,ref); return ref;
 }
 @Transactional(readOnly=true) public SupportDtos.AttachmentFile documentAttachmentFile(String type,int id){String normalized=requireAttachmentDocument(type,false);assertDocumentExists(normalized,id);return readAttachment(documentAttachmentReference(normalized,id));}
 @Transactional public void removeDocumentAttachment(String type,int id){String normalized=requireAttachmentDocument(type,true);assertDocumentExists(normalized,id);String old=documentAttachmentReference(normalized,id);setDocumentAttachmentReference(normalized,id,"");if(old!=null&&!old.isBlank())jdbc.update("DELETE FROM document_attachment WHERE document_type=? AND document_id=? AND storage_ref=?",normalized,id,old);deleteManagedReferenceQuietly(old);audit.logChange(normalized,id,"ATTACHMENT_REMOVED","Primary attachment removed","Attachment",old,"");}
 @Transactional(readOnly=true) public List<SupportDtos.AttachmentMeta> documentAttachments(String type,int id){
  String normalized=requireAttachmentDocument(type,false);assertDocumentExists(normalized,id);
  return jdbc.query("SELECT id,document_type,document_id,file_name,COALESCE(created_by,''),COALESCE(created_at::text,'') FROM document_attachment WHERE document_type=? AND document_id=? ORDER BY id",(r,i)->new SupportDtos.AttachmentMeta(r.getLong(1),r.getString(2),r.getInt(3),r.getString(4),r.getString(5),r.getString(6)),normalized,id);
 }
 @Transactional public SupportDtos.AttachmentMeta addDocumentAttachment(String type,int id,String fileName,byte[] data){
  String normalized=requireAttachmentDocument(type,true);assertDocumentExists(normalized,id);
  String ref=storeManagedAttachment(normalized+"Attachments",String.valueOf(id),fileName,data);
  try{
   String createdBy=CurrentUser.require().username(),createdAt=BusinessClock.nowUtcText();
   long attachmentId=jdbc.queryForObject("INSERT INTO document_attachment(document_type,document_id,file_name,storage_ref,created_by,created_at) VALUES(?,?,?,?,?,?) RETURNING id",Long.class,normalized,id,safeFileName(fileName),ref,createdBy,createdAt);
   if(documentAttachmentReference(normalized,id).isBlank())setDocumentAttachmentReference(normalized,id,ref);
   audit.logChange(normalized,id,"ATTACHMENT_ADDED","Attachment added: "+safeFileName(fileName),"Attachment",null,safeFileName(fileName));
   return new SupportDtos.AttachmentMeta(attachmentId,normalized,id,safeFileName(fileName),createdBy,createdAt);
  }catch(RuntimeException ex){deleteReferenceQuietly(ref);throw ex;}
 }
 @Transactional(readOnly=true) public SupportDtos.AttachmentFile documentAttachmentFile(String type,int id,long attachmentId){
  String normalized=requireAttachmentDocument(type,false);assertDocumentExists(normalized,id);
  List<String> refs=jdbc.query("SELECT storage_ref FROM document_attachment WHERE id=? AND document_type=? AND document_id=?",(r,i)->r.getString(1),attachmentId,normalized,id);
  if(refs.isEmpty())throw new IllegalArgumentException("Attachment not found");
  return readAttachment(refs.getFirst());
 }
 @Transactional public void removeDocumentAttachment(String type,int id,long attachmentId){
  String normalized=requireAttachmentDocument(type,true);assertDocumentExists(normalized,id);
  List<String> refs=jdbc.query("SELECT storage_ref FROM document_attachment WHERE id=? AND document_type=? AND document_id=? FOR UPDATE",(r,i)->r.getString(1),attachmentId,normalized,id);
  if(refs.isEmpty())throw new IllegalArgumentException("Attachment not found");
  String removedRef=refs.getFirst();
  jdbc.update("DELETE FROM document_attachment WHERE id=? AND document_type=? AND document_id=?",attachmentId,normalized,id);
  if(Objects.equals(documentAttachmentReference(normalized,id),removedRef)){
   List<String> remaining=jdbc.query("SELECT storage_ref FROM document_attachment WHERE document_type=? AND document_id=? ORDER BY id LIMIT 1",(r,i)->r.getString(1),normalized,id);
   setDocumentAttachmentReference(normalized,id,remaining.isEmpty()?"":remaining.getFirst());
  }
  deleteManagedReferenceQuietly(removedRef);audit.logChange(normalized,id,"ATTACHMENT_REMOVED","Attachment removed","Attachment",removedRef,null);
 }
 @Transactional public String storeReturnAttachment(String no,String fileName,byte[] data){requireReturnAccess(no,true);String old=returnAttachmentReference(no);String ref=storeManagedAttachment(returnFolder(no),safeSegment(no),fileName,data);try{jdbc.update("UPDATE return_register SET attachment_path=?,updated_at=? WHERE return_no=?",ref,BusinessClock.nowUtcText(),no);}catch(RuntimeException ex){deleteReferenceQuietly(ref);throw ex;}deleteSupersededManagedReference(old,ref);return ref;}
 @Transactional(readOnly=true) public SupportDtos.AttachmentFile returnAttachmentFile(String no){requireReturnAccess(no,false);return readAttachment(returnAttachmentReference(no));}
 @Transactional public void removeReturnAttachment(String no){requireReturnAccess(no,true);String old=returnAttachmentReference(no);jdbc.update("UPDATE return_register SET attachment_path='',updated_at=? WHERE return_no=?",BusinessClock.nowUtcText(),no);deleteManagedReferenceQuietly(old);}
 @Transactional public String storePaymentAttachment(int paymentId,String fileName,byte[] data){assertPaymentEditable(paymentId);String old=paymentAttachmentReference(paymentId);String ref=storeManagedAttachment("PaymentProofs",String.valueOf(paymentId),fileName,data);try{paymentIntegrity.updateAttachment(paymentId,ref);}catch(RuntimeException ex){deleteReferenceQuietly(ref);throw ex;}deleteSupersededManagedReference(old,ref);return ref;}
 @Transactional(readOnly=true) public SupportDtos.AttachmentFile paymentAttachmentFile(int paymentId){requirePaymentAccess(paymentId,false);return readAttachment(paymentAttachmentReference(paymentId));}
 @Transactional public void removePaymentAttachment(int paymentId){assertPaymentEditable(paymentId);String old=paymentAttachmentReference(paymentId);paymentIntegrity.updateAttachment(paymentId,"");deleteManagedReferenceQuietly(old);}
 @Transactional public String storeReturnRefundAttachment(int refundId,String fileName,byte[] data){assertReturnRefundEditable(refundId);String old=returnRefundAttachmentReference(refundId);String returnNo=jdbc.queryForObject("SELECT return_no FROM return_refund WHERE id=?",String.class,refundId);String ref=storeManagedAttachment("ReturnRefundProofs",safeSegment(returnNo),fileName,data);try{jdbc.update("UPDATE return_refund SET attachment_path=? WHERE id=?",ref,refundId);}catch(RuntimeException ex){deleteReferenceQuietly(ref);throw ex;}deleteSupersededManagedReference(old,ref);return ref;}
 @Transactional(readOnly=true) public SupportDtos.AttachmentFile returnRefundAttachmentFile(int refundId){requireReturnRefundAccess(refundId,false);return readAttachment(returnRefundAttachmentReference(refundId));}
 @Transactional public void removeReturnRefundAttachment(int refundId){assertReturnRefundEditable(refundId);String old=returnRefundAttachmentReference(refundId);jdbc.update("UPDATE return_refund SET attachment_path='' WHERE id=?",refundId);deleteManagedReferenceQuietly(old);}

 private String requireAttachmentDocument(String type,boolean write){String n=normalizeAttachmentDocument(type);String permission=switch(n){case "PURCHASE"->write?"PURCHASE.EDIT":"PURCHASE.VIEW";case "QUOTATION"->write?"QUOTATION.EDIT":"QUOTATION.VIEW";case "PURCHASE_RECON"->write?"PURCHASE_RECON.EDIT":"PURCHASE_RECON.VIEW";case "CUSTOMER"->write?"CUSTOMERS.EDIT":"CUSTOMERS.VIEW";default->write?"SALES.EDIT":"SALES.VIEW";};CurrentUser.requirePermission(permission,write?"Modify document attachments":"View document attachments");return n;}
 private String normalizeAttachmentDocument(String type){String n=type==null?"":type.trim().toUpperCase(Locale.ROOT);if(!Set.of("SALE","PURCHASE","QUOTATION","PURCHASE_RECON","CUSTOMER").contains(n))throw new IllegalArgumentException("Attachment document type must be SALE, PURCHASE, QUOTATION, PURCHASE_RECON or CUSTOMER");return n;}
 private void assertDocumentExists(String type,int id){String table=attachmentTable(type);Long count=jdbc.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE id=?",Long.class,id);if(count==null||count==0)throw new IllegalArgumentException("Document not found");}
 private String attachmentTable(String type){return switch(type){case "SALE"->"sales_header";case "PURCHASE"->"purchase_header";case "QUOTATION"->"quotation_header";case "PURCHASE_RECON"->"purchase_recon";case "CUSTOMER"->"party_master";default->throw new IllegalArgumentException("Unsupported document type");};}
 private String documentAttachmentReference(String type,int id){List<String>x=jdbc.query("SELECT COALESCE(attachment_path,'') FROM "+attachmentTable(type)+" WHERE id=?",(rs,i)->rs.getString(1),id);return x.isEmpty()?"":x.getFirst();}
 private void setDocumentAttachmentReference(String type,int id,String path){String n=normalizeAttachmentDocument(type);String table=attachmentTable(n);if("QUOTATION".equals(n))jdbc.update("UPDATE "+table+" SET attachment_path=? WHERE id=?",path,id);else if("CUSTOMER".equals(n))jdbc.update("UPDATE "+table+" SET attachment_path=?,row_version=row_version+1 WHERE id=?",path,id);else jdbc.update("UPDATE "+table+" SET attachment_path=?,updated_at=?,row_version=row_version+1 WHERE id=?",path,BusinessClock.nowUtcText(),id);}
 private String returnAttachmentReference(String no){List<String>x=jdbc.query("SELECT COALESCE(MAX(attachment_path),'') FROM return_register WHERE return_no=?",(rs,i)->rs.getString(1),no);return x.isEmpty()?"":x.getFirst();}
 private String paymentAttachmentReference(int id){List<String>x=jdbc.query("SELECT COALESCE(attachment_path,'') FROM payment_record WHERE id=?",(rs,i)->rs.getString(1),id);if(x.isEmpty())throw new IllegalArgumentException("Payment not found");return x.getFirst();}
 private void assertPaymentEditable(int id){requirePaymentAccess(id,true);List<String>x=jdbc.query("SELECT COALESCE(payment_type,'PARTIAL') FROM payment_record WHERE id=?",(rs,i)->rs.getString(1),id);if(x.isEmpty())throw new IllegalArgumentException("Payment not found");if("BANK_RECONCILIATION".equalsIgnoreCase(x.getFirst()))throw new IllegalStateException("Bank reconciliation payment proofs are read-only.");}
 private void requirePaymentAccess(int id,boolean write){List<String>x=jdbc.query("SELECT document_type FROM payment_record WHERE id=?",(rs,i)->rs.getString(1),id);if(x.isEmpty())throw new IllegalArgumentException("Payment not found");String type=x.getFirst()==null?"":x.getFirst().trim().toUpperCase(Locale.ROOT);if(!Set.of("SALE","PURCHASE").contains(type))throw new IllegalArgumentException("Payment document type is invalid");CurrentUser.requirePermission("PURCHASE".equals(type)?(write?"PURCHASE.EDIT":"PURCHASE.VIEW"):(write?"SALES.EDIT":"SALES.VIEW"),write?"Modify payment proof":"View payment proof");}
 private void requireReturnAccess(String no,boolean write){String type=jdbc.queryForObject("SELECT MAX(return_type) FROM return_register WHERE return_no=?",String.class,no);if(type==null)throw new IllegalArgumentException("Return not found");boolean purchase=type.toUpperCase(Locale.ROOT).startsWith("PURCHASE");CurrentUser.requirePermission(purchase?(write?"PURCHASE.EDIT":"PURCHASE.VIEW"):(write?"SALES.EDIT":"SALES.VIEW"),write?"Modify return attachment":"View return attachment");}

 private String returnRefundAttachmentReference(int id){List<String>x=jdbc.query("SELECT COALESCE(attachment_path,'') FROM return_refund WHERE id=?",(rs,i)->rs.getString(1),id);if(x.isEmpty())throw new IllegalArgumentException("Return refund not found");return x.getFirst();}
 private void assertReturnRefundEditable(int id){requireReturnRefundAccess(id,true);List<String>x=jdbc.query("SELECT COALESCE(refund_type,'PARTIAL') FROM return_refund WHERE id=?",(rs,i)->rs.getString(1),id);if(x.isEmpty())throw new IllegalArgumentException("Return refund not found");if("BANK_RECONCILIATION".equalsIgnoreCase(x.getFirst()))throw new IllegalStateException("Bank-reconciled refund proofs are read-only.");}
 private void requireReturnRefundAccess(int id,boolean write){List<String>x=jdbc.query("SELECT COALESCE(MAX(r.return_type),'') FROM return_refund rr JOIN return_register r ON r.return_no=rr.return_no WHERE rr.id=?",(rs,i)->rs.getString(1),id);if(x.isEmpty()||x.getFirst()==null||x.getFirst().isBlank())throw new IllegalArgumentException("Return refund not found");boolean purchase=x.getFirst().toUpperCase(Locale.ROOT).startsWith("PURCHASE");CurrentUser.requirePermission(purchase?(write?"PURCHASE.EDIT":"PURCHASE.VIEW"):(write?"SALES.EDIT":"SALES.VIEW"),write?"Modify return refund proof":"View return refund proof");}
 private String returnFolder(String no){String type=jdbc.queryForObject("SELECT MAX(return_type) FROM return_register WHERE return_no=?",String.class,no);return type!=null&&type.toUpperCase(Locale.ROOT).startsWith("PURCHASE")?"PurchaseReturns":"SalesReturns";}
 private String storeManagedAttachment(String module,String key,String fileName,byte[] data){if(data==null||data.length==0)throw new IllegalArgumentException("Attachment file is empty");if(data.length>25*1024*1024)throw new IllegalArgumentException("Attachment is larger than 25 MB");try{Path root=attachmentRoot();Path folder=root.resolve(safeSegment(module)).resolve(safeSegment(key)).normalize();if(!folder.startsWith(root))throw new IllegalArgumentException("Invalid attachment folder");Files.createDirectories(folder);String safe=safeFileName(fileName);Path target=folder.resolve(System.currentTimeMillis()+"-"+safe).normalize();if(!target.startsWith(folder))throw new IllegalArgumentException("Invalid attachment filename");Files.write(target,data,StandardOpenOption.CREATE_NEW);return workspaceRoot().relativize(target).toString();}catch(IOException ex){throw new IllegalStateException("Unable to store attachment",ex);}}
 private SupportDtos.AttachmentFile readAttachment(String reference){if(reference==null||reference.isBlank())throw new IllegalArgumentException("No attachment is available");try{Path path=resolveAttachmentReference(reference);if(path==null||!Files.isRegularFile(path))throw new IllegalArgumentException("Attachment file is not available");return new SupportDtos.AttachmentFile(path.getFileName().toString(),Files.readAllBytes(path));}catch(IOException ex){throw new IllegalArgumentException("Attachment exists but could not be read from managed storage. Check the server Attachments workspace permissions.",ex);}}
 private Path workspaceRoot(){if(workspacePath==null||workspacePath.isBlank())throw new IllegalStateException("Server workspace path is not configured");return Path.of(workspacePath).toAbsolutePath().normalize();}
 private Path attachmentRoot(){return workspaceRoot().resolve("Attachments").normalize();}
 private Path resolveAttachmentReference(String reference){try{Path p=Path.of(reference);Path resolved=p.isAbsolute()?p.toAbsolutePath().normalize():workspaceRoot().resolve(p).normalize();Path root=attachmentRoot().toAbsolutePath().normalize();return resolved.startsWith(root)?resolved:null;}catch(Exception ex){return null;}}
 private void deleteSupersededManagedReference(String oldRef,String newRef){if(oldRef==null||oldRef.isBlank()||Objects.equals(oldRef,newRef))return;deleteManagedReferenceQuietly(oldRef);}
 private void deleteManagedReferenceQuietly(String ref){try{Path p=resolveAttachmentReference(ref);Path root=attachmentRoot().toAbsolutePath().normalize();if(p!=null&&p.toAbsolutePath().normalize().startsWith(root))Files.deleteIfExists(p);}catch(Exception ignored){}}
 private void deleteReferenceQuietly(String ref){deleteManagedReferenceQuietly(ref);}
 private String safeSegment(String value){String x=value==null?"document":value.replaceAll("[^A-Za-z0-9._-]","_");return x.isBlank()?"document":x;}
 private String safeFileName(String value){String x=value==null?"attachment":Path.of(value).getFileName().toString().replaceAll("[^A-Za-z0-9._() -]","_").trim();return x.isBlank()?"attachment":x;}
 @Transactional public void activity(String type,int id,String action,String detail,String ignoredUser){requireSalesEntity(type);audit.log(type,id,action,detail);}
 @Transactional(readOnly=true) public List<SupportDtos.ActivityRow> activityRows(String type,int id){requireSalesEntity(type);String normalized=type==null?"":type.trim().toUpperCase(Locale.ROOT);return jdbc.query("SELECT id,entity_type,entity_id,action,COALESCE(detail,''),COALESCE(created_by,'System'),COALESCE(created_at,'') FROM activity_log WHERE UPPER(entity_type)=? AND entity_id=? ORDER BY id DESC LIMIT 200",(r,i)->new SupportDtos.ActivityRow(r.getLong(1),r.getString(2),r.getInt(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7)),normalized,id);}

 @Transactional(readOnly=true) public String returnPartyEmail(String no){requireReturnAccess(no,false);List<String>x=jdbc.query("SELECT COALESCE(pm.email,\'\') FROM return_register rr LEFT JOIN party_master pm ON pm.id=rr.party_id WHERE rr.return_no=? LIMIT 1",(r,i)->r.getString(1),no);return x.isEmpty()?"":x.getFirst();}
 @Transactional public String duplicateSale(int id,String user){CurrentUser.requirePermission("SALES.CREATE","Duplicate Sale");return operations.duplicateSale(id).invoiceNo();}
 @Transactional public void cancelPurchase(int id){String invoice=jdbc.queryForObject("SELECT invoice_no FROM purchase_header WHERE id=?",String.class,id);if(invoice==null||invoice.isBlank())throw new IllegalArgumentException("Purchase document was not found");operations.cancelPurchase(invoice);}
 @Transactional(readOnly=true)
 public SupportDtos.ResolvedRecord resolveRecord(String moduleKey,String reference){
   String ref=reference==null?"":reference.trim();if(ref.isBlank())return new SupportDtos.ResolvedRecord(false,"",null,"","");
   String key=moduleKey==null?"":moduleKey.trim().toUpperCase(Locale.ROOT);
   key=switch(key){case "SALES","SALES_ORDER","SALES_ORDERS"->"SALE";case "PURCHASES","PURCHASE_ORDER","PURCHASE_ORDERS"->"PURCHASE";case "QUOTATIONS"->"QUOTATION";case "SALES_RETURNS"->"SALES_RETURN";case "PURCHASE_RETURNS"->"PURCHASE_RETURN";case "ITEMS"->"ITEM";case "PAYMENTS"->"PAYMENT";case "REMINDERS"->"REMINDER";default->key;};
   String permission=switch(key){case "SALE"->"SALES.VIEW";case "PURCHASE"->"PURCHASE.VIEW";case "QUOTATION"->"QUOTATION.VIEW";case "SALES_RETURN"->"SALES.VIEW";case "PURCHASE_RETURN"->"PURCHASE.VIEW";case "ITEM","STOCK_ADJUSTMENT"->"INVENTORY.VIEW";case "CUSTOMER"->"CUSTOMERS.VIEW";case "SUPPLIER"->"SUPPLIERS.VIEW";case "PAYMENT"->"";case "FINANCE","BANK_STATEMENT"->"BANK_EXPENSE.VIEW";case "REMINDER"->"REMINDERS.VIEW";case "COMMUNICATION"->"COMMUNICATION.VIEW";case "MASTER"->"MASTERS.VIEW";case "USER"->"USERS.VIEW";default->"";};
   if(!permission.isBlank()&&!searchPermissionAllowed(permission))return new SupportDtos.ResolvedRecord(false,key,null,ref,targetFor(key));
   SupportDtos.ResolvedRecord found=switch(key){
     case "SALE"->resolved(key,targetFor(key),"SELECT id,invoice_no FROM sales_header WHERE LOWER(TRIM(invoice_no))=LOWER(TRIM(?)) AND UPPER(COALESCE(document_status,''))<>'DELETED' ORDER BY id DESC LIMIT 1",ref);
     case "PURCHASE"->resolved(key,targetFor(key),"SELECT id,invoice_no FROM purchase_header WHERE LOWER(TRIM(invoice_no))=LOWER(TRIM(?)) AND UPPER(COALESCE(document_status,''))<>'DELETED' ORDER BY id DESC LIMIT 1",ref);
     case "QUOTATION"->resolved(key,targetFor(key),"SELECT id,quotation_no FROM quotation_header WHERE LOWER(TRIM(quotation_no))=LOWER(TRIM(?)) AND UPPER(COALESCE(status,''))<>'DELETED' ORDER BY id DESC LIMIT 1",ref);
     case "SALES_RETURN"->resolved(key,targetFor(key),"SELECT id,return_no FROM return_register WHERE UPPER(return_type)='SALES RETURN' AND LOWER(TRIM(return_no))=LOWER(TRIM(?)) AND UPPER(COALESCE(status,''))<>'DELETED' ORDER BY id DESC LIMIT 1",ref);
     case "PURCHASE_RETURN"->resolved(key,targetFor(key),"SELECT id,return_no FROM return_register WHERE UPPER(return_type)='PURCHASE RETURN' AND LOWER(TRIM(return_no))=LOWER(TRIM(?)) AND UPPER(COALESCE(status,''))<>'DELETED' ORDER BY id DESC LIMIT 1",ref);
     case "ITEM"->resolved(key,targetFor(key),"SELECT id,item_code FROM item_master WHERE LOWER(TRIM(item_code))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     case "CUSTOMER"->resolved(key,targetFor(key),"SELECT id,party_code FROM party_master WHERE party_type='CUSTOMER' AND LOWER(TRIM(party_code))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     case "SUPPLIER"->resolved(key,targetFor(key),"SELECT id,party_code FROM party_master WHERE party_type='SUPPLIER' AND LOWER(TRIM(party_code))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     case "PAYMENT"->resolvePayment(ref);
     case "FINANCE"->resolved(key,targetFor(key),"SELECT id,voucher_no FROM finance_register WHERE LOWER(TRIM(voucher_no))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     case "BANK_STATEMENT"->resolved(key,targetFor(key),"SELECT id,COALESCE(original_reference,'Row '||CAST(source_row_number AS text)) FROM bank_statement_transaction WHERE LOWER(TRIM(COALESCE(original_reference,'Row '||CAST(source_row_number AS text))))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     case "REMINDER"->resolved(key,targetFor(key),"SELECT id,COALESCE(reference_no,'Reminder #'||CAST(id AS text)) FROM reminder_register WHERE LOWER(TRIM(COALESCE(reference_no,'Reminder #'||CAST(id AS text))))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     case "STOCK_ADJUSTMENT"->resolved(key,targetFor(key),"SELECT id,COALESCE(reference_no,'Adjustment #'||CAST(id AS text)) FROM stock_adjustment WHERE LOWER(TRIM(COALESCE(reference_no,'Adjustment #'||CAST(id AS text))))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     case "MASTER"->resolveMaster(ref);
     case "USER"->resolved(key,targetFor(key),"SELECT id,username FROM users WHERE LOWER(TRIM(username))=LOWER(TRIM(?)) ORDER BY id DESC LIMIT 1",ref);
     default->new SupportDtos.ResolvedRecord(false,key,null,ref,targetFor(key));
   };
   return found;
 }
 private SupportDtos.ResolvedRecord resolved(String key,String target,String sql,String reference){try{List<SupportDtos.ResolvedRecord> rows=jdbc.query(sql,(r,i)->new SupportDtos.ResolvedRecord(true,key,r.getLong(1),Objects.toString(r.getObject(2),reference),target),reference);return rows.isEmpty()?new SupportDtos.ResolvedRecord(false,key,null,reference,target):rows.getFirst();}catch(Exception ignored){return new SupportDtos.ResolvedRecord(false,key,null,reference,target);}}
 private SupportDtos.ResolvedRecord resolveMaster(String reference){
   String ref=reference==null?"":reference.trim();
   if(ref.isBlank())return new SupportDtos.ResolvedRecord(false,"MASTER",null,ref,targetFor("MASTER"));
   try{
     List<SupportDtos.ResolvedRecord> rows=jdbc.query("SELECT lm.id,lm.lookup_code FROM lookup_master lm WHERE LOWER(TRIM(lm.lookup_code))=LOWER(TRIM(?)) OR EXISTS (SELECT 1 FROM lookup_code_alias a WHERE a.lookup_id=lm.id AND LOWER(TRIM(a.alias_code))=LOWER(TRIM(?))) ORDER BY lm.id DESC LIMIT 1",(r,i)->new SupportDtos.ResolvedRecord(true,"MASTER",r.getLong(1),r.getString(2),targetFor("MASTER")),ref,ref);
     return rows.isEmpty()?new SupportDtos.ResolvedRecord(false,"MASTER",null,ref,targetFor("MASTER")):rows.getFirst();
   }catch(Exception ignored){return new SupportDtos.ResolvedRecord(false,"MASTER",null,ref,targetFor("MASTER"));}
 }
 private SupportDtos.ResolvedRecord resolvePayment(String reference){
   String ref=reference==null?"":reference.trim();
   if(ref.isBlank())return new SupportDtos.ResolvedRecord(false,"PAYMENT",null,"","");
   try{
     List<SupportDtos.ResolvedRecord> rows=jdbc.query("SELECT UPPER(p.document_type),p.document_id,CASE WHEN UPPER(p.document_type)='PURCHASE' THEN ph.invoice_no ELSE sh.invoice_no END FROM payment_record p LEFT JOIN sales_header sh ON UPPER(p.document_type)='SALE' AND sh.id=p.document_id LEFT JOIN purchase_header ph ON UPPER(p.document_type)='PURCHASE' AND ph.id=p.document_id WHERE LOWER(TRIM(COALESCE(p.reference_no,'')))=LOWER(TRIM(?)) OR LOWER(TRIM(COALESCE(sh.invoice_no,'')))=LOWER(TRIM(?)) OR LOWER(TRIM(COALESCE(ph.invoice_no,'')))=LOWER(TRIM(?)) ORDER BY p.id DESC LIMIT 1",(r,i)->{String type=r.getString(1);String key="PURCHASE".equals(type)?"PURCHASE":"SALE";String target="PURCHASE".equals(type)?"/fxml/pages/PurchasePayment.fxml":"/fxml/pages/RecordPayment.fxml";return new SupportDtos.ResolvedRecord(true,key,r.getLong(2),Objects.toString(r.getObject(3),ref),target);},ref,ref,ref);
     if(rows.isEmpty())return new SupportDtos.ResolvedRecord(false,"PAYMENT",null,ref,"");
     SupportDtos.ResolvedRecord row=rows.getFirst();
     String permission="PURCHASE".equals(row.moduleKey())?"PURCHASE.VIEW":"SALES.VIEW";
     return searchPermissionAllowed(permission)?row:new SupportDtos.ResolvedRecord(false,row.moduleKey(),null,row.reference(),row.targetFxml());
   }catch(Exception ignored){return new SupportDtos.ResolvedRecord(false,"PAYMENT",null,ref,"");}
 }
 private String targetFor(String key){return switch(key){case "SALE"->"/fxml/pages/SalesList.fxml";case "PURCHASE"->"/fxml/pages/PurchaseList.fxml";case "QUOTATION"->"/fxml/pages/Quotations.fxml";case "SALES_RETURN"->"/fxml/pages/SalesReturns.fxml";case "PURCHASE_RETURN"->"/fxml/pages/PurchaseReturns.fxml";case "ITEM"->"/fxml/pages/ItemMaster.fxml";case "CUSTOMER"->"/fxml/pages/Customer.fxml";case "SUPPLIER"->"/fxml/pages/Suppliers.fxml";case "PAYMENT"->"/fxml/pages/RecordPayment.fxml";case "FINANCE"->"/fxml/pages/BankExpense.fxml";case "BANK_STATEMENT"->"/fxml/pages/BankStatement.fxml";case "REMINDER"->"/fxml/pages/ReminderCenter.fxml";case "COMMUNICATION"->"/fxml/pages/CommunicationCenter.fxml";case "STOCK_ADJUSTMENT"->"/fxml/pages/Inventory.fxml";case "MASTER"->"/fxml/pages/Masterdata.fxml";case "USER"->"/fxml/pages/UserAccess.fxml";default->"";};}

 @Transactional(readOnly=true)
 public List<SupportDtos.SearchRow> search(String q){
   String term=q==null?"":q.trim(); if(term.isBlank())return List.of(); String like="%"+term+"%";
   List<SupportDtos.SearchRow> out=new ArrayList<>();
   search(out,"Items","ITEM","/fxml/pages/ItemMaster.fxml","INVENTORY.VIEW","SELECT id,item_code,description,COALESCE(category,'')||'  Stock: '||COALESCE(opening_stock,0) FROM item_master WHERE item_code ILIKE ? OR description ILIKE ? OR category ILIKE ? OR brand ILIKE ? OR material ILIKE ? OR size ILIKE ? OR hsn ILIKE ? OR COALESCE(location,'') ILIKE ? OR COALESCE(remarks,'') ILIKE ? ORDER BY item_code LIMIT 50",like,9);
   search(out,"Customers","CUSTOMER","/fxml/pages/Customer.fxml","CUSTOMERS.VIEW","SELECT id,party_code,name,COALESCE(phone,'')||'  '||COALESCE(email,'')||'  '||COALESCE(gstin,'') FROM party_master WHERE party_type='CUSTOMER' AND (party_code ILIKE ? OR name ILIKE ? OR COALESCE(contact_person,'') ILIKE ? OR COALESCE(phone,'') ILIKE ? OR COALESCE(email,'') ILIKE ? OR COALESCE(gstin,'') ILIKE ? OR COALESCE(address,'') ILIKE ?) ORDER BY name LIMIT 50",like,7);
   search(out,"Suppliers","SUPPLIER","/fxml/pages/Suppliers.fxml","SUPPLIERS.VIEW","SELECT id,party_code,name,COALESCE(phone,'')||'  '||COALESCE(email,'')||'  '||COALESCE(gstin,'') FROM party_master WHERE party_type='SUPPLIER' AND (party_code ILIKE ? OR name ILIKE ? OR COALESCE(contact_person,'') ILIKE ? OR COALESCE(phone,'') ILIKE ? OR COALESCE(email,'') ILIKE ? OR COALESCE(gstin,'') ILIKE ? OR COALESCE(address,'') ILIKE ?) ORDER BY name LIMIT 50",like,7);
   search(out,"Sales Invoices","SALE","/fxml/pages/SalesList.fxml","SALES.VIEW","SELECT DISTINCT s.id,s.invoice_no,p.name,CAST(s.invoice_date AS text)||'  ₹'||to_char(s.total_amount,'FM999999990.00')||'  '||("+BusinessKpiPolicy.effectivePaymentStatus("s","SALE")+") FROM sales_header s JOIN party_master p ON p.id=s.customer_id LEFT JOIN sales_line l ON l.sales_id=s.id LEFT JOIN item_master i ON i.item_code=l.item_code WHERE UPPER(COALESCE(s.document_status,''))<>'DELETED' AND (s.invoice_no ILIKE ? OR p.name ILIKE ? OR COALESCE(p.contact_person,'') ILIKE ? OR COALESCE(p.phone,'') ILIKE ? OR COALESCE(p.email,'') ILIKE ? OR COALESCE(s.remarks,'') ILIKE ? OR COALESCE(l.item_code,'') ILIKE ? OR COALESCE(i.description,'') ILIKE ?) ORDER BY s.id DESC LIMIT 50",like,8);
   search(out,"Purchase Invoices","PURCHASE","/fxml/pages/PurchaseList.fxml","PURCHASE.VIEW","SELECT DISTINCT s.id,s.invoice_no,p.name,CAST(s.invoice_date AS text)||'  ₹'||to_char(s.total_amount,'FM999999990.00')||'  '||("+BusinessKpiPolicy.effectivePaymentStatus("s","PURCHASE")+") FROM purchase_header s JOIN party_master p ON p.id=s.supplier_id LEFT JOIN purchase_line l ON l.purchase_id=s.id LEFT JOIN item_master i ON i.item_code=l.item_code WHERE UPPER(COALESCE(s.document_status,''))<>'DELETED' AND (s.invoice_no ILIKE ? OR p.name ILIKE ? OR COALESCE(p.contact_person,'') ILIKE ? OR COALESCE(p.phone,'') ILIKE ? OR COALESCE(p.email,'') ILIKE ? OR COALESCE(s.reference_no,'') ILIKE ? OR COALESCE(s.remarks,'') ILIKE ? OR COALESCE(l.item_code,'') ILIKE ? OR COALESCE(i.description,'') ILIKE ?) ORDER BY s.id DESC LIMIT 50",like,9);
   search(out,"Quotations","QUOTATION","/fxml/pages/Quotations.fxml","QUOTATION.VIEW","SELECT DISTINCT q.id,q.quotation_no,p.name,CAST(q.quotation_date AS text)||'  ₹'||to_char(q.total_amount,'FM999999990.00')||'  '||COALESCE(q.status,'') FROM quotation_header q JOIN party_master p ON p.id=q.customer_id LEFT JOIN quotation_line l ON l.quotation_id=q.id LEFT JOIN item_master i ON i.item_code=l.item_code WHERE UPPER(COALESCE(q.status,''))<>'DELETED' AND (q.quotation_no ILIKE ? OR p.name ILIKE ? OR COALESCE(p.contact_person,'') ILIKE ? OR COALESCE(p.phone,'') ILIKE ? OR COALESCE(q.remarks,'') ILIKE ? OR COALESCE(l.item_code,'') ILIKE ? OR COALESCE(i.description,'') ILIKE ?) ORDER BY q.id DESC LIMIT 50",like,7);
   search(out,"Sales Returns","SALES_RETURN","/fxml/pages/SalesReturns.fxml","SALES.VIEW","SELECT r.id,r.return_no,COALESCE(p.name,r.invoice_no,''),CAST(r.return_date AS text)||'  '||r.item_code||'  '||COALESCE(r.status,'') FROM return_register r LEFT JOIN party_master p ON p.id=r.party_id WHERE UPPER(r.return_type)='SALES RETURN' AND UPPER(COALESCE(r.status,'PENDING'))<>'DELETED' AND (r.return_no ILIKE ? OR COALESCE(r.invoice_no,'') ILIKE ? OR COALESCE(p.name,'') ILIKE ? OR r.item_code ILIKE ? OR COALESCE(r.reason,'') ILIKE ?) ORDER BY r.id DESC LIMIT 50",like,5);
   search(out,"Purchase Returns","PURCHASE_RETURN","/fxml/pages/PurchaseReturns.fxml","PURCHASE.VIEW","SELECT r.id,r.return_no,COALESCE(p.name,r.invoice_no,''),CAST(r.return_date AS text)||'  '||r.item_code||'  '||COALESCE(r.status,'') FROM return_register r LEFT JOIN party_master p ON p.id=r.party_id WHERE UPPER(r.return_type)='PURCHASE RETURN' AND UPPER(COALESCE(r.status,'PENDING'))<>'DELETED' AND (r.return_no ILIKE ? OR COALESCE(r.invoice_no,'') ILIKE ? OR COALESCE(p.name,'') ILIKE ? OR r.item_code ILIKE ? OR COALESCE(r.reason,'') ILIKE ?) ORDER BY r.id DESC LIMIT 50",like,5);
   search(out,"Payments","SALE","/fxml/pages/RecordPayment.fxml","SALES.VIEW","SELECT p.document_id,sh.invoice_no,COALESCE(pm.name,'Sales payment'),CAST(p.payment_date AS text)||'  ₹'||to_char(p.amount,'FM999999990.00')||'  '||p.payment_mode||'  '||COALESCE(p.reference_no,'') FROM payment_record p JOIN sales_header sh ON sh.id=p.document_id LEFT JOIN party_master pm ON pm.id=sh.customer_id WHERE UPPER(p.document_type)='SALE' AND (COALESCE(p.reference_no,'') ILIKE ? OR sh.invoice_no ILIKE ? OR p.payment_mode ILIKE ? OR COALESCE(p.notes,'') ILIKE ? OR COALESCE(p.received_from,'') ILIKE ? OR COALESCE(p.created_by,'') ILIKE ? OR COALESCE(pm.name,'') ILIKE ?) ORDER BY p.id DESC LIMIT 50",like,7);
   search(out,"Payments","PURCHASE","/fxml/pages/PurchasePayment.fxml","PURCHASE.VIEW","SELECT p.document_id,ph.invoice_no,COALESCE(pm.name,'Purchase payment'),CAST(p.payment_date AS text)||'  ₹'||to_char(p.amount,'FM999999990.00')||'  '||p.payment_mode||'  '||COALESCE(p.reference_no,'') FROM payment_record p JOIN purchase_header ph ON ph.id=p.document_id LEFT JOIN party_master pm ON pm.id=ph.supplier_id WHERE UPPER(p.document_type)='PURCHASE' AND (COALESCE(p.reference_no,'') ILIKE ? OR ph.invoice_no ILIKE ? OR p.payment_mode ILIKE ? OR COALESCE(p.notes,'') ILIKE ? OR COALESCE(p.received_from,'') ILIKE ? OR COALESCE(p.created_by,'') ILIKE ? OR COALESCE(pm.name,'') ILIKE ?) ORDER BY p.id DESC LIMIT 50",like,7);
   search(out,"Bank / Expense Entries","FINANCE","/fxml/pages/BankExpense.fxml","BANK_EXPENSE.VIEW","SELECT f.id,f.voucher_no,COALESCE(p.name,f.category,f.voucher_type),CAST(f.voucher_date AS text)||'  ₹'||to_char(f.amount,'FM999999990.00')||'  '||COALESCE(f.payment_mode,'') FROM finance_register f LEFT JOIN party_master p ON p.id=f.party_id WHERE f.voucher_no ILIKE ? OR f.voucher_type ILIKE ? OR COALESCE(p.name,'') ILIKE ? OR COALESCE(f.category,'') ILIKE ? OR COALESCE(f.reference_no,'') ILIKE ? OR COALESCE(f.notes,'') ILIKE ? ORDER BY f.id DESC LIMIT 50",like,6);
   search(out,"Bank Statement","BANK_STATEMENT","/fxml/pages/BankStatement.fxml","BANK_EXPENSE.VIEW","SELECT t.id,COALESCE(t.original_reference,'Row '||CAST(t.source_row_number AS text)),COALESCE(t.original_description,''),t.transaction_date||'  Debit ₹'||to_char(t.debit_amount,'FM999999990.00')||'  Credit ₹'||to_char(t.credit_amount,'FM999999990.00')||'  '||t.status FROM bank_statement_transaction t WHERE COALESCE(t.original_reference,'') ILIKE ? OR COALESCE(t.original_description,'') ILIKE ? OR COALESCE(t.notes,'') ILIKE ? OR COALESCE(t.status,'') ILIKE ? ORDER BY t.id DESC LIMIT 50",like,4);
   search(out,"Reminders","REMINDER","/fxml/pages/ReminderCenter.fxml","REMINDERS.VIEW","SELECT id,COALESCE(reference_no,'Reminder #'||CAST(id AS text)),title,due_date||'  '||priority||'  '||status FROM reminder_register WHERE title ILIKE ? OR COALESCE(reference_no,'') ILIKE ? OR COALESCE(notes,'') ILIKE ? OR status ILIKE ? OR priority ILIKE ? ORDER BY id DESC LIMIT 50",like,5);
   search(out,"Communications","COMMUNICATION","/fxml/pages/CommunicationCenter.fxml","COMMUNICATION.VIEW","SELECT id,entity_type||' #'||CAST(entity_id AS text),COALESCE(subject,recipient,channel),channel||'  '||status||'  '||COALESCE(recipient,'') FROM communication_log WHERE entity_type ILIKE ? OR channel ILIKE ? OR COALESCE(recipient,'') ILIKE ? OR COALESCE(subject,'') ILIKE ? OR COALESCE(status,'') ILIKE ? OR COALESCE(error_message,'') ILIKE ? ORDER BY id DESC LIMIT 50",like,6);
   search(out,"Inventory Adjustments","STOCK_ADJUSTMENT","/fxml/pages/Inventory.fxml","INVENTORY.VIEW","SELECT id,COALESCE(reference_no,'Adjustment #'||CAST(id AS text)),item_code,adjustment_date||'  '||adjustment_type||'  Qty '||quantity||'  '||reason FROM stock_adjustment WHERE item_code ILIKE ? OR adjustment_type ILIKE ? OR reason ILIKE ? OR COALESCE(reference_no,'') ILIKE ? OR COALESCE(created_by,'') ILIKE ? ORDER BY id DESC LIMIT 50",like,5);
   search(out,"Master Data","MASTER","/fxml/pages/Masterdata.fxml","MASTERS.VIEW","SELECT lm.id,lm.lookup_code,lm.lookup_value,lm.lookup_type||'  '||COALESCE(lm.description,'') FROM lookup_master lm WHERE lm.lookup_code ILIKE ? OR lm.lookup_value ILIKE ? OR lm.lookup_type ILIKE ? OR COALESCE(lm.description,'') ILIKE ? OR EXISTS (SELECT 1 FROM lookup_code_alias a WHERE a.lookup_id=lm.id AND a.alias_code ILIKE ?) ORDER BY lm.lookup_type,lm.display_order LIMIT 50",like,5);
   search(out,"Users","USER","/fxml/pages/UserAccess.fxml","USERS.VIEW","SELECT id,username,COALESCE(full_name,username),COALESCE(email,'')||'  '||COALESCE(role,'') FROM users WHERE username ILIKE ? OR COALESCE(full_name,'') ILIKE ? OR COALESCE(email,'') ILIKE ? OR COALESCE(role,'') ILIKE ? ORDER BY username LIMIT 50",like,4);
   return out.stream().limit(500).toList();
 }
 private void search(List<SupportDtos.SearchRow> out,String module,String moduleKey,String target,String permission,String sql,String like,int n){
   if(!searchPermissionAllowed(permission))return;
   try{Object[] a=new Object[n];Arrays.fill(a,like);jdbc.query(sql,r->{out.add(new SupportDtos.SearchRow(module,moduleKey,r.getLong(1),Objects.toString(r.getObject(2),""),Objects.toString(r.getObject(3),""),Objects.toString(r.getObject(4),""),target,permission));},a);}catch(Exception ignored){}
 }
 private boolean searchPermissionAllowed(String permission){
   if(permission==null||permission.isBlank())return true;
   String role=CurrentUser.require().role();
   if("ADMIN".equalsIgnoreCase(role))return true;
   String[] parts=permission.trim().toUpperCase(Locale.ROOT).split("\\.",2);
   if(parts.length!=2)return false;
   try{
     Long allowed=jdbc.queryForObject("SELECT COUNT(*) FROM role_permission rp JOIN permissions p ON p.id=rp.permission_id WHERE UPPER(TRIM(COALESCE(rp.role_code,'')))=? AND UPPER(p.module_name)=? AND UPPER(p.action_name)=? AND p.active=1 AND COALESCE(rp.allowed,0)=1",Long.class,role.toUpperCase(Locale.ROOT),parts[0],parts[1]);
     return allowed!=null&&allowed>0;
   }catch(Exception ignored){return false;}
 }
 private void requireSalesDocument(String type){String normalized=type==null?"":type.trim().toUpperCase(Locale.ROOT);if(!Set.of("SALE","PURCHASE").contains(normalized))throw new IllegalArgumentException("Document type must be SALE or PURCHASE");CurrentUser.requirePermission("PURCHASE".equals(normalized)?"PURCHASE.VIEW":"SALES.VIEW","Payment access");}
 private String documentTableUnchecked(String type){String normalized=type==null?"":type.trim().toUpperCase(Locale.ROOT);if(!Set.of("SALE","PURCHASE").contains(normalized))throw new IllegalArgumentException("Document type must be SALE or PURCHASE");return "SALE".equals(normalized)?"sales_header":"purchase_header";}
 private void requireSalesEntity(String type){requireEntityPermission(type,"VIEW","Activity access");}
 private void requireEntityPermission(String type,String action,String label){String normalized=type==null?"":type.trim().toUpperCase(Locale.ROOT);String module=switch(normalized){case "PURCHASE","PURCHASE RETURN"->"PURCHASE";case "QUOTATION"->"QUOTATION";default->"SALES";};CurrentUser.requirePermission(module+"."+action,label);}
 @Transactional(readOnly=true) public SupportDtos.ReportSummary businessReport(String from,String to){
  Object[] a={LocalDate.parse(from),LocalDate.parse(to)};
  String saleActive="UPPER(COALESCE(document_status,'')) NOT IN ('DELETED','CANCELLED','REJECTED','PENDING APPROVAL')";
  String purchaseActive="UPPER(COALESCE(document_status,'')) NOT IN ('DELETED','CANCELLED','DRAFT','REJECTED','PENDING APPROVAL') AND COALESCE(inventory_posted,false)=true";
  double grossSales=n("SELECT COALESCE(SUM(total_amount),0) FROM sales_header WHERE "+saleActive+" AND dse_safe_date(invoice_date) BETWEEN ? AND ?",a);
  double salesReturns=n("SELECT COALESCE(SUM(amount),0) FROM return_register WHERE UPPER(COALESCE(return_type,'')) IN ('SALE RETURN','SALES RETURN') AND UPPER(COALESCE(status,''))='APPROVED' AND dse_safe_date(return_date) BETWEEN ? AND ?",a);
  double grossPurchases=n("SELECT COALESCE(SUM(total_amount),0) FROM purchase_header WHERE "+purchaseActive+" AND dse_safe_date(invoice_date) BETWEEN ? AND ?",a);
  double purchaseReturns=n("SELECT COALESCE(SUM(amount),0) FROM return_register WHERE UPPER(COALESCE(return_type,''))='PURCHASE RETURN' AND UPPER(COALESCE(status,''))='APPROVED' AND dse_safe_date(return_date) BETWEEN ? AND ?",a);
  double sales=Math.max(0,grossSales-salesReturns),purchases=Math.max(0,grossPurchases-purchaseReturns);
  double stock=n("SELECT COALESCE(SUM(COALESCE(s.quantity,i.opening_stock,0)*COALESCE(s.average_unit_cost,i.purchase_price,0)),0) FROM item_master i LEFT JOIN inventory_cost_state s ON s.item_code=i.item_code");
  List<List<String>> sc=rows("SELECT COALESCE(pm.name,'Unknown'),COUNT(*),COALESCE(SUM(sh.total_amount),0) FROM sales_header sh LEFT JOIN party_master pm ON pm.id=sh.customer_id WHERE UPPER(COALESCE(sh.document_status,'')) NOT IN ('DELETED','CANCELLED','REJECTED','PENDING APPROVAL') AND dse_safe_date(sh.invoice_date) BETWEEN ? AND ? GROUP BY pm.id,pm.name ORDER BY 3 DESC",a),
   ps=rows("SELECT COALESCE(pm.name,'Unknown'),COUNT(*),COALESCE(SUM(ph.total_amount),0) FROM purchase_header ph LEFT JOIN party_master pm ON pm.id=ph.supplier_id WHERE UPPER(COALESCE(ph.document_status,'')) NOT IN ('DELETED','CANCELLED','DRAFT','REJECTED','PENDING APPROVAL') AND COALESCE(ph.inventory_posted,false)=true AND dse_safe_date(ph.invoice_date) BETWEEN ? AND ? GROUP BY pm.id,pm.name ORDER BY 3 DESC",a),
   low=rows("SELECT description,COALESCE(opening_stock,0),COALESCE(minimum_stock,0),COALESCE(unit,'') FROM item_master WHERE COALESCE(opening_stock,0)<=COALESCE(minimum_stock,0) ORDER BY opening_stock,description");
  return new SupportDtos.ReportSummary(sales,purchases,stock,sc,ps,low);
 }
 private List<List<String>> rows(String q,Object...a){return jdbc.query(q,(r,i)->{var md=r.getMetaData();List<String>x=new ArrayList<>();for(int c=1;c<=md.getColumnCount();c++)x.add(Objects.toString(r.getObject(c),""));return x;},a);} private double n(String q,Object...a){Double d=jdbc.queryForObject(q,Double.class,a);return d==null?0:d;}
 @Transactional(readOnly=true) public String setting(String key,String def){requireSharedSettingKey(key);try{String v=jdbc.queryForObject("SELECT setting_value FROM application_setting WHERE setting_key=?",String.class,key);return v==null?def:v;}catch(Exception e){return def;}}
 @Transactional public void setSettings(Map<String,String> values){if(values==null||values.isEmpty())return;for(var entry:values.entrySet())setSetting(entry.getKey(),entry.getValue());}
 @Transactional public void setSetting(String key,String value){requireSharedSettingKey(key);String k=key==null?"":key.trim();if((k.startsWith("security.auth.")||k.startsWith("storage."))&&!"ADMIN".equalsIgnoreCase(CurrentUser.require().role()))throw new SecurityException(k.startsWith("storage.")?"Storage and retention settings can be changed only by an administrator":"Authentication policy can be changed only by an administrator");jdbc.update("INSERT INTO application_setting(setting_key,setting_value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=CURRENT_TIMESTAMP",key,value);if(k.startsWith("security.auth.")||k.startsWith("storage."))jdbc.update("INSERT INTO activity_log(entity_type,entity_id,action,detail,created_by,created_at) VALUES(?,NULL,?,?,?,?)",k.startsWith("storage.")?"STORAGE":"SECURITY",k.startsWith("storage.")?"STORAGE_POLICY_CHANGED":"MFA_POLICY_CHANGED",k+"="+(value==null?"":value),CurrentUser.require().username(),BusinessClock.nowUtcText());}
 private static void requireSharedSettingKey(String key){String k=key==null?"":key.trim();if(k.isBlank()||k.length()>160||k.toLowerCase(Locale.ROOT).matches(".*(password|secret|token|credential).*"))throw new IllegalArgumentException("Setting key is not shareable");if(!(k.startsWith("company.")||k.startsWith("payment.")||k.startsWith("invoice.")||k.startsWith("business.")||k.startsWith("tax.")||k.startsWith("reference.")||k.startsWith("backup.")||k.startsWith("storage.")||k.startsWith("security.session.")||k.startsWith("security.auth.")||k.equals("date.format")||k.equals("timezone.business")))throw new IllegalArgumentException("Setting key is not part of the server-authoritative business configuration");}
 @Transactional public void ensureBackupTables(){jdbc.execute("CREATE TABLE IF NOT EXISTS application_metadata(metadata_key TEXT PRIMARY KEY,metadata_value TEXT NOT NULL)");jdbc.execute("CREATE TABLE IF NOT EXISTS application_setting(setting_key TEXT PRIMARY KEY,setting_value TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");jdbc.execute("CREATE TABLE IF NOT EXISTS backup_history(id BIGSERIAL PRIMARY KEY,file_name TEXT NOT NULL UNIQUE,original_name TEXT,source_type TEXT NOT NULL DEFAULT 'MANUAL',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,file_size INTEGER NOT NULL DEFAULT 0,integrity_status TEXT NOT NULL DEFAULT 'AVAILABLE',schema_version INTEGER,application_id TEXT,created_by TEXT)");}
 @Transactional public void ensureApplicationMetadata(String appId,int schemaVersion,String appVersion){ensureBackupTables();metadata("application.id",appId);metadata("schema.version",String.valueOf(schemaVersion));metadata("application.version",appVersion);}
 private void metadata(String k,String v){jdbc.update("INSERT INTO application_metadata(metadata_key,metadata_value) VALUES(?,?) ON CONFLICT(metadata_key) DO UPDATE SET metadata_value=excluded.metadata_value",k,v);}
 @Transactional(readOnly=true) public SupportDtos.BackupMeta backupMeta(String file){List<SupportDtos.BackupMeta>x=jdbc.query("SELECT file_name,source_type,integrity_status,schema_version,application_id,file_size FROM backup_history WHERE file_name=?",(r,i)->new SupportDtos.BackupMeta(r.getString(1),r.getString(2),r.getString(3),(Integer)r.getObject(4),r.getString(5),r.getLong(6)),file);return x.isEmpty()?null:x.getFirst();}
 @Transactional public void saveBackupMeta(SupportDtos.BackupMeta d){ensureBackupTables();jdbc.update("INSERT INTO backup_history(file_name,original_name,source_type,created_at,file_size,integrity_status,schema_version,application_id) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(file_name) DO UPDATE SET source_type=excluded.source_type,file_size=excluded.file_size,integrity_status=excluded.integrity_status,schema_version=excluded.schema_version,application_id=excluded.application_id",d.fileName(),d.fileName(),d.source(),BusinessClock.nowUtcText(),d.fileSize(),d.integrityStatus(),d.schemaVersion(),d.applicationId());}
 @Transactional public void legacyConstraints(boolean add){String[] addSql={"ALTER TABLE quotation_line ADD CONSTRAINT quotation_line_item_code_fkey FOREIGN KEY(item_code) REFERENCES item_master(item_code) NOT VALID","ALTER TABLE quotation_line ADD CONSTRAINT quotation_line_quotation_id_fkey FOREIGN KEY(quotation_id) REFERENCES quotation_header(id) ON DELETE CASCADE NOT VALID","ALTER TABLE return_register ADD CONSTRAINT return_register_item_code_fkey FOREIGN KEY(item_code) REFERENCES item_master(item_code) NOT VALID","ALTER TABLE stock_adjustment ADD CONSTRAINT stock_adjustment_item_code_fkey FOREIGN KEY(item_code) REFERENCES item_master(item_code) NOT VALID"};String[] dropSql={"ALTER TABLE quotation_line DROP CONSTRAINT IF EXISTS quotation_line_item_code_fkey","ALTER TABLE quotation_line DROP CONSTRAINT IF EXISTS quotation_line_quotation_id_fkey","ALTER TABLE return_register DROP CONSTRAINT IF EXISTS return_register_item_code_fkey","ALTER TABLE stock_adjustment DROP CONSTRAINT IF EXISTS stock_adjustment_item_code_fkey"};for(String q:add?addSql:dropSql){try{jdbc.execute(q);}catch(Exception e){if(!add)throw e;}}}
}
