package org.example.server.support;
import org.example.server.persistence.JpaNativeRepository;import org.example.server.security.CurrentUser;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDate;import java.util.*;
@Service public class SupportService {
 private final JpaNativeRepository jdbc; private final PaymentIntegrityService paymentIntegrity; public SupportService(JpaNativeRepository jdbc,PaymentIntegrityService paymentIntegrity){this.jdbc=jdbc;this.paymentIntegrity=paymentIntegrity;}
 @Transactional(readOnly=true) public List<SupportDtos.SavedView> savedViews(String screen,Integer ignoredUserId){return jdbc.query("SELECT view_name,filter_json FROM saved_filter WHERE screen_key=? AND (user_id=? OR user_id IS NULL) ORDER BY view_name",(r,i)->new SupportDtos.SavedView(r.getString(1),r.getString(2)),screen,CurrentUser.require().id());}
 @Transactional public void saveView(SupportDtos.SavedViewSave d){jdbc.update("INSERT INTO saved_filter(user_id,screen_key,view_name,filter_json) VALUES(?,?,?,?) ON CONFLICT(user_id,screen_key,view_name) DO UPDATE SET filter_json=excluded.filter_json",CurrentUser.require().id(),d.screen(),d.name(),d.data());}
 @Transactional(readOnly=true) public List<SupportDtos.PaymentRow> payments(String type,int id){requireSalesDocument(type);return jdbc.query("SELECT id,payment_date,COALESCE(reference_no,''),payment_mode,amount,COALESCE(notes,''),COALESCE(received_from,''),COALESCE(attachment_path,'') FROM payment_record WHERE document_type=? AND document_id=? ORDER BY payment_date DESC,id DESC",(r,i)->new SupportDtos.PaymentRow(r.getInt(1),String.valueOf(r.getObject(2)),r.getString(3),r.getString(4),r.getDouble(5),r.getString(6),r.getString(7),r.getString(8)),type,id);}
 @Transactional public void recordPayment(SupportDtos.PaymentRequest d){requireSalesDocument(d==null?null:d.documentType());paymentIntegrity.record(d);}
 @Transactional public void communication(SupportDtos.CommunicationRequest d){requireSalesEntity(d.entityType());jdbc.update("INSERT INTO communication_log(entity_type,entity_id,channel,recipient,subject,status,error_message,created_by) VALUES(?,?,?,?,?,?,?,?)",d.entityType(),d.entityId(),d.channel(),d.recipient(),d.subject(),d.status(),d.errorMessage(),CurrentUser.require().username());}
 @Transactional(readOnly=true) public List<SupportDtos.CommunicationRow> communications(){return jdbc.query("SELECT c.id,c.entity_type,c.entity_id,COALESCE(CASE WHEN c.entity_type='SALE' THEN (SELECT invoice_no FROM sales_header WHERE id=c.entity_id) WHEN c.entity_type='PURCHASE' THEN (SELECT invoice_no FROM purchase_header WHERE id=c.entity_id) WHEN c.entity_type='QUOTATION' THEN (SELECT quotation_no FROM quotation_header WHERE id=c.entity_id) END,c.subject,c.entity_type||' #'||c.entity_id),c.channel,COALESCE(c.recipient,''),COALESCE(c.subject,''),COALESCE(c.status,''),COALESCE(c.error_message,''),COALESCE(c.created_by,''),COALESCE(c.created_at::text,'') FROM communication_log c ORDER BY c.created_at DESC,c.id DESC LIMIT 500",(r,i)->new SupportDtos.CommunicationRow(r.getInt(1),r.getString(2),r.getInt(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11)));}
 @Transactional public void markWhatsappSent(String type,int id){String table=documentTable(type);try{jdbc.update("UPDATE "+table+" SET whatsapp_sent=1 WHERE id=?",id);}catch(Exception ignored){}}
 @Transactional public void setAttachment(String type,int id,String path){String table=documentTable(type);jdbc.update("UPDATE "+table+" SET attachment_path=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",path,id);}
 @Transactional public void setNotes(String type,int id,String notes){String table=documentTable(type);String col="SALE".equalsIgnoreCase(type)?"notes":"remarks";jdbc.update("UPDATE "+table+" SET "+col+"=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",notes,id);}
 @Transactional public void activity(String type,int id,String action,String detail,String ignoredUser){requireSalesEntity(type);jdbc.update("INSERT INTO activity_log(entity_type,entity_id,action,detail,created_by) VALUES(?,?,?,?,?)",type,id,action,detail,CurrentUser.require().username());}

 @Transactional(readOnly=true) public String returnPartyEmail(String no){if(CurrentUser.isSales()){String type=jdbc.queryForObject("SELECT MAX(return_type) FROM return_register WHERE return_no=?",String.class,no);if(!"SALES RETURN".equalsIgnoreCase(type))throw new SecurityException("Purchase returns require Manager or Admin access");}List<String>x=jdbc.query("SELECT COALESCE(pm.email,\'\') FROM return_register rr LEFT JOIN party_master pm ON pm.id=rr.party_id WHERE rr.return_no=? LIMIT 1",(r,i)->r.getString(1),no);return x.isEmpty()?"":x.getFirst();}
 @Transactional public String duplicateSale(int id,String user){String source=jdbc.queryForObject("SELECT invoice_no FROM sales_header WHERE id=?",String.class,id);if(source==null)throw new IllegalArgumentException("Sales invoice not found");String prefix="INV-";String next;try{Long n=jdbc.queryForObject("SELECT COALESCE(MAX(CAST(substring(invoice_no from '([0-9]+)$') AS BIGINT)),0)+1 FROM sales_header WHERE invoice_no LIKE 'INV-%'",Long.class);next=prefix+String.format(java.util.Locale.ROOT,"%04d",n==null?1L:n);}catch(Exception e){next=prefix+System.currentTimeMillis();}Integer newId=jdbc.queryForObject("INSERT INTO sales_header(invoice_no,invoice_date,customer_id,subtotal,gst_amount,total_amount,remarks,created_at,email_sent,due_date,paid_amount,payment_status,whatsapp_sent,invoice_type,salesperson,source,notes) SELECT ?,CURRENT_DATE,customer_id,subtotal,gst_amount,total_amount,?,CURRENT_TIMESTAMP,0,CURRENT_DATE+30,0,'PENDING',0,invoice_type,salesperson,source,notes FROM sales_header WHERE id=? RETURNING id",Integer.class,next,"Duplicated from "+source,id);jdbc.update("INSERT INTO sales_line(sales_id,item_code,quantity,rate,discount_percent,discount_amount,gst_percent,line_total) SELECT ?,item_code,quantity,rate,discount_percent,discount_amount,gst_percent,line_total FROM sales_line WHERE sales_id=?",newId,id);jdbc.query("SELECT item_code,quantity FROM sales_line WHERE sales_id=?",r->{jdbc.update("UPDATE item_master SET opening_stock=COALESCE(opening_stock,0)-? WHERE item_code=?",r.getDouble(2),r.getString(1));},id);activity("SALE",newId==null?0:newId,"DUPLICATED","From "+source,user);return next;}
 @Transactional public void cancelPurchase(int id){int changed=jdbc.update("UPDATE purchase_header SET document_status='CANCELLED',updated_at=CURRENT_TIMESTAMP WHERE id=? AND COALESCE(document_status,'')<>'CANCELLED'",id);if(changed>0)jdbc.query("SELECT item_code,quantity FROM purchase_line WHERE purchase_id=?",r->{jdbc.update("UPDATE item_master SET opening_stock=COALESCE(opening_stock,0)-? WHERE item_code=?",r.getDouble(2),r.getString(1));},id);}
 @Transactional(readOnly=true) public List<SupportDtos.SearchRow> search(String q){String like="%"+(q==null?"":q.trim())+"%";List<SupportDtos.SearchRow> out=new ArrayList<>();search(out,"Item","/fxml/pages/ItemMaster.fxml","SELECT item_code,description,COALESCE(category,'')||'  Stock: '||COALESCE(opening_stock,0) FROM item_master WHERE item_code ILIKE ? OR description ILIKE ? OR category ILIKE ? OR brand ILIKE ? LIMIT 20",like,4);search(out,"Customer","/fxml/pages/Customer.fxml","SELECT party_code,name,COALESCE(phone,'')||'  '||COALESCE(gstin,'') FROM party_master WHERE party_type='CUSTOMER' AND (party_code ILIKE ? OR name ILIKE ? OR phone ILIKE ? OR email ILIKE ? OR gstin ILIKE ?) LIMIT 20",like,5);search(out,"Supplier","/fxml/pages/Suppliers.fxml","SELECT party_code,name,COALESCE(phone,'')||'  '||COALESCE(gstin,'') FROM party_master WHERE party_type='SUPPLIER' AND (party_code ILIKE ? OR name ILIKE ? OR phone ILIKE ? OR email ILIKE ? OR gstin ILIKE ?) LIMIT 20",like,5);search(out,"Sales Invoice","/fxml/pages/SalesList.fxml","SELECT s.invoice_no,p.name,CAST(s.invoice_date AS text)||'  ₹'||to_char(s.total_amount,'FM999999990.00')||'  '||COALESCE(s.payment_status,'') FROM sales_header s JOIN party_master p ON p.id=s.customer_id WHERE s.invoice_no ILIKE ? OR p.name ILIKE ? LIMIT 20",like,2);search(out,"Purchase Invoice","/fxml/pages/PurchaseList.fxml","SELECT s.invoice_no,p.name,CAST(s.invoice_date AS text)||'  ₹'||to_char(s.total_amount,'FM999999990.00')||'  '||COALESCE(s.payment_status,'') FROM purchase_header s JOIN party_master p ON p.id=s.supplier_id WHERE s.invoice_no ILIKE ? OR p.name ILIKE ? OR COALESCE(s.reference_no,'') ILIKE ? LIMIT 20",like,3);search(out,"Quotation","/fxml/pages/Quotations.fxml","SELECT q.quotation_no,p.name,CAST(q.quotation_date AS text)||'  ₹'||to_char(q.total_amount,'FM999999990.00')||'  '||q.status FROM quotation_header q JOIN party_master p ON p.id=q.customer_id WHERE q.quotation_no ILIKE ? OR p.name ILIKE ? OR q.status ILIKE ? LIMIT 20",like,3);search(out,"Return","/fxml/pages/Operations.fxml","SELECT return_no,COALESCE(invoice_no,''),CAST(return_date AS text)||'  '||return_type||'  '||status FROM return_register WHERE return_no ILIKE ? OR COALESCE(invoice_no,'') ILIKE ? OR COALESCE(reason,'') ILIKE ? LIMIT 20",like,3);search(out,"Payment","/fxml/pages/Operations.fxml","SELECT COALESCE(reference_no,'Payment #'||CAST(id AS text)),document_type,CAST(payment_date AS text)||'  ₹'||to_char(amount,'FM999999990.00')||'  '||payment_mode FROM payment_record WHERE COALESCE(reference_no,'') ILIKE ? OR document_type ILIKE ? OR payment_mode ILIKE ? LIMIT 20",like,3);search(out,"Master Value","/fxml/pages/Masterdata.fxml","SELECT lookup_code,lookup_value,lookup_type||'  '||COALESCE(description,'') FROM lookup_master WHERE lookup_code ILIKE ? OR lookup_value ILIKE ? OR lookup_type ILIKE ? OR COALESCE(description,'') ILIKE ? LIMIT 20",like,4);return out.stream().limit(100).toList();}
 private void search(List<SupportDtos.SearchRow> out,String module,String target,String sql,String like,int n){try{Object[] a=new Object[n];Arrays.fill(a,like);jdbc.query(sql,r->{out.add(new SupportDtos.SearchRow(module,Objects.toString(r.getObject(1),""),Objects.toString(r.getObject(2),""),Objects.toString(r.getObject(3),""),target));},a);}catch(Exception ignored){}}
 private void requireSalesDocument(String type){String normalized=type==null?"":type.trim().toUpperCase(Locale.ROOT);if(!Set.of("SALE","PURCHASE").contains(normalized))throw new IllegalArgumentException("Document type must be SALE or PURCHASE");if(CurrentUser.isSales()&&!"SALE".equals(normalized))throw new SecurityException("Purchase payments require Manager or Admin access");}
 private String documentTable(String type){requireSalesDocument(type);return "SALE".equalsIgnoreCase(type)?"sales_header":"purchase_header";}
 private void requireSalesEntity(String type){if(CurrentUser.isSales()&&!Set.of("SALE","QUOTATION","SALES RETURN").contains(type==null?"":type.trim().toUpperCase(Locale.ROOT)))throw new SecurityException("This activity requires Manager or Admin access");}
 @Transactional(readOnly=true) public SupportDtos.ReportSummary businessReport(String from,String to){Object[] a={LocalDate.parse(from),LocalDate.parse(to)};double sales=n("SELECT COALESCE(SUM(total_amount),0) FROM sales_header WHERE CAST(invoice_date AS DATE) BETWEEN ? AND ?",a),purchases=n("SELECT COALESCE(SUM(total_amount),0) FROM purchase_header WHERE CAST(invoice_date AS DATE) BETWEEN ? AND ?",a),stock=n("SELECT COALESCE(SUM(COALESCE(opening_stock,0)*COALESCE(purchase_price,0)),0) FROM item_master");List<List<String>> sc=rows("SELECT COALESCE(pm.name,'Unknown'),COUNT(*),COALESCE(SUM(sh.total_amount),0) FROM sales_header sh LEFT JOIN party_master pm ON pm.id=sh.customer_id WHERE CAST(sh.invoice_date AS DATE) BETWEEN ? AND ? GROUP BY pm.id,pm.name ORDER BY 3 DESC",a),ps=rows("SELECT COALESCE(pm.name,'Unknown'),COUNT(*),COALESCE(SUM(ph.total_amount),0) FROM purchase_header ph LEFT JOIN party_master pm ON pm.id=ph.supplier_id WHERE CAST(ph.invoice_date AS DATE) BETWEEN ? AND ? GROUP BY pm.id,pm.name ORDER BY 3 DESC",a),low=rows("SELECT description,COALESCE(opening_stock,0),COALESCE(minimum_stock,0),COALESCE(unit,'') FROM item_master WHERE COALESCE(opening_stock,0)<=COALESCE(minimum_stock,0) ORDER BY opening_stock,description");return new SupportDtos.ReportSummary(sales,purchases,stock,sc,ps,low);}
 private List<List<String>> rows(String q,Object...a){return jdbc.query(q,(r,i)->{var md=r.getMetaData();List<String>x=new ArrayList<>();for(int c=1;c<=md.getColumnCount();c++)x.add(Objects.toString(r.getObject(c),""));return x;},a);} private double n(String q,Object...a){Double d=jdbc.queryForObject(q,Double.class,a);return d==null?0:d;}
 @Transactional(readOnly=true) public String setting(String key,String def){try{String v=jdbc.queryForObject("SELECT setting_value FROM application_setting WHERE setting_key=?",String.class,key);return v==null?def:v;}catch(Exception e){return def;}}
 @Transactional public void setSetting(String key,String value){jdbc.update("INSERT INTO application_setting(setting_key,setting_value) VALUES(?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value",key,value);}
 @Transactional public void ensureBackupTables(){jdbc.execute("CREATE TABLE IF NOT EXISTS application_metadata(metadata_key TEXT PRIMARY KEY,metadata_value TEXT NOT NULL)");jdbc.execute("CREATE TABLE IF NOT EXISTS application_setting(setting_key TEXT PRIMARY KEY,setting_value TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");jdbc.execute("CREATE TABLE IF NOT EXISTS backup_history(id BIGSERIAL PRIMARY KEY,file_name TEXT NOT NULL UNIQUE,original_name TEXT,source_type TEXT NOT NULL DEFAULT 'MANUAL',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,file_size INTEGER NOT NULL DEFAULT 0,integrity_status TEXT NOT NULL DEFAULT 'AVAILABLE',schema_version INTEGER,application_id TEXT,created_by TEXT)");}
 @Transactional public void ensureApplicationMetadata(String appId,int schemaVersion,String appVersion){ensureBackupTables();metadata("application.id",appId);metadata("schema.version",String.valueOf(schemaVersion));metadata("application.version",appVersion);}
 private void metadata(String k,String v){jdbc.update("INSERT INTO application_metadata(metadata_key,metadata_value) VALUES(?,?) ON CONFLICT(metadata_key) DO UPDATE SET metadata_value=excluded.metadata_value",k,v);}
 @Transactional(readOnly=true) public SupportDtos.BackupMeta backupMeta(String file){List<SupportDtos.BackupMeta>x=jdbc.query("SELECT file_name,source_type,integrity_status,schema_version,application_id,file_size FROM backup_history WHERE file_name=?",(r,i)->new SupportDtos.BackupMeta(r.getString(1),r.getString(2),r.getString(3),(Integer)r.getObject(4),r.getString(5),r.getLong(6)),file);return x.isEmpty()?null:x.getFirst();}
 @Transactional public void saveBackupMeta(SupportDtos.BackupMeta d){ensureBackupTables();jdbc.update("INSERT INTO backup_history(file_name,original_name,source_type,created_at,file_size,integrity_status,schema_version,application_id) VALUES(?,?,?,CURRENT_TIMESTAMP,?,?,?,?) ON CONFLICT(file_name) DO UPDATE SET source_type=excluded.source_type,file_size=excluded.file_size,integrity_status=excluded.integrity_status,schema_version=excluded.schema_version,application_id=excluded.application_id",d.fileName(),d.fileName(),d.source(),d.fileSize(),d.integrityStatus(),d.schemaVersion(),d.applicationId());}
 @Transactional public void legacyConstraints(boolean add){String[] addSql={"ALTER TABLE quotation_line ADD CONSTRAINT quotation_line_item_code_fkey FOREIGN KEY(item_code) REFERENCES item_master(item_code) NOT VALID","ALTER TABLE quotation_line ADD CONSTRAINT quotation_line_quotation_id_fkey FOREIGN KEY(quotation_id) REFERENCES quotation_header(id) ON DELETE CASCADE NOT VALID","ALTER TABLE return_register ADD CONSTRAINT return_register_item_code_fkey FOREIGN KEY(item_code) REFERENCES item_master(item_code) NOT VALID","ALTER TABLE role_permission ADD CONSTRAINT role_permission_role_id_fkey FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE NOT VALID","ALTER TABLE stock_adjustment ADD CONSTRAINT stock_adjustment_item_code_fkey FOREIGN KEY(item_code) REFERENCES item_master(item_code) NOT VALID"};String[] dropSql={"ALTER TABLE quotation_line DROP CONSTRAINT IF EXISTS quotation_line_item_code_fkey","ALTER TABLE quotation_line DROP CONSTRAINT IF EXISTS quotation_line_quotation_id_fkey","ALTER TABLE return_register DROP CONSTRAINT IF EXISTS return_register_item_code_fkey","ALTER TABLE role_permission DROP CONSTRAINT IF EXISTS role_permission_role_id_fkey","ALTER TABLE stock_adjustment DROP CONSTRAINT IF EXISTS stock_adjustment_item_code_fkey"};for(String q:add?addSql:dropSql){try{jdbc.execute(q);}catch(Exception e){if(!add)throw e;}}}
}
